//! Proof-carrying contract propositions for `elicit_ui`.
//!
//! # Modules
//!
//! - [`wcag`] — WCAG 2.2 (78 Success Criteria + sub-invariants + legacy aliases)
//! - [`ui`] — UI-pipeline propositions (`RenderComplete`, `IrSourced`)

pub mod ui;
pub mod wcag;

// Re-export everything so call sites use `elicit_ui::{WcagLevelAAValid, ...}`.
pub use ui::{IrSourced, RenderComplete};
pub use wcag::{
    // ── Legacy aliases (API back-compat) ──────────────────────────────────
    AccessibleAA,
    AltTextProvided,
    FocusVisible,
    HasLabel,
    KeyboardAccessible,
    MinTargetSize,
    NoOverflow,
    StructuredContent,
    SufficientContrast,
    ValidRole,
    WcagAbbreviationsExpanded,
    WcagAccessibleAuthentication,
    WcagAccessibleAuthenticationEnhanced,
    WcagAllFunctionalityKeyboard,
    WcagAudioControlAvailable,
    WcagAudioDescriptionOrMediaAlt,
    WcagAudioDescriptionPrerecorded,
    // 1.2 Time-based Media
    WcagAudioOnlyAlternativeProvided,
    WcagAudioOnlyLiveAlternative,
    WcagAutoUpdatePausable,
    // 2.4 Navigable
    WcagBypassBlocksMechanism,
    WcagCaptchaMultipleModalities,
    WcagCaptionsLiveProvided,
    WcagCaptionsSynchronized,
    WcagChangesOnRequest,
    WcagCharacterShortcutsDisableable,
    WcagCharacterShortcutsFocusOnly,
    WcagCharacterShortcutsRemappable,
    // 1.4 Distinguishable
    WcagColorNotSoleConveyor,
    WcagComponentPurposeIdentifiable,
    WcagConcurrentInputMechanisms,
    WcagConsistentHelpLocated,
    WcagContentReflowable,
    WcagContextSensitiveHelp,
    WcagContrastEnhancedLargeText,
    WcagContrastEnhancedNormalText,
    WcagContrastMinimumLargeText,
    WcagContrastMinimumLogotypeExcepted,
    WcagContrastMinimumNormalText,
    WcagDecorativeImageAltEmpty,
    WcagDraggingAlternative,
    // 3.3 Input Assistance
    WcagErrorIdentificationDescriptive,
    WcagErrorPreventionAll,
    WcagErrorPreventionChecked,
    WcagErrorPreventionConfirmed,
    WcagErrorPreventionLegal,
    WcagErrorPreventionReversible,
    WcagErrorSuggestionProvided,
    WcagExtendedAudioDescription,
    WcagFlashAreaBelowThreshold,
    WcagFocusAppearanceEnhancedArea,
    WcagFocusAppearanceEnhancedContrast,
    WcagFocusAppearanceMinimumArea,
    WcagFocusAppearanceMinimumContrast,
    WcagFocusIndicatorContrast,
    // 3.2 Predictable
    WcagFocusNoContextChange,
    WcagFocusOrderLogical,
    WcagFocusVisibleKeyboard,
    WcagFormLabelsProgrammatic,
    WcagHeadingStructureProgrammatic,
    WcagHeadingsDescriptive,
    WcagHoverContentDismissible,
    WcagHoverContentHoverable,
    WcagHoverContentPersistent,
    WcagIdentificationConsistent,
    WcagImagesOfTextAvoided,
    WcagImagesOfTextCustomizable,
    WcagImagesOfTextNoException,
    // 1.3 Adaptable
    WcagInfoAndRelationshipsProgrammatic,
    WcagInputNoContextChange,
    WcagInputPurposeIdentifiable,
    WcagInterruptionsPostponable,
    WcagKeyboardEscapeFromComponent,
    WcagKeyboardNoTimingPath,
    WcagKeyboardNotTrapped,
    // ── Principle 2: Operable ─────────────────────────────────────────────
    // 2.1 Keyboard Accessible
    WcagKeyboardOperable,
    WcagLabelInNameMatch,
    WcagLabelsDescriptive,
    WcagLabelsOrInstructionsPresent,
    WcagLetterSpacingAdjustable,
    WcagLevelAAAValid,
    WcagLevelAAValid,
    // ── Aggregate seams ───────────────────────────────────────────────────
    WcagLevelAValid,
    WcagLineHeightAdjustable,
    WcagLinkPurposeFromContext,
    WcagLinkPurposeLinkOnly,
    WcagListStructureProgrammatic,
    WcagLocationInNavigationSet,
    WcagLowBackgroundAudio,
    WcagMeaningfulSequencePreservable,
    WcagMediaAlternativePrerecorded,
    WcagMotionActuationAlternative,
    WcagMotionActuationDisableable,
    WcagMultiplePathsToContent,
    WcagNamePresent,
    WcagNameRoleValueProgrammatic,
    WcagNavigationConsistent,
    WcagNoHorizontalScrollVerticalText,
    WcagNoThreeFlashAbsolute,
    WcagNoTimingRequired,
    WcagNonTextContentAltDescriptive,
    WcagNonTextContentAltNonEmpty,
    // ── Principle 1: Perceivable ──────────────────────────────────────────
    // 1.1 Text Alternatives
    WcagNonTextContentAltPresent,
    WcagNonTextContrastMinimum,
    WcagOrientationNotRestricted,
    // ── Principle 3: Understandable ───────────────────────────────────────
    // 3.1 Readable
    WcagPageLanguageIdentified,
    WcagPageTitleDescriptive,
    WcagPageTitled,
    WcagParagraphSpacingAdjustable,
    // ── Principle 4: Robust ───────────────────────────────────────────────
    WcagParsingValid,
    WcagPartLanguageIdentified,
    WcagPauseStopHideAvailable,
    WcagPointerCancellationAbortable,
    WcagPointerCancellationReversible,
    WcagPointerCancellationUpEvent,
    // 2.5 Input Modalities
    WcagPointerGesturesSimpleAlternative,
    WcagPronunciationAvailable,
    WcagReadingLevelSupplemented,
    WcagReauthWithoutDataLoss,
    WcagReducedMotionRespected,
    WcagRedundantEntryMinimized,
    WcagRoleProgrammatic,
    WcagSectionHeadingsPresent,
    WcagSensoryNotExclusive,
    WcagSignLanguagePrerecorded,
    WcagStatusMessagesLiveRegion,
    WcagStatusMessagesProgrammatic,
    WcagTableHeadersProgrammatic,
    WcagTargetSizeEnhanced,
    WcagTargetSizeEnhancedHeight,
    WcagTargetSizeEnhancedWidth,
    WcagTargetSizeMinimum,
    WcagTargetSizeMinimumHeight,
    WcagTargetSizeMinimumSpaced,
    WcagTargetSizeMinimumWidth,
    WcagTextResizable,
    WcagTextSpacingAdjustable,
    // 2.3 Seizures and Physical Reactions
    WcagThreeFlashBelowThreshold,
    WcagTimeoutWarningProvided,
    WcagTimingAdjustTenX,
    // 2.2 Enough Time
    WcagTimingAdjustable,
    WcagTimingExtendWarning,
    WcagTimingTurnOffAvailable,
    WcagUnusualWordsDefined,
    WcagValueStatesProgrammatic,
    WcagVideoOnlyAlternativeProvided,
    WcagVisualPresentationCustomizable,
    WcagWordSpacingAdjustable,
};
