//! `elicit_gis` — Geospatial contract interface crate.
//!
//! Provides a standards-anchored vocabulary of geospatial propositions
//! ([`contracts`]), domain types ([`types`]), and object-safe async traits
//! ([`traits`]) for geospatial framework boundaries.
//!
//! # Design
//!
//! This is an **interface crate**, not an implementation. Geospatial drivers
//! (`elicit_geo`, `elicit_proj`, `elicit_geojson`) implement the traits;
//! consumers depend on this crate only.
//!
//! Traits use [`Established<P>`] contract return types instead of associated
//! types, giving object safety (`dyn GisCrsLookup`) and a common proof
//! language at call sites.
//!
//! # Standards
//!
//! - ISO 19111:2019 — Spatial referencing by coordinates
//! - OGC Simple Features Specification Part 1 (OGC 06-103r4)
//! - ISO 19115-1:2014 — Geographic metadata
//! - FGDC CSDGM — Content Standard for Digital Geospatial Metadata
//! - OGC WKT-CRS (OGC 18-010r7)
//! - RFC 7946 — GeoJSON
//!
//! [`Established<P>`]: elicitation::Established

#![forbid(unsafe_code)]
#![warn(missing_docs)]

mod contracts;
mod error;
mod traits;
mod types;

pub use contracts::{
    AngularAxisMustUseAngularUnit,
    // OGC SFS
    Area0DReturnsZero,
    Area1DReturnsZero,
    Area2DReturnsPositive,
    AreaEmptyGeometryIsZero,
    AreaNonNegative,
    AreaUnitsSquaredSrsUnits,
    AsBinaryMethodDefined,
    AsBinaryReturnsWkb,
    AsTextMethodDefined,
    AsTextReturnsWkt,
    AxisAbbreviationNonEmpty,
    AxisAbbreviationUniqueInCs,
    AxisAbbreviationUniqueWithinCs,
    AxisDirectionIsValidCode,
    AxisDirectionMemberOfCodeList,
    AxisMinMaxValueOptional,
    AxisNameNonEmpty,
    AxisOrderChangeRequiresExplicitOperation,
    AxisOrderMustFollowCrsDefinition,
    AxisRangeMeaningExactOrWraparound,
    AxisUnitAppropriateForAxisType,
    BoundaryOfBoundaryIsEmpty,
    BufferNegativeDistanceShrinks,
    BufferPositiveDistanceIncreasesArea,
    BufferResultIsValid,
    BufferReturnsContainingGeometry,
    BufferZeroContainsSelf,
    CentroidDefinedForAll,
    CentroidReturnsPoint,
    CentroidWithinConvexHull,
    CentroidXIsFinite,
    CentroidYIsFinite,
    CollectionCoordDimMatchesComponents,
    CollectionGeometryNIndexed,
    CollectionGeometryNNeverNull,
    CollectionNumGeometriesCount,
    CollectionNumGeometriesNonNegative,
    CompoundCrsComponentsNonOverlapping,
    CompoundCrsComponentsOrthogonal,
    CompoundCrsEpsgRange6000To6999,
    // §12
    CompoundCrsHasAtLeastTwoComponents,
    CompoundCrsMinimumTwoComponents,
    CompoundCrsNameNonEmpty,
    CompoundCrsNoTwoHorizontalComponents,
    CompoundCrsNoTwoVerticalComponents,
    CompoundCrsTotalAxisCountIsSumOfComponents,
    CompoundCrsTypicalIs2dPlusVertical,
    ConcatenatedOperationHasAtLeastTwoSteps,
    ConcatenatedOperationMinimumTwoSteps,
    ConcatenatedOperationSourceCrsIsFirstStep,
    ConcatenatedOperationStepsFormAChain,
    ConcatenatedOperationTargetCrsIsLastStep,
    ConformanceClass0RequiresSevenTypes,
    ConformanceClass0RequiresWkbWkt,
    ConformanceClass1AddsPredicates,
    ConformanceClass1AddsSetOps,
    ContainsDe9ImPattern,
    ContainsIsInverseOfWithin,
    ContainsIsNotSymmetric,
    ConversionDefinesMapProjection,
    ConversionHasOperationMethod,
    ConversionHasParameterValues,
    ConversionInverseExists,
    ConversionInvolvesNoDatumChange,
    ConvexHullContainsSelf,
    ConvexHullIdempotent,
    ConvexHullOfConvexPolygonIsSelf,
    ConvexHullReturnsSmallestConvex,
    Coord2DMPosition,
    Coord2DPosition,
    Coord3DMPosition,
    Coord3DPosition,
    Coord3DZIsElevation,
    CoordDimUniformInGeometry,
    CoordDimensionalityIsConsistent,
    CoordDimensionalityUniform,
    CoordMIsFiniteWhenPresent,
    CoordMIsMeasure,
    CoordXIsFinite,
    CoordYIsFinite,
    CoordZIsFiniteWhenPresent,
    CoordinateElementAlignedToAxisOrdinalPosition,
    CoordinateEpochDistinctFromFrameReferenceEpoch,
    CoordinateEpochIsDecimalYear,
    CoordinateEpochPositiveFinite,
    CoordinateMetadataApplicableAtSetOrTupleLevel,
    CoordinateMetadataCrsNonNull,
    CoordinateMetadataDynamicCrsRequiresEpoch,
    CoordinateMetadataEpochIsDecimalYear,
    // §23
    CoordinateMetadataHasCrs,
    CoordinateMetadataStaticCrsEpochShouldBeAbsent,
    CoordinateMetadataValid,
    CoordinateOperationDomainOfValidityOptional,
    CoordinateOperationHasSourceCrs,
    CoordinateOperationHasTargetCrs,
    CoordinateOperationInheritsIdentifiedObjectInterface,
    // §14
    CoordinateOperationNameNonEmpty,
    CoordinateOperationVersionOptional,
    // §8
    CoordinateSystemAxisCountOneToFour,
    CoordinateSystemMaximumFourAxes,
    // §20
    CoordinateSystemMinimumOneAxis,
    CoordinateSystemNameNonEmpty,
    CoordinateTupleDimensionMatchesAxes,
    CoordinateTupleElementCountEqualsAxisCount,
    CoordinatesTransformed,
    CoveredByIsInverseOfCovers,
    CoversDe9ImPattern,
    CoversImpliesWithin,
    CrossesDe9ImPattern,
    CrossesDimIntersectionLessThanMax,
    CrossesDimensionConstraint,
    CrossesIsNotSymmetric,
    // §6
    CrsConsistsOfCsAndDatum,
    CrsDomainOfValidityExtentTypes,
    CrsDomainOfValidityOptionalImpliesGlobal,
    CrsIdentifierAuthorityNonEmpty,
    CrsIdentifierCodeNonEmpty,
    // §18
    CrsIdentityAuthorityPlusCodeUnique,
    CrsIdentityByAuthorityAndCode,
    CrsInheritsIdentifiedObjectInterface,
    CrsMandatoryStringNonNull,
    // Operation contracts
    CrsResolved,
    CrsScopeDescribesIntendedUse,
    CrsStringValuesUtf8Encoded,
    CrsTypeMemberOfDefinedTypes,
    CrsValid,
    CsAxisCountMatchesTupleDimensionality,
    CsTypeMemberOfDefinedTypes,
    DatumEnsembleAccuracyPositive,
    // §22
    DatumEnsembleGroupsRelatedDatums,
    DatumEnsembleHasAtLeastTwoMembers,
    DatumEnsembleMemberNoNullEntries,
    DatumEnsembleMembersHomogeneous,
    DatumEnsembleNameNonEmpty,
    DatumEnsembleResolved,
    DatumEnsembleSubMetreRequiresMemberSelection,
    DatumEnsembleWgs84EpsgCode6326,
    DatumInheritsIdentifiedObjectInterface,
    De9ImCellValues,
    De9ImInteriorBoundaryExteriorAxes,
    De9ImMatrixDefined,
    De9ImRelatePatternIsNineChars,
    DerivedCrsCsDiffersFromBaseCrsAllowed,
    DerivedCrsDerivingConversionIsConversion,
    // §13
    DerivedCrsHasBaseCrs,
    DerivedCrsInheritsDatumFromBase,
    DerivedCrsNameNonEmpty,
    DerivedProjectedCrsBaseMustBeProjCrs,
    DifferenceAsymmetric,
    DifferenceDimensionAtMostSelf,
    DifferenceDisjointFromSubtracted,
    DifferenceSubsetOfSelf,
    DifferentCrsCodesRequireExplicitOperation,
    DimensionConsistencyInHierarchy,
    DisjointDe9ImPattern,
    DisjointIsInverseOfIntersects,
    DisjointIsSymmetric,
    DistanceInSrsUnits,
    DistanceNonNegative,
    DistanceSymmetric,
    DistanceTriangleInequality,
    DistanceZeroIffIntersecting,
    DynamicCrsOmittingEpochIntroducesError,
    DynamicCrsRequiresCoordinateEpoch,
    DynamicReferenceFrameHasFrameReferenceEpoch,
    EllipsoidInverseFlatteningPositiveWhenNonSphere,
    EllipsoidInverseFlatteningZeroMeansSphere,
    EllipsoidIsSphereConsistentWithParameters,
    // §7.3
    EllipsoidNameNonEmpty,
    EllipsoidSecondParameterEitherInverseFlatteningOrSemiMinor,
    EllipsoidSemiMajorAxisInMetres,
    EllipsoidSemiMajorAxisPositive,
    EllipsoidSemiMinorAxisInMetres,
    EllipsoidSemiMinorAxisLessThanSemiMajor,
    EllipsoidValid,
    EllipsoidWgs84InverseFlatteningApprox298,
    EmptyGeometryBoundaryIsEmpty,
    EmptyGeometryBoundaryIsEmptyGeometry,
    EmptyGeometryEnvelopeIsEmpty,
    EmptyHandlingConsistent,
    EngineeringCrsCsTypeFlexible,
    // §11
    EngineeringCrsDatumIsEngineeringDatum,
    EngineeringCrsIsLocalContextOnly,
    EngineeringCrsNameNonEmpty,
    EngineeringDatumAnchorOptional,
    EngineeringDatumNameNonEmpty,
    EnvelopeEmptyWhenGeometryEmpty,
    EnvelopeIsPointWhenDegenerate,
    EnvelopeIsPolygon,
    Epsg4326AxisOrderLatFirst,
    Epsg4326LatitudeRangeValid,
    Epsg4326LongitudeRangeValid,
    Epsg4326UsesDatumEnsemble,
    Epsg4978IsWgs84Geocentric,
    Epsg4978XAxisTowardsPrimeMeridian,
    Epsg4978ZAxisTowardsNorthPole,
    Epsg4979HeightUnbounded,
    Epsg4979IsWgs84Geographic3d,
    EpsgAuthorityNameIsEpsg,
    // §16
    EpsgCodePositiveInteger,
    EpsgCompoundCrsRange6000To6999,
    EpsgGeographicCrsRange4000To4999,
    EpsgProjectedCrsRange20000To32767,
    EpsgVerticalCrsRange5000To5999,
    EqualsDe9ImPattern,
    EqualsIsReflexive,
    EqualsIsSymmetric,
    EwkbBaseTypeCodeMasked,
    EwkbSridIsUint32,
    EwkbSridPresent,
    GeocentricCrsUsesCartesianCs,
    GeodeticCrsCsIsEllipsoidalOrCartesian,
    // §7
    GeodeticCrsDatumIsGeodeticReferenceFrame,
    GeodeticReferenceFrameAnchorOptional,
    GeodeticReferenceFrameHasExactlyOneEllipsoid,
    GeodeticReferenceFrameHasExactlyOnePrimeMeridian,
    // §7.2
    GeodeticReferenceFrameNameNonEmpty,
    GeodeticReferenceFrameRealizationEpochIsIso8601,
    Geographic2dCrsHasTwoAxes,
    // §15
    Geographic2dIsoAxisOrderLatitudeFirst,
    Geographic3dCrsHasThreeAxes,
    Geographic3dIsoAxisOrderLatLonHeight,
    GeometryBoundaryDefinedPerType,
    GeometryCollectionAllComponentsValid,
    GeometryCollectionBoundaryMod2Rule,
    GeometryCollectionHeterogeneousAllowed,
    GeometryCollectionIsSimpleAllSimple,
    GeometryCollectionMayBeEmpty,
    GeometryDimension0ForPoint,
    GeometryDimension1ForLine,
    GeometryDimension2ForSurface,
    GeometryDimensionMinus1WhenEmpty,
    GeometryEnvelopeReturnsMbr,
    GeometryHasSrs,
    GeometryIsEmptyPredicate,
    GeometryIsSimpleAndIsValidDistinct,
    GeometryIsSimplePredicate,
    GeometryIsValidPredicate,
    GeometrySridReturnsInteger,
    GeometrySrsNotNull,
    GeometryTypeMatchesConcreteName,
    GeometryTypeReturnsString,
    // §27
    GridBasedDatumShiftUsesExternalFile,
    HelmertConventionMustBeIdentified,
    HelmertConventionsEquivalentOnlyForZeroRotation,
    HelmertCoordinateFrameConvention,
    HelmertEpsgMethodCodes9606And9607,
    HelmertPositionVectorConvention,
    // §26
    HelmertSevenParameterStructure,
    IdentifiedObjectAliasNoNullEntries,
    IdentifiedObjectAliasOptionalList,
    IdentifiedObjectIdentifierEntryComplete,
    // §21
    IdentifiedObjectPrimaryNameNonEmpty,
    IdentifiedObjectRemarksOptional,
    IdentifiedObjectRemarksWhenPresentNonNull,
    Igs20IsDynamicDatum,
    IntersectionDimensionAtMostMin,
    IntersectionIsCommutative,
    IntersectionOfDisjointIsEmpty,
    IntersectionSubsetOfBothInputs,
    IntersectsAtLeastOneSharedPoint,
    IntersectsIsNotDisjoint,
    IntersectsIsSymmetric,
    IsEmptyFalseForNonEmpty,
    IsEmptyTrueForEmpty,
    IsSimpleNoSelfIntersection,
    IsValidImpliesSubComponentsValid,
    IsValidWellFormed,
    Itrf2014IsDynamicDatum,
    Itrf2020IsDynamicDatum,
    LatitudePolesValid,
    LatitudeRangeNegative90To90,
    Length0DReturnsZero,
    Length1DReturnsPositive,
    Length2DReturnsZero,
    LengthEmptyGeometryIsZero,
    LengthInSrsUnits,
    LengthNonNegative,
    LineStringAdjacentPointsDistinct,
    LineStringBoundaryIsEndpoints,
    LineStringClosedBoundaryEmpty,
    LineStringClosedEqualsLinearRing,
    LineStringEndPointIsPointNLast,
    LineStringHasTwoOrMorePoints,
    LineStringIsClosedStartEqualsEnd,
    LineStringIsRingImpliesClosedAndSimple,
    LineStringMinimumTwoPositions,
    LineStringNonClosedBoundaryIsEndpointMultiPoint,
    LineStringNumPointsMatchesCoordCount,
    LineStringOpenBoundaryTwoPoints,
    LineStringPointNInRange,
    LineStringSimpleNoSelfIntersection,
    LineStringStartPointIsPointNZero,
    LinearAxisMustUseLinearUnit,
    LinearRingBoundaryIsEmpty,
    LinearRingBoundaryIsEmptySet,
    LinearRingFirstPositionEqualsLast,
    LinearRingIsClosedLineString,
    LinearRingIsSimple,
    LinearRingMinimumFourPositions,
    LinearRingNonDegenerate,
    LongitudeNegative180Excluded,
    LongitudeRangeNegative180To180,
    MapProjectionFalseOriginFiniteReal,
    MapProjectionScaleFactorPositive,
    MolodenskyBadenkasTenParameter,
    MultiLineStringComponentsAreLineStrings,
    MultiLineStringIsClosedAllClosed2,
    MultiLineStringMayBeEmpty,
    MultiLineStringSimpleWhenIntersectAtEndpointsOnly,
    MultiPointComponentsArePoints,
    MultiPointMayBeEmpty,
    MultiPointSimpleWhenNoTwoEqual,
    MultiPolygonBoundariesDontOverlap,
    MultiPolygonBoundariesTouchAtPoints,
    MultiPolygonBoundaryIsAllRings,
    MultiPolygonComponentsArePolygons,
    MultiPolygonInteriorsDisjoint,
    MultiPolygonMayBeEmpty,
    Nad27EnsembleEpsg6267,
    Nadcon5IsUsHorizontalDatumShift,
    Ntv2IsGridHorizontalShift,
    NullAuthorityCodeInvalidForRegisteredCrs,
    OgcAuthorityNameIsOgc,
    OperationMethodFormulaOptional,
    OperationMethodHasParameterList,
    OperationMethodNameNonEmpty,
    OperationParameterNameNonEmpty,
    OperationParameterValueHasUnit,
    OtherAuthorityNamesEsriIgnf,
    OverlapsDe9ImPattern2D,
    OverlapsDe9ImPatternLowDim,
    OverlapsDimensionConstraint,
    OverlapsIsSymmetric,
    ParameterFileStoresFilenameNotValue,
    ParametricAxisMustUseParametricUnit,
    ParametricCrsCsIsParametricCs,
    ParametricCrsDatumIsParametricDatum,
    ParametricCrsHasOneAxis,
    PassThroughOperationCompoundCrsUsage,
    PassThroughOperationDimensionConsistency,
    PassThroughOperationIndexInRange,
    PassThroughOperationInnerOperationNonNull,
    PassThroughOperationModifiedCoordinatesNonEmpty,
    // §24
    PassThroughOperationPreservesSomeAxes,
    PointAlwaysValid,
    PointBoundaryIsEmpty,
    PointEmptyHasNoCoords,
    PointEmptyIsEmpty,
    PointMDefinedWhenMPresent,
    PointOnSurfaceDefinedForAll,
    PointOnSurfaceIsOnGeometry,
    PointOnSurfaceReturnsPoint,
    PointXIsFinite,
    PointXReturnsXOrdinate,
    PointYIsFinite,
    PointYReturnsYOrdinate,
    PointZDefinedWhen3D,
    PointZIsFiniteWhenPresent,
    PolygonBoundaryIsAllRings,
    PolygonExteriorIsCCW,
    PolygonExteriorIsLinearRing,
    PolygonExteriorRingNeverNull,
    PolygonHasExactlyOneExteriorRing,
    PolygonHoleCountNonNegative,
    PolygonHolesAreCW,
    PolygonHolesDontContainEachOther,
    PolygonHolesInsideExterior,
    PolygonInteriorRingNInRange,
    PolygonInteriorRingNReturnsHole,
    PolygonInteriorRingsAreLinearRings,
    PolygonNoRingSelfIntersects,
    PolygonNumInteriorRingsNonNegative,
    PolygonRingsDontCross,
    PolygonRingsDontTouchAlongSegment,
    PolygonRingsTouchAtPoints,
    PrimeMeridianGreenwichIsZero,
    PrimeMeridianGreenwichLongitudeFinite,
    PrimeMeridianGreenwichLongitudeInDegreeBounds,
    PrimeMeridianGreenwichLongitudeUnitIsAngular,
    // §7.4
    PrimeMeridianNameNonEmpty,
    PrimeMeridianNonGreenwichAllowed,
    ProjectedConventionalAxisOrderEastingFirst,
    ProjectedCrsAxesUseLinearUnit,
    // §9
    ProjectedCrsBaseCrsIsGeographic,
    ProjectedCrsConventionalAxisDirections,
    ProjectedCrsCsIsCartesian,
    ProjectedCrsHasTwoAxes,
    ProjectedCrsNameNonEmpty,
    ProjectedCrsProjectionIsConversion,
    ProjectedNorthingFirstVariantsExist,
    RegisteredCrsNullAuthorityCodeInvalid,
    RelatePatternCharacters,
    RelatePatternLength9,
    RelateReturnsBooleanMatchingPattern,
    ScCrsDomainOfValidityIsExtent,
    ScCrsIdentifierHasAuthorityAndCode,
    ScCrsIsAbstract,
    ScCrsNameNonEmpty,
    ScCrsScopeNonEmpty,
    SphericalCsAngularAxesThenLinear,
    SphericalCsApplicableToGeocentricContext,
    // §25
    SphericalCsHasThreeAxes,
    SridAssignedAtConstruction,
    SridIsInteger,
    SridNonNegative,
    SrsConsistentInCollection,
    StaticCrsDatumAtFixedEpoch,
    // §17
    StaticCrsPlateFixedNoEpochRequired,
    SymDifferenceEqualsUnionMinusIntersection,
    SymDifferenceIsCommutative,
    TemporalCrsCsIsTemporalCs,
    // §19
    TemporalCrsDatumIsTemporalDatum,
    TemporalCrsHasOneAxis,
    TemporalDatumOriginIsIso8601DateTime,
    TimeAxisMustUseTemporalUnit,
    TouchesDe9ImPattern,
    TouchesInteriorsDisjoint,
    TouchesIsSymmetric,
    TransformationAccuracyNonZero,
    TransformationAccuracyPositiveReal,
    TransformationInverseApproximate,
    TransformationInvolvesDatumChange,
    TransformationNad27ToWgs84UsesHelmert,
    UnionDimensionIsMax,
    UnionEqualsIntersectionPlusSymDifference,
    UnionIsAssociative,
    UnionIsCommutative,
    UnionSupersetOfBothInputs,
    UomAngularConvertToRadians,
    UomConversionFactorPositive,
    UomFeetAmbiguityInternationalVsSurvey,
    UomLinearConvertToMetres,
    // §28
    UomNameNonEmpty,
    UomScaleDimensionless,
    UomTimeConvertToSeconds,
    UtmAxisOrderEastingFirst,
    UtmCommonParametersFalseEastingAndScale,
    UtmFalseEasting500000,
    UtmNorthZoneEpsgRange32601To32660,
    UtmNorthZoneFalseNorthing0,
    UtmScaleFactorAtCentralMeridian0996,
    UtmSouthZoneEpsgRange32701To32760,
    // §29
    UtmSouthZoneFalseNorthing10000000,
    UtmZoneNumberOneToSixty,
    UtmZoneWidthSixDegrees,
    VertconIsUsVerticalDatumShift,
    VerticalCrsAxisLinearUnit,
    VerticalCrsCsIsVerticalCs,
    // §10
    VerticalCrsDatumIsVerticalReferenceFrame,
    VerticalCrsDepthAxisDirectionDown,
    VerticalCrsEpsgRange5000To5999,
    VerticalCrsHasOneAxis,
    VerticalCrsHeightAxisDirectionUp,
    VerticalCrsNameNonEmpty,
    VerticalReferenceFrameAnchorOptional,
    VerticalReferenceFrameGravityRelated,
    VerticalReferenceFrameNameNonEmpty,
    VerticalReferenceFrameRealizationEpochIsIso8601,
    WithinDe9ImPattern,
    WithinIsInverseOfContains,
    WithinIsNotSymmetric,
    WkbByteOrderBigEndian,
    WkbByteOrderLittleEndian,
    WkbByteOrderMarkerPresent,
    WkbByteOrderMarkerTwoValues,
    WkbCoordinateIsDouble,
    WkbCoordinatesByteOrderMatches,
    WkbCountFieldsAreUint32,
    WkbLengthValid,
    WkbMVariant,
    WkbPointLength21Bytes2D,
    WkbRingHasCount,
    WkbRoundTrip,
    WkbSubGeometriesAreCompleteBlobs,
    WkbTypeCodeGeometryCollection,
    WkbTypeCodeLineString,
    WkbTypeCodeMultiLineString,
    WkbTypeCodeMultiPoint,
    WkbTypeCodeMultiPolygon,
    WkbTypeCodePoint,
    WkbTypeCodePolygon,
    WkbTypeCodeValid,
    WkbZMVariant,
    WkbZVariant,
    WktCoordinateListInParens,
    WktCoordsSeparatedBySpace,
    WktDimensionTagPrecedesParens,
    WktEmptyApplicableToAllTypes,
    WktEmptyGeometry,
    WktGeometryCollectionProduction,
    WktKeywordCaseInsensitive,
    WktKeywordValid,
    WktLineStringProduction,
    WktMVariant,
    WktMultiLineStringProduction,
    WktMultiPointProduction,
    WktMultiPolygonProduction,
    WktNestingForMultiTypes,
    WktPointProduction,
    WktPolygonExteriorFirstRing,
    WktPolygonProduction,
    WktPositionsSeparatedByComma,
    WktRingsParenthesized,
    WktRingsSeparatedByComma,
    WktRoundTrip,
    WktZMVariant,
    WktZVariant,
};

pub use error::{GisError, GisErrorKind, GisResult};
pub use traits::{
    GisBackend, GisCrsLookup, GisCrsTransformer, GisCrsValidator, SfsGeometry, SfsSetOps,
    SfsTopology,
};
pub use types::{
    AuthorityCode, AxisDirection, CoordinateMetadata, CrsInfo, CrsType, CsType, DatumEnsembleInfo,
    DecimalYear, EllipsoidParams, EpsgCode, HelmertConvention,
};
