//! `elicit_gis` — Geospatial contract interface crate.
//!
//! Provides a standards-anchored vocabulary of geospatial propositions
//! ([`contracts`]), domain types ([`types`]), and object-safe async traits
//! ([`traits`]) for geospatial framework boundaries.
//!
//! # Design
//!
//! This is an **interface crate**, not an implementation. Geospatial drivers
//! (`elicit_geo`, `elicit_proj`, `elicit_geojson`) implement the traits;
//! consumers depend on this crate only.
//!
//! Traits use [`Established<P>`] contract return types instead of associated
//! types, giving object safety (`dyn GisCrsLookup`) and a common proof
//! language at call sites.
//!
//! # Standards
//!
//! - ISO 19111:2019 — Spatial referencing by coordinates
//! - OGC Simple Features Specification Part 1 (OGC 06-103r4)
//! - ISO 19115-1:2014 — Geographic metadata
//! - FGDC CSDGM — Content Standard for Digital Geospatial Metadata
//! - OGC WKT-CRS (OGC 18-010r7)
//! - RFC 7946 — GeoJSON
//!
//! [`Established<P>`]: elicitation::Established

#![forbid(unsafe_code)]
#![warn(missing_docs)]

mod contracts;
mod error;
mod traits;
mod types;

pub use contracts::{
    AllPositionsInGeometryHaveConsistentDimension, AngularAxisMustUseAngularUnit,
    AntimeridianCrossingGeometriesShouldBeSplit, AntimeridianCutPreservesTopology,
    AntimeridianLineStringSplitsToMultiLineString, AntimeridianNoLongitudeOutsideRange,
    AntimeridianPolygonSplitsToMultiPolygon, AntimeridianSplitPartDoesNotCrossLine,
    Area0DReturnsZero, Area1DReturnsZero, Area2DReturnsPositive, AreaEmptyGeometryIsZero,
    AreaIsFinite, AreaNonNegative, AreaUnitsSquaredSrsUnits, AsBinaryMethodDefined,
    AsBinaryReturnsWkb, AsTextMethodDefined, AsTextReturnsWkt, AxisAbbreviationNonEmpty,
    AxisAbbreviationUniqueInCs, AxisAbbreviationUniqueWithinCs, AxisDirectionIsValidCode,
    AxisDirectionMemberOfCodeList, AxisMinMaxValueOptional, AxisNameNonEmpty,
    AxisOrderChangeRequiresExplicitOperation, AxisOrderMustFollowCrsDefinition,
    AxisRangeMeaningExactOrWraparound, AxisUnitAppropriateForAxisType,
    Bbox2dHasExactlyFourElements, Bbox2dOrderIsMinLonMinLatMaxLonMaxLat,
    Bbox3dHasExactlySixElements, Bbox3dOrderIsMinLonMinLatMinAltMaxLonMaxLatMaxAlt,
    BboxAllElementsAreJsonNumbers, BboxAntimeridianWestValueMayExceedEast,
    BboxDimensionMatchesGeometryDimension, BboxEdgesFollowConstantCoordinateLines,
    BboxElementsAreFinite, BboxLatitudeMustNotBelowNeg90, BboxLatitudeMustNotExceed90,
    BboxLengthIsTwiceN, BboxMemberIsOptional, BboxMinAltLeMaxAlt, BboxMinLatLeMaxLat,
    BboxMustNotUseOutOfRangeLatForSphericalCap, BboxShouldContainAllGeometryPositions,
    BboxSouthwestCornerPrecedesNortheast, BboxWhenPresentIsJsonArray, BoundaryOfBoundaryIsEmpty,
    BufferNegativeDistanceShrinks, BufferPositiveDistanceIncreasesArea, BufferResultIsValid,
    BufferReturnsContainingGeometry, BufferZeroContainsSelf, CentroidDefinedForAll,
    CentroidReturnsPoint, CentroidWithinConvexHull, CentroidXIsFinite, CentroidYIsFinite,
    CiAddressAdministrativeAreaOptional, CiAddressCityOptional, CiAddressCountryIsIso3166,
    CiAddressCountryOptional, CiAddressDeliveryPointOptional, CiAddressEmailOptional,
    CiAddressPostalCodeOptional, CiCitationAlternateTitleOptional,
    CiCitationCollectiveTitleOptional, CiCitationDateMandatory, CiCitationEditionDateOptional,
    CiCitationEditionOptional, CiCitationIdentifierOptional, CiCitationIsbnFormatValid,
    CiCitationIssnFormatValid, CiCitationOtherDetailsOptional, CiCitationPresentationFormOptional,
    CiCitationResponsiblePartyOptional, CiCitationSeriesOptional, CiCitationTitleMandatory,
    CiCitationTitleNonEmpty, CiCitationValid, CiContactAddressOptional,
    CiContactHoursOfServiceOptional, CiContactInstructionsOptional,
    CiContactOnlineResourceOptional, CiContactPhoneOptional, CiDateTypeAdopted,
    CiDateTypeCodeMandatory, CiDateTypeCreation, CiDateTypeDeprecated, CiDateTypeDistribution,
    CiDateTypeExpiry, CiDateTypeInForce, CiDateTypeLastRevision, CiDateTypeLastUpdate,
    CiDateTypeNextUpdate, CiDateTypePublication, CiDateTypeReleased, CiDateTypeRevision,
    CiDateTypeSuperseded, CiDateTypeUnavailable, CiDateTypeValidityBegins,
    CiDateTypeValidityExpires, CiDateValueMandatory, CiIndividualContactInfoOptional,
    CiIndividualNameOptional, CiIndividualNameOrPositionRequired, CiIndividualPositionNameOptional,
    CiOnlineFunctionBrowseGraphic, CiOnlineFunctionBrowsing, CiOnlineFunctionCompleteMetadata,
    CiOnlineFunctionDownload, CiOnlineFunctionEmailService, CiOnlineFunctionFileAccess,
    CiOnlineFunctionInformation, CiOnlineFunctionOfflineAccess, CiOnlineFunctionOrder,
    CiOnlineFunctionSearch, CiOnlineFunctionUpload, CiOnlineResourceApplicationProfileOptional,
    CiOnlineResourceDescriptionOptional, CiOnlineResourceFunctionOptional,
    CiOnlineResourceLinkageMandatory, CiOnlineResourceLinkageValidUrl,
    CiOnlineResourceNameOptional, CiOnlineResourceProtocolOptional,
    CiOrganisationContactInfoOptional, CiOrganisationIndividualOptional,
    CiOrganisationNameOptional, CiPartyIsAbstract, CiResponsibilityExtentOptional,
    CiResponsibilityPartyMandatory, CiResponsibilityPartyNameNonNull,
    CiResponsibilityRoleMandatory, CiResponsibilityValid, CiRoleAuthor, CiRoleCoAuthor,
    CiRoleCollaborator, CiRoleContributor, CiRoleCustodian, CiRoleDistributor, CiRoleEditor,
    CiRoleFunder, CiRoleMediator, CiRoleOriginator, CiRoleOwner, CiRolePointOfContact,
    CiRolePrincipalInvestigator, CiRoleProcessor, CiRolePublisher, CiRoleResourceProvider,
    CiRoleRightsHolder, CiRoleSponsor, CiRoleStakeholder, CiRoleUser, CiTelephoneFacsimile,
    CiTelephoneNumberMandatory, CiTelephoneNumberNonEmpty, CiTelephoneSms, CiTelephoneTypeVoice,
    CollectionCoordDimMatchesComponents, CollectionGeometryNIndexed, CollectionGeometryNNeverNull,
    CollectionNumGeometriesCount, CollectionNumGeometriesNonNegative,
    CompoundCrsComponentsNonOverlapping, CompoundCrsComponentsOrthogonal,
    CompoundCrsEpsgRange6000To6999, CompoundCrsHasAtLeastTwoComponents,
    CompoundCrsMinimumTwoComponents, CompoundCrsNameNonEmpty, CompoundCrsNoTwoHorizontalComponents,
    CompoundCrsNoTwoVerticalComponents, CompoundCrsTotalAxisCountIsSumOfComponents,
    CompoundCrsTypicalIs2dPlusVertical, ConcatenatedOperationHasAtLeastTwoSteps,
    ConcatenatedOperationMinimumTwoSteps, ConcatenatedOperationSourceCrsIsFirstStep,
    ConcatenatedOperationStepsFormAChain, ConcatenatedOperationTargetCrsIsLastStep,
    ConformanceClass0RequiresSevenTypes, ConformanceClass0RequiresWkbWkt,
    ConformanceClass1AddsPredicates, ConformanceClass1AddsSetOps, ContainsDe9ImPattern,
    ContainsIsInverseOfWithin, ContainsIsNotSymmetric, ConversionDefinesMapProjection,
    ConversionHasOperationMethod, ConversionHasParameterValues, ConversionInverseExists,
    ConversionInvolvesNoDatumChange, ConvexHullContainsSelf, ConvexHullIdempotent,
    ConvexHullOfConvexPolygonIsSelf, ConvexHullReturnsSmallestConvex, Coord2DMPosition,
    Coord2DPosition, Coord3DMPosition, Coord3DPosition, Coord3DZIsElevation,
    CoordDimUniformInGeometry, CoordDimensionalityIsConsistent, CoordDimensionalityUniform,
    CoordMIsFiniteWhenPresent, CoordMIsMeasure, CoordPrecisionMustNotImplyAccuracyLevel,
    CoordPrecisionNotInDmsFormat, CoordPrecisionNotInSexagesimalFormat,
    CoordPrecisionSixDecimalPlacesIsSufficient, CoordXIsFinite, CoordYIsFinite,
    CoordZIsFiniteWhenPresent, CoordinateElementAlignedToAxisOrdinalPosition,
    CoordinateEpochDistinctFromFrameReferenceEpoch, CoordinateEpochIsDecimalYear,
    CoordinateEpochPositiveFinite, CoordinateMetadataApplicableAtSetOrTupleLevel,
    CoordinateMetadataCrsNonNull, CoordinateMetadataDynamicCrsRequiresEpoch,
    CoordinateMetadataEpochIsDecimalYear, CoordinateMetadataHasCrs,
    CoordinateMetadataStaticCrsEpochShouldBeAbsent, CoordinateMetadataValid,
    CoordinateOperationDomainOfValidityOptional, CoordinateOperationHasSourceCrs,
    CoordinateOperationHasTargetCrs, CoordinateOperationInheritsIdentifiedObjectInterface,
    CoordinateOperationNameNonEmpty, CoordinateOperationVersionOptional,
    CoordinatePrecisionMustNotImplyUncertainty, CoordinateSystemAxisCountOneToFour,
    CoordinateSystemMaximumFourAxes, CoordinateSystemMinimumOneAxis, CoordinateSystemNameNonEmpty,
    CoordinateSystemValid, CoordinateTupleDimensionMatchesAxes,
    CoordinateTupleElementCountEqualsAxisCount, CoordinatesAreInDecimalDegreesOnly,
    CoordinatesTransformed, CoveredByIsInverseOfCovers, CoversDe9ImPattern, CoversImpliesWithin,
    CrossesDe9ImPattern, CrossesDimIntersectionLessThanMax, CrossesDimensionConstraint,
    CrossesIsNotSymmetric, CrsAbsentAltitudeTreatedAsSurface,
    CrsAlternativeForbiddenWithoutArrangement, CrsAltitudeIsAboveWgs84Ellipsoid,
    CrsAxisOrderLatitudeSecond, CrsAxisOrderLongitudeFirst, CrsComponentGraphAcyclic,
    CrsConsistsOfCsAndDatum, CrsDomainOfValidityExtentTypes,
    CrsDomainOfValidityOptionalImpliesGlobal, CrsEquivalentToOgcUrn,
    CrsIdentifierAuthorityNonEmpty, CrsIdentifierCodeNonEmpty, CrsIdentityAuthorityPlusCodeUnique,
    CrsIdentityByAuthorityAndCode, CrsInheritsIdentifiedObjectInterface, CrsMandatoryStringNonNull,
    CrsMemberMustNotAppearInDocument, CrsNoEpsgCodesPermitted, CrsNoNamedCrsObjectPermitted,
    CrsOnlyWgs84IsPermitted, CrsResolved, CrsScopeDescribesIntendedUse, CrsStringValuesUtf8Encoded,
    CrsTypeMemberOfDefinedTypes, CrsValid, CsAxisCountMatchesTupleDimensionality,
    CsTypeMemberOfDefinedTypes, DatumEnsembleAccuracyFinite, DatumEnsembleAccuracyPositive,
    DatumEnsembleGroupsRelatedDatums, DatumEnsembleHasAtLeastTwoMembers,
    DatumEnsembleMemberNoNullEntries, DatumEnsembleMembersHomogeneous, DatumEnsembleNameNonEmpty,
    DatumEnsembleResolved, DatumEnsembleSubMetreRequiresMemberSelection,
    DatumEnsembleWgs84EpsgCode6326, DatumInheritsIdentifiedObjectInterface, De9ImCellValues,
    De9ImInteriorBoundaryExteriorAxes, De9ImMatrixDefined, De9ImRelatePatternIsNineChars,
    DerivedCrsCsDiffersFromBaseCrsAllowed, DerivedCrsDerivingConversionIsConversion,
    DerivedCrsHasBaseCrs, DerivedCrsInheritsDatumFromBase, DerivedCrsNameNonEmpty,
    DerivedProjectedCrsBaseMustBeProjCrs, DifferenceAsymmetric, DifferenceDimensionAtMostSelf,
    DifferenceDisjointFromSubtracted, DifferenceSubsetOfSelf,
    DifferentCrsCodesRequireExplicitOperation, DigitCountIsNotDataAccuracyIndicator,
    DimensionConsistencyInHierarchy, DisjointDe9ImPattern, DisjointIsInverseOfIntersects,
    DisjointIsSymmetric, DistanceInSrsUnits, DistanceIsFinite, DistanceNonNegative,
    DistanceSymmetric, DistanceTriangleInequality, DistanceZeroIffIntersecting,
    DqAbsoluteExternalPositionalAccuracy, DqCompletenessCommission, DqCompletenessOmission,
    DqConceptualConsistency, DqConformanceResultPassMandatory,
    DqConformanceResultSpecificationMandatory, DqDataQualityReportOptional,
    DqDataQualityScopeMandatory, DqDataQualityStandaloneOptional, DqDomainConsistency,
    DqElementResultMandatory, DqFormatConsistency, DqGriddedDataPositionalAccuracy,
    DqNonQuantitativeAttributeCorrectness, DqQuantitativeAttributeAccuracy,
    DqQuantitativeResultValueNonEmpty, DqQuantitativeResultValueUnitMandatory,
    DqRelativeInternalPositionalAccuracy, DqTemporalConsistency, DqTemporalValidity,
    DqThematicClassificationCorrectness, DqTopologicalConsistency, DsAssociationTypeCrossReference,
    DsAssociationTypeIsComposedOf, DsAssociationTypeLargerWorkCitation,
    DsAssociationTypePartOfSeamlessDatabase, DsAssociationTypeRevisionOf, DsInitiativeTypeMission,
    DsInitiativeTypePlatform, DsInitiativeTypeProject, DynamicCrsOmittingEpochIntroducesError,
    DynamicCrsRequiresCoordinateEpoch, DynamicReferenceFrameHasFrameReferenceEpoch,
    DynamicReferenceFrameVelocityModelReferenced, EllipsoidInverseFlatteningPositiveWhenNonSphere,
    EllipsoidInverseFlatteningZeroMeansSphere, EllipsoidIsSphereConsistentWithParameters,
    EllipsoidNameNonEmpty, EllipsoidSecondParameterEitherInverseFlatteningOrSemiMinor,
    EllipsoidSemiMajorAxisFinite, EllipsoidSemiMajorAxisInMetres, EllipsoidSemiMajorAxisPositive,
    EllipsoidSemiMinorAxisFinite, EllipsoidSemiMinorAxisInMetres,
    EllipsoidSemiMinorAxisLessThanSemiMajor, EllipsoidValid,
    EllipsoidWgs84InverseFlatteningApprox298, EmptyGeometryBoundaryIsEmpty,
    EmptyGeometryBoundaryIsEmptyGeometry, EmptyGeometryEnvelopeIsEmpty, EmptyHandlingConsistent,
    EngineeringCrsCsTypeFlexible, EngineeringCrsDatumIsEngineeringDatum,
    EngineeringCrsIsLocalContextOnly, EngineeringCrsNameNonEmpty, EngineeringDatumAnchorOptional,
    EngineeringDatumNameNonEmpty, EnvelopeEmptyWhenGeometryEmpty, EnvelopeIsPointWhenDegenerate,
    EnvelopeIsPolygon, Epsg4326AxisOrderLatFirst, Epsg4326LatitudeRangeValid,
    Epsg4326LongitudeRangeValid, Epsg4326UsesDatumEnsemble, Epsg4978IsWgs84Geocentric,
    Epsg4978XAxisTowardsPrimeMeridian, Epsg4978ZAxisTowardsNorthPole, Epsg4979HeightUnbounded,
    Epsg4979IsWgs84Geographic3d, EpsgAuthorityNameIsEpsg, EpsgCodePositiveInteger,
    EpsgCompoundCrsRange6000To6999, EpsgGeographicCrsRange4000To4999,
    EpsgProjectedCrsRange20000To32767, EpsgVerticalCrsRange5000To5999, EqualsDe9ImPattern,
    EqualsIsReflexive, EqualsIsSymmetric, EwkbBaseTypeCodeMasked, EwkbSridIsUint32,
    EwkbSridPresent, ExBboxEastBoundIsFinite, ExBboxEastBoundMandatory,
    ExBboxExtentTypeCodeOptional, ExBboxLatitudeRange, ExBboxLongitudeRange,
    ExBboxNorthBoundIsFinite, ExBboxNorthBoundMandatory, ExBboxSouthBoundIsFinite,
    ExBboxSouthBoundMandatory, ExBboxSouthLeNorth, ExBboxWestBoundIsFinite,
    ExBboxWestBoundMandatory, ExBboxWestLeEastOrAntimeridian, ExBoundingPolygonAtLeastOneGeometry,
    ExBoundingPolygonExtentTypeCodeOptional, ExBoundingPolygonGeometryIsValid,
    ExBoundingPolygonPolygonMandatory, ExExtentAtLeastOneElementRequired,
    ExExtentDescriptionOptional, ExExtentGeographicElementConditional,
    ExExtentTemporalElementOptional, ExExtentValid, ExExtentVerticalElementOptional,
    ExGeographicBoundingBoxValid, ExTemporalExtentExtentMandatory,
    ExTemporalExtentPeriodBeginLeEnd, ExVerticalExtentCrsOptional, ExVerticalExtentMaxIsFinite,
    ExVerticalExtentMaximumMandatory, ExVerticalExtentMinIsFinite, ExVerticalExtentMinLeMax,
    ExVerticalExtentMinimumMandatory, ExistingGeometrySemanticsMustNotChange,
    FeatureCollectionConsistentCoordinateDimension, FeatureCollectionEachElementIsFeatureObject,
    FeatureCollectionEachElementIsNotNull, FeatureCollectionFeaturesIsJsonArray,
    FeatureCollectionFeaturesIsNotNull, FeatureCollectionFeaturesIsNotSingleFeature,
    FeatureCollectionHasFeaturesMember, FeatureCollectionIdIsNotRequired,
    FeatureCollectionMayBeEmpty, FeatureCollectionSemanticsMustNotChange,
    FeatureCollectionTypeEqualsFeatureCollection, FeatureCollectionValid,
    FeatureGeometryIsGeometryObjectOrNull, FeatureGeometryWhenPresentIsValidGeometry,
    FeatureHasGeometryMember, FeatureHasPropertiesMember, FeatureIdMemberIsOptional,
    FeatureIdMustNotBeArray, FeatureIdMustNotBeBoolean, FeatureIdMustNotBeNull,
    FeatureIdMustNotBeObject, FeatureIdNumberIsAllowed, FeatureIdStringIsAllowed,
    FeatureIdUniquenessWithinCollectionRecommended, FeatureIdWhenPresentIsStringOrNumber,
    FeatureNullGeometryMeansUnlocated, FeaturePropertiesIsJsonObjectOrNull,
    FeatureSemanticsMustNotChange, FeatureTypeEqualsFeature, FeatureValid, FileExtensionIsGeojson,
    ForeignMembersAtAnyLevelShouldBeIgnored, ForeignMembersCannotOverrideTypeMember,
    ForeignMembersDoNotAlterSemantics, FullRfc7946Compliance, GeoJsonBboxMemberIsOptional,
    GeoJsonBboxWhenPresentIsArray, GeoJsonDocumentValid, GeoJsonForeignMembersShouldBeIgnored,
    GeoJsonGeometryCollectionMayBeEmpty, GeoJsonGeometryCollectionValid, GeoJsonGeometryValid,
    GeoJsonLineStringValid, GeoJsonMultiLineStringMayBeEmpty, GeoJsonMultiLineStringValid,
    GeoJsonMultiPointValid, GeoJsonMultiPolygonMayBeEmpty, GeoJsonMultiPolygonValid,
    GeoJsonObjectHasTypeMember, GeoJsonObjectMustNotUseNullType,
    GeoJsonObjectTypeMemberNeverMissing, GeoJsonPointMappableToGeoUri, GeoJsonPointValid,
    GeoJsonPolygonValid, GeoJsonRootIsObject, GeoJsonTextIsSingleJsonValue,
    GeoJsonTypeIsCaseSensitive, GeoJsonTypeIsNotExtensible, GeoJsonTypeIsOneOfNineValues,
    GeoJsonTypeMemberIsNotNull, GeoJsonTypeMemberIsString, GeoUriMappableToGeoJsonPoint,
    GeocentricCrsUsesCartesianCs, GeodeticCrsCsIsEllipsoidalOrCartesian,
    GeodeticCrsDatumIsGeodeticReferenceFrame, GeodeticReferenceFrameAnchorOptional,
    GeodeticReferenceFrameHasExactlyOneEllipsoid, GeodeticReferenceFrameHasExactlyOnePrimeMeridian,
    GeodeticReferenceFrameNameNonEmpty, GeodeticReferenceFrameRealizationEpochIsIso8601,
    GeodeticReferenceFrameValid, Geographic2dCrsHasTwoAxes, Geographic2dIsoAxisOrderLatitudeFirst,
    Geographic3dCrsHasThreeAxes, Geographic3dIsoAxisOrderLatLonHeight,
    GeometryBoundaryDefinedPerType, GeometryCollectionAllComponentsValid,
    GeometryCollectionBoundaryMod2Rule, GeometryCollectionEachElementIsValidGeometry,
    GeometryCollectionEachGeometryHasTypeMember, GeometryCollectionGeometriesIsJsonArray,
    GeometryCollectionGeometriesIsNotNull, GeometryCollectionHasGeometriesMember,
    GeometryCollectionHeterogeneousAllowed, GeometryCollectionIsSimpleAllSimple,
    GeometryCollectionMayBeEmpty, GeometryCollectionMustNotHaveCoordinatesMember,
    GeometryCollectionShouldNotBeNested, GeometryCollectionShouldNotReplaceMultiXType,
    GeometryCollectionTypeEqualsGeometryCollection, GeometryCollectionValid,
    GeometryDimension0ForPoint, GeometryDimension1ForLine, GeometryDimension2ForSurface,
    GeometryDimensionMinus1WhenEmpty, GeometryEnvelopeReturnsMbr, GeometryHasSrs,
    GeometryIsEmptyPredicate, GeometryIsSimpleAndIsValidDistinct, GeometryIsSimplePredicate,
    GeometryIsValidPredicate, GeometrySridReturnsInteger, GeometrySrsNotNull,
    GeometryTypeMatchesConcreteName, GeometryTypeReturnsString,
    GeometryTypeValueMatchesCoordinateStructure, GridBasedDatumShiftUsesExternalFile,
    HelmertConventionMustBeIdentified, HelmertConventionsEquivalentOnlyForZeroRotation,
    HelmertCoordinateFrameConvention, HelmertEpsgMethodCodes9606And9607,
    HelmertPositionVectorConvention, HelmertSevenParameterStructure, IJsonNoBomShouldBeAdded,
    IJsonNoDuplicateKeysAllowed, IJsonNoInfinityValues, IJsonNoNaNValues,
    IJsonNoUnescapedControlCharacters, IJsonNumbersMustBeIeee754Representable,
    IJsonStringsAreUnicode, IJsonUtf8EncodingRequired, IdentifiedObjectAliasNoDuplicates,
    IdentifiedObjectAliasNoNullEntries, IdentifiedObjectAliasOptionalList,
    IdentifiedObjectIdentifierEntryComplete, IdentifiedObjectPrimaryNameNonEmpty,
    IdentifiedObjectRemarksOptional, IdentifiedObjectRemarksWhenPresentNonNull,
    Igs20IsDynamicDatum, IntersectionDimensionAtMostMin, IntersectionIsCommutative,
    IntersectionOfDisjointIsEmpty, IntersectionSubsetOfBothInputs, IntersectsAtLeastOneSharedPoint,
    IntersectsIsNotDisjoint, IntersectsIsSymmetric, IsEmptyFalseForNonEmpty, IsEmptyTrueForEmpty,
    IsSimpleNoSelfIntersection, IsValidImpliesSubComponentsValid, IsValidWellFormed,
    Iso19115AllMandatoryElementsPresent, Iso19115CitationTitleNeverEmpty,
    Iso19115ConditionalElementsTriggered, Iso19115ContactPartyNameNonNull,
    Iso19115CountryCodeIso3166, Iso19115DateIso8601Format, Iso19115EnumerationValuesValid,
    Iso19115LanguageCodeIso6392, Iso19115MultiplicityConstraintsMet,
    Iso19115ProcessStepDescriptionNeverEmpty, Itrf2014IsDynamicDatum, Itrf2020IsDynamicDatum,
    LatitudePolesValid, LatitudeRangeNegative90To90, Length0DReturnsZero, Length1DReturnsPositive,
    Length2DReturnsZero, LengthEmptyGeometryIsZero, LengthInSrsUnits, LengthIsFinite,
    LengthNonNegative, LiLineageAdditionalDocumentationOptional, LiLineageAtLeastOneProvided,
    LiLineageProcessStepOptional, LiLineageScopeOptional, LiLineageSourceOptional,
    LiLineageStatementConditional, LiLineageValid, LiProcessStepDateTimeOptional,
    LiProcessStepDescriptionMandatory, LiProcessStepDescriptionNonEmpty,
    LiProcessStepProcessorOptional, LiProcessStepRationaleOptional, LiProcessStepReferenceOptional,
    LiProcessStepScopeOptional, LiProcessStepSourceOptional, LiSourceCitationOptional,
    LiSourceDescriptionConditional, LiSourceDescriptionOrCitationRequired,
    LiSourceReferenceSystemOptional, LiSourceSpatialResolutionOptional, LiSourceStepOptional,
    LineStringAdjacentPointsDistinct, LineStringBoundaryIsEndpoints, LineStringClosedBoundaryEmpty,
    LineStringClosedEqualsLinearRing, LineStringCoordinatesHasMinTwoPositions,
    LineStringCoordinatesIsArray, LineStringCoordinatesIsNotEmpty, LineStringCoordinatesIsNotNull,
    LineStringEachElementIsValidPosition, LineStringEndPointIsPointNLast,
    LineStringHasCoordinatesMember, LineStringHasTwoOrMorePoints, LineStringIsClosedStartEqualsEnd,
    LineStringIsRingImpliesClosedAndSimple, LineStringMinTwoPositionsFormPath,
    LineStringMinimumTwoPositions, LineStringNonClosedBoundaryIsEndpointMultiPoint,
    LineStringNumPointsMatchesCoordCount, LineStringOpenBoundaryTwoPoints, LineStringPointNInRange,
    LineStringSimpleNoSelfIntersection, LineStringStartPointIsPointNZero,
    LineStringTypeEqualsLineString, LineStringValid, LinearAxisMustUseLinearUnit,
    LinearRingBoundaryIsEmpty, LinearRingBoundaryIsEmptySet, LinearRingFirstPositionEqualsLast,
    LinearRingIsClosedLineString, LinearRingIsSimple, LinearRingMinimumFourPositions,
    LinearRingNonDegenerate, LinearRingValid, LongitudeNegative180Excluded,
    LongitudeRangeNegative180To180, MapProjectionFalseOriginFiniteReal,
    MapProjectionScaleFactorFinite, MapProjectionScaleFactorPositive,
    MdAssociatedResourceAssociationTypeMandatory, MdAssociatedResourceInitiativeTypeOptional,
    MdAssociatedResourceMetadataRefConditional, MdAssociatedResourceNameConditional,
    MdAssociatedResourceNameOrMetaRefRequired, MdBrowseGraphicFileDescriptionOptional,
    MdBrowseGraphicFileNameMandatory, MdBrowseGraphicFileNameNonEmpty,
    MdBrowseGraphicFileTypeOptional, MdBrowseGraphicLinkageOptional, MdCharsetArabic,
    MdCharsetBig5, MdCharsetCyrillic, MdCharsetEucJp, MdCharsetGb2312, MdCharsetGreek,
    MdCharsetHebrew, MdCharsetLatin1, MdCharsetLatin2, MdCharsetLatin5, MdCharsetShiftJis,
    MdCharsetUcs2, MdCharsetUcs4, MdCharsetUsAscii, MdCharsetUtf8, MdCharsetUtf16, MdCharsetUtf32,
    MdClassificationConfidential, MdClassificationForOfficialUseOnly,
    MdClassificationLimitedDistribution, MdClassificationProtected, MdClassificationRestricted,
    MdClassificationSecret, MdClassificationSensitiveButUnclassified, MdClassificationTopSecret,
    MdClassificationUnclassified, MdConstraintsApplicationScopeOptional,
    MdConstraintsUseLimitationOptional, MdDataIdentificationCharacterSetConditional,
    MdDataIdentificationExtentConditional, MdDataIdentificationLanguageConditional,
    MdDataIdentificationSpatialResolutionOptional, MdDataIdentificationSupplementalInfoOptional,
    MdDataIdentificationTopicCategoryConditional, MdDimensionNameColumn, MdDimensionNameMandatory,
    MdDimensionNameRow, MdDimensionNameTime, MdDimensionNameVertical,
    MdDimensionResolutionOptional, MdDimensionSizeMandatory, MdDimensionSizePositive,
    MdDistributionAtLeastOneElement, MdDistributionDistributorOptional,
    MdDistributionFormatOptional, MdDistributionTransferOptionsOptional,
    MdDistributorContactMandatory, MdDistributorFormatOptional, MdDistributorOrderProcessOptional,
    MdDistributorTransferOptionsOptional, MdFormatAmendmentNumberOptional,
    MdFormatDistributorOptional, MdFormatFileDecompressionOptional, MdFormatMediumOptional,
    MdFormatSpecificationCitationMandatory, MdGridSpatialRepAxisDimensionProperties,
    MdGridSpatialRepCellGeometry, MdGridSpatialRepNumberOfDimensions,
    MdGridSpatialRepNumberOfDimensionsPositive, MdGridSpatialRepTransformationAvailable,
    MdIdentificationAbstractMandatory, MdIdentificationAbstractNonEmpty,
    MdIdentificationCitationMandatory, MdIdentificationCreditOptional,
    MdIdentificationDescriptiveKeywordsOptional, MdIdentificationGraphicOverviewOptional,
    MdIdentificationPointOfContactOptional, MdIdentificationPurposeOptional,
    MdIdentificationResourceConstraintsOptional, MdIdentificationResourceFormatOptional,
    MdIdentificationResourceMaintenanceOptional, MdIdentificationStatusOptional,
    MdIdentificationValid, MdKeywordTypeDataCentre, MdKeywordTypeDiscipline,
    MdKeywordTypeFeatureType, MdKeywordTypeInstrument, MdKeywordTypePlace, MdKeywordTypePlatform,
    MdKeywordTypeProcess, MdKeywordTypeProduct, MdKeywordTypeProject, MdKeywordTypeService,
    MdKeywordTypeStratum, MdKeywordTypeSubTopicCategory, MdKeywordTypeTaxon, MdKeywordTypeTemporal,
    MdKeywordTypeTheme, MdKeywordsKeywordClassOptional, MdKeywordsKeywordMandatory,
    MdKeywordsThesaurusNameOptional, MdKeywordsTypeOptional,
    MdLegalConstraintsAccessConstraintsOptional, MdLegalConstraintsOtherConstraintsConditional,
    MdLegalConstraintsUseConstraintsOptional, MdMaintenanceContactOptional,
    MdMaintenanceDateOptional, MdMaintenanceFrequencyAnnually, MdMaintenanceFrequencyAsNeeded,
    MdMaintenanceFrequencyContinual, MdMaintenanceFrequencyDaily, MdMaintenanceFrequencyIrregular,
    MdMaintenanceFrequencyMandatory, MdMaintenanceFrequencyMonthly,
    MdMaintenanceFrequencyNotPlanned, MdMaintenanceFrequencyQuarterly,
    MdMaintenanceFrequencyUnknown, MdMaintenanceFrequencyWeekly, MdMaintenanceNoteOptional,
    MdMaintenanceScopeOptional, MdMaintenanceUserDefinedFreqConditional,
    MdMediumDensityUnitsConditional, MdMediumVolumesOptional, MdMetadataCharacterSetConditional,
    MdMetadataConstraintsOptional, MdMetadataContactMandatory, MdMetadataContactPartyNameNonNull,
    MdMetadataDataQualityInfoOptional, MdMetadataDateInfoMandatory,
    MdMetadataDistributionInfoOptional, MdMetadataFileIdentifierOptional,
    MdMetadataHierarchyLevelNameMatchesLevel, MdMetadataHierarchyLevelScopeCode,
    MdMetadataIdentificationInfoMandatory, MdMetadataLanguageConditional, MdMetadataLocaleOptional,
    MdMetadataMaintenanceOptional, MdMetadataParentIdentifierOptional,
    MdMetadataReferenceSystemInfoOptional, MdMetadataResourceLineageOptional,
    MdMetadataSpatialRepresentationInfoOptional, MdMetadataStandardNameOptional,
    MdMetadataStandardVersionOptional, MdMetadataValid, MdProgressCodeAccepted,
    MdProgressCodeCompleted, MdProgressCodeDeprecated, MdProgressCodeFinal,
    MdProgressCodeHistoricalArchive, MdProgressCodeNotAccepted, MdProgressCodeObsolete,
    MdProgressCodeOnGoing, MdProgressCodePending, MdProgressCodePlanned, MdProgressCodeProposed,
    MdProgressCodeRequired, MdProgressCodeRetired, MdProgressCodeSuperseded,
    MdProgressCodeTentative, MdProgressCodeUnderDevelopment, MdProgressCodeValid,
    MdProgressCodeWithdrawn, MdReferenceSystemIdentifierOptional, MdReferenceSystemTypeOptional,
    MdRepresentativeFractionDenominatorMandatory, MdRepresentativeFractionDenominatorPositive,
    MdResolutionDistanceIsFinite, MdResolutionDistanceIsPositive,
    MdResolutionEquivalentScaleOrDistance, MdResolutionScaleImpliesSmallIsCoarse,
    MdRestrictionConfidentialCode, MdRestrictionCopyrightCode, MdRestrictionInConfidenceCode,
    MdRestrictionIntellectualPropertyCode, MdRestrictionLicenceCode,
    MdRestrictionLicenceDistributorCode, MdRestrictionLicenceEndUserCode,
    MdRestrictionLicenceUnrestrictedCode, MdRestrictionOtherRestrictionsCode,
    MdRestrictionPatentCode, MdRestrictionPatentPendingCode, MdRestrictionPrivateCode,
    MdRestrictionRestrictedCode, MdRestrictionSbuCode, MdRestrictionStatutoryCode,
    MdRestrictionTrademarkCode, MdRestrictionUnrestrictedCode, MdScopeAttribute,
    MdScopeAttributeType, MdScopeCollectionSession, MdScopeDataset, MdScopeDimensionGroup,
    MdScopeFeature, MdScopeFeatureType, MdScopeFieldSession, MdScopeInitiative, MdScopeModel,
    MdScopeNonGeographicDataset, MdScopeSeries, MdScopeService, MdScopeSoftware, MdScopeTile,
    MdSecurityConstraintsClassSystemOptional, MdSecurityConstraintsClassificationMandatory,
    MdSecurityConstraintsHandlingDescOptional, MdSecurityConstraintsUserNoteOptional,
    MdSpatialRepTypeGrid, MdSpatialRepTypeStereoModel, MdSpatialRepTypeTextTable,
    MdSpatialRepTypeTin, MdSpatialRepTypeVector, MdSpatialRepTypeVideo, MdTopicCategoryBiota,
    MdTopicCategoryBoundaries, MdTopicCategoryClimatologyMeteorologyAtmosphere,
    MdTopicCategoryDisaster, MdTopicCategoryEconomy, MdTopicCategoryElevation,
    MdTopicCategoryEnvironment, MdTopicCategoryExtraTerrestrial, MdTopicCategoryFarming,
    MdTopicCategoryGeoscientificInformation, MdTopicCategoryHealth,
    MdTopicCategoryImageryBaseMapsEarthCover, MdTopicCategoryInlandWaters,
    MdTopicCategoryIntelligenceMilitary, MdTopicCategoryLocation, MdTopicCategoryOceans,
    MdTopicCategoryPlanningCadastre, MdTopicCategorySociety, MdTopicCategoryStructure,
    MdTopicCategoryTransportation, MdTopicCategoryUtilitiesCommunication,
    MdTransferOptionsOfflineOptional, MdTransferOptionsOnlineOptional,
    MdTransferOptionsSizeIsFinite, MdTransferOptionsSizePositive,
    MdVectorSpatialRepGeometricObjects, MdVectorSpatialRepTopologyLevel, MediaTypeCharsetIsUtf8,
    MediaTypeIsApplicationGeoJson, MediaTypeNotApplicationJson, MolodenskyBadenkasTenParameter,
    MultiLineStringComponentsAreLineStrings, MultiLineStringCoordinatesIsArray,
    MultiLineStringCoordinatesIsNotNull, MultiLineStringEachElementIsArray,
    MultiLineStringEachLineStringHasMinTwoPositions, MultiLineStringEachPositionIsValid,
    MultiLineStringHasCoordinatesMember, MultiLineStringIsClosedAllClosed2,
    MultiLineStringMayBeEmpty, MultiLineStringSimpleWhenIntersectAtEndpointsOnly,
    MultiLineStringTypeEqualsMultiLineString, MultiLineStringValid, MultiPointComponentsArePoints,
    MultiPointCoordinatesIsArrayOfPositions, MultiPointCoordinatesIsNotNull,
    MultiPointCoordinatesMayBeEmpty, MultiPointEachElementIsValidPosition,
    MultiPointHasCoordinatesMember, MultiPointMayBeEmpty, MultiPointSimpleWhenNoTwoEqual,
    MultiPointTypeEqualsMultiPoint, MultiPointValid, MultiPolygonBoundariesDontOverlap,
    MultiPolygonBoundariesTouchAtPoints, MultiPolygonBoundaryIsAllRings,
    MultiPolygonComponentsArePolygons, MultiPolygonCoordinatesIsArray,
    MultiPolygonCoordinatesIsNotNull, MultiPolygonEachElementIsPolygonCoordinates,
    MultiPolygonEachPolygonObeysPolygonRules, MultiPolygonHasCoordinatesMember,
    MultiPolygonInteriorsDisjoint, MultiPolygonMayBeEmpty, MultiPolygonTypeEqualsMultiPolygon,
    MultiPolygonValid, Nad27EnsembleEpsg6267, Nadcon5IsUsHorizontalDatumShift,
    NoNewGeometryTypesMayBeDefined, NoProjectedCoordinatesPermitted, Ntv2IsGridHorizontalShift,
    NullAuthorityCodeInvalidForRegisteredCrs, NullGeometryDistinctFromAbsentGeometry,
    OgcAuthorityNameIsOgc, OperationMethodFormulaOptional, OperationMethodHasParameterList,
    OperationMethodNameNonEmpty, OperationMethodParameterNoDuplicates,
    OperationParameterNameNonEmpty, OperationParameterValueFiniteReal,
    OperationParameterValueHasUnit, OtherAuthorityNamesEsriIgnf, OverlapsDe9ImPattern2D,
    OverlapsDe9ImPatternLowDim, OverlapsDimensionConstraint, OverlapsIsSymmetric,
    ParameterFileStoresFilenameNotValue, ParametricAxisMustUseParametricUnit,
    ParametricCrsCsIsParametricCs, ParametricCrsDatumIsParametricDatum, ParametricCrsHasOneAxis,
    PassThroughOperationCompoundCrsUsage, PassThroughOperationDimensionConsistency,
    PassThroughOperationIndexInRange, PassThroughOperationInnerOperationNonNull,
    PassThroughOperationModifiedCoordinatesNonEmpty, PassThroughOperationPreservesSomeAxes,
    PointAlwaysValid, PointBoundaryIsEmpty, PointCoordinatesHasMinTwoElements,
    PointCoordinatesIsNotNestedArray, PointCoordinatesIsNotNull, PointCoordinatesIsSinglePosition,
    PointEmptyHasNoCoords, PointEmptyIsEmpty, PointHasCoordinatesMember, PointMDefinedWhenMPresent,
    PointOnSurfaceDefinedForAll, PointOnSurfaceIsOnGeometry, PointOnSurfaceReturnsPoint,
    PointTypeEqualsPoint, PointValid, PointXIsFinite, PointXReturnsXOrdinate, PointYIsFinite,
    PointYReturnsYOrdinate, PointZDefinedWhen3D, PointZIsFiniteWhenPresent,
    PolygonBoundaryIsAllRings, PolygonCoordinatesHasAtLeastOneRing,
    PolygonCoordinatesIsArrayOfRings, PolygonCoordinatesIsNotNull, PolygonExteriorIsCCW,
    PolygonExteriorIsLinearRing, PolygonExteriorRingHasPositiveSignedArea,
    PolygonExteriorRingIsCounterclockwise, PolygonExteriorRingNeverNull,
    PolygonFirstRingIsExteriorBoundary, PolygonHasCoordinatesMember,
    PolygonHasExactlyOneExteriorRing, PolygonHoleCountNonNegative,
    PolygonHoleRingHasNegativeSignedArea, PolygonHoleRingsAreClockwise, PolygonHolesAreCW,
    PolygonHolesAreInteriorToExteriorRing, PolygonHolesDoNotOverlap,
    PolygonHolesDontContainEachOther, PolygonHolesInsideExterior, PolygonInteriorRingNInRange,
    PolygonInteriorRingNReturnsHole, PolygonInteriorRingsAreLinearRings,
    PolygonLinearRingFirstAndLastAreIdentical, PolygonLinearRingHasMinFourPositions,
    PolygonLinearRingIsClosedLineString, PolygonLinearRingRepresentationShouldBeIdentical,
    PolygonNoRingSelfIntersects, PolygonNumInteriorRingsNonNegative,
    PolygonRightHandRuleAreaToLeft, PolygonRingDoesNotSelfIntersect, PolygonRingsDontCross,
    PolygonRingsDontTouchAlongSegment, PolygonRingsTouchAtPoints,
    PolygonSubsequentRingsAreInteriorHoles, PolygonTypeEqualsPolygon, PolygonValid,
    PositionAltitudeIsFinite, PositionAltitudeReferencesWgs84Ellipsoid,
    PositionElementOneIsLatitude, PositionElementTwoIsAltitudeWhenPresent,
    PositionElementZeroIsLongitude, PositionElementsAreJsonNumbers,
    PositionExtraElementsBeyondThreeIgnored, PositionHasAtLeastTwoElements,
    PositionInterpolationIsCartesian, PositionIsJsonArray, PositionIsNotJsonNull,
    PositionIsNotJsonNumber, PositionIsNotJsonObject, PositionIsNotJsonString,
    PositionLatitudeInRange, PositionLatitudeIsFinite, PositionLongitudeInRange,
    PositionLongitudeIsFinite, PositionShouldNotExceedThreeElements, PositionValid,
    PrimeMeridianGreenwichIsZero, PrimeMeridianGreenwichLongitudeFinite,
    PrimeMeridianGreenwichLongitudeInDegreeBounds, PrimeMeridianGreenwichLongitudeUnitIsAngular,
    PrimeMeridianNameNonEmpty, PrimeMeridianNonGreenwichAllowed, PrimeMeridianValid,
    ProjectedConventionalAxisOrderEastingFirst, ProjectedCrsAxesUseLinearUnit,
    ProjectedCrsBaseCrsIsGeographic, ProjectedCrsConventionalAxisDirections,
    ProjectedCrsCsIsCartesian, ProjectedCrsHasTwoAxes, ProjectedCrsNameNonEmpty,
    ProjectedCrsProjectionIsConversion, ProjectedNorthingFirstVariantsExist,
    PropertiesIsPreferredLocationForAppData, PtLocaleCharacterEncodingMandatory,
    PtLocaleCountryOptional, PtLocaleLanguageCodeThreeLetterLowercase, PtLocaleLanguageMandatory,
    RegisteredCrsNullAuthorityCodeInvalid, RelatePatternCharacters, RelatePatternLength9,
    RelateReturnsBooleanMatchingPattern, ScCrsDomainOfValidityIsExtent,
    ScCrsIdentifierHasAuthorityAndCode, ScCrsIsAbstract, ScCrsNameNonEmpty, ScCrsScopeNonEmpty,
    SfsGeometryValid, SphericalCsAngularAxesThenLinear, SphericalCsApplicableToGeocentricContext,
    SphericalCsHasThreeAxes, SridAssignedAtConstruction, SridIsInteger, SridNonNegative,
    SrsConsistentInCollection, StaticCrsDatumAtFixedEpoch, StaticCrsPlateFixedNoEpochRequired,
    SymDifferenceEqualsUnionMinusIntersection, SymDifferenceIsCommutative,
    TemporalCrsCsIsTemporalCs, TemporalCrsDatumIsTemporalDatum, TemporalCrsHasOneAxis,
    TemporalDatumOriginIsIso8601DateTime, TimeAxisMustUseTemporalUnit, TouchesDe9ImPattern,
    TouchesInteriorsDisjoint, TouchesIsSymmetric, TransformationAccuracyNonZero,
    TransformationAccuracyPositiveReal, TransformationInverseApproximate,
    TransformationInvolvesDatumChange, TransformationNad27ToWgs84UsesHelmert, UnionDimensionIsMax,
    UnionEqualsIntersectionPlusSymDifference, UnionIsAssociative, UnionIsCommutative,
    UnionSupersetOfBothInputs, UomAngularConvertToRadians, UomConversionFactorFinite,
    UomConversionFactorPositive, UomFeetAmbiguityInternationalVsSurvey, UomLinearConvertToMetres,
    UomNameNonEmpty, UomScaleDimensionless, UomTimeConvertToSeconds, UtmAxisOrderEastingFirst,
    UtmCommonParametersFalseEastingAndScale, UtmFalseEasting500000,
    UtmNorthZoneEpsgRange32601To32660, UtmNorthZoneFalseNorthing0,
    UtmScaleFactorAtCentralMeridian0996, UtmSouthZoneEpsgRange32701To32760,
    UtmSouthZoneFalseNorthing10000000, UtmZoneNumberOneToSixty, UtmZoneWidthSixDegrees,
    VertconIsUsVerticalDatumShift, VerticalCrsAxisLinearUnit, VerticalCrsCsIsVerticalCs,
    VerticalCrsDatumIsVerticalReferenceFrame, VerticalCrsDepthAxisDirectionDown,
    VerticalCrsEpsgRange5000To5999, VerticalCrsHasOneAxis, VerticalCrsHeightAxisDirectionUp,
    VerticalCrsNameNonEmpty, VerticalReferenceFrameAnchorOptional,
    VerticalReferenceFrameGravityRelated, VerticalReferenceFrameNameNonEmpty,
    VerticalReferenceFrameRealizationEpochIsIso8601, WithinDe9ImPattern, WithinIsInverseOfContains,
    WithinIsNotSymmetric, WkbByteOrderBigEndian, WkbByteOrderLittleEndian,
    WkbByteOrderMarkerPresent, WkbByteOrderMarkerTwoValues, WkbCoordinateIsDouble,
    WkbCoordinatesByteOrderMatches, WkbCountFieldsAreUint32, WkbLengthValid, WkbMVariant,
    WkbPointLength21Bytes2D, WkbRingHasCount, WkbRoundTrip, WkbSubGeometriesAreCompleteBlobs,
    WkbTypeCodeGeometryCollection, WkbTypeCodeLineString, WkbTypeCodeMultiLineString,
    WkbTypeCodeMultiPoint, WkbTypeCodeMultiPolygon, WkbTypeCodePoint, WkbTypeCodePolygon,
    WkbTypeCodeValid, WkbZMVariant, WkbZVariant, WktCoordinateListInParens,
    WktCoordsSeparatedBySpace, WktDimensionTagPrecedesParens, WktEmptyApplicableToAllTypes,
    WktEmptyGeometry, WktGeometryCollectionProduction, WktKeywordCaseInsensitive, WktKeywordValid,
    WktLineStringProduction, WktMVariant, WktMultiLineStringProduction, WktMultiPointProduction,
    WktMultiPolygonProduction, WktNestingForMultiTypes, WktPointProduction,
    WktPolygonExteriorFirstRing, WktPolygonProduction, WktPositionsSeparatedByComma,
    WktRingsParenthesized, WktRingsSeparatedByComma, WktRoundTrip, WktZMVariant, WktZVariant,
};

pub use error::{GisError, GisErrorKind, GisResult};
pub use traits::{
    GisBackend, GisCrsBuilder, GisCrsLookup, GisCrsTransformer, Iso19111Identified, Iso19111Scoped,
    Iso19115CitationFactory, Iso19115ContactMeta, Iso19115DateMeta, Iso19115ExtentFactory,
    Iso19115LineageFactory, Iso19115QualityMeta, Iso19115RecordFactory, SfsGeometryFactory,
    SfsGeometryIo, SfsGeometryMeta, SfsSetOps, SfsTopology,
};
pub use types::{
    AuthorityCode, AxisDirection, CitationDescriptor, CoordinateAxisInfo, CoordinateMetadata,
    CoordinateSystemParams, CrsInfo, CrsType, CsType, DataQualityDescriptor, DataQualityReport,
    DatumEnsembleInfo, DecimalYear, DomainExtent, EllipsoidParams, EpsgCode, ExtentDescriptor,
    GeodeticFrameParams, GeographicBboxDescriptor, GeographicBoundingBox,
    GeometryCollectionDescriptor, HelmertConvention, IdentificationDescriptor, Iso19115Date,
    LineStringDescriptor, LineageDescriptor, LineageProcessStep, LinearRingDescriptor,
    MetadataDescriptor, MultiGeometryDescriptor, PointDescriptor, PolygonDescriptor,
    PrimeMeridianParams, ResponsibilityDescriptor, SfsCoordinate, SfsCoordinate3D,
    TemporalExtentDescriptor, VerticalExtentDescriptor,
};
