//! MCP tool transport for `serde_json` — navigate, query, and transform JSON values as tools.
//!
//! Wraps `serde_json::Value`, `serde_json::Map<String, Value>`, and `serde_json::Number`
//! as elicitation-enabled newtypes with MCP tools generated by `#[reflect_methods]`.
//!
//! # Quick Start
//!
//! ```ignore
//! use elicit_serde_json::JsonPlugin;
//! use elicitation::PluginRegistry;
//!
//! #[tokio::main]
//! async fn main() {
//!     let registry = PluginRegistry::new()
//!         .register("serde_json", JsonPlugin::new());
//!     // registry.serve(rmcp::transport::stdio()).await.unwrap();
//! }
//! ```

#![forbid(unsafe_code)]
#![warn(missing_docs)]

mod number;
mod value;

pub use number::JsonNumber;
pub use value::JsonValue;
