//! Build script: generates formal verification proof harnesses for archive VSMs
//! by composing token streams from `VerifiedStateMachine` impls.
//!
//! Generates files for all three verifiers into their respective `generated/` dirs:
//!
//! - `src/kani/generated/`    — Kani proof harnesses (`#[kani::proof]`)
//! - `src/creusot/generated/` — Creusot companions (`#[cfg(creusot)]`)
//! - `src/verus/generated/`   — Verus companions (`#[cfg(verus)]`)
//!
//! Regenerate: `cargo build -p elicit_proofs`

use elicit_server::archive::vsm::{
    ArchiveConnectionMachine, ArchiveNavMachine, ArchiveOverlayMachine, ArchivePanelMachine,
};
use elicitation::VerifiedStateMachine;

fn main() {
    let manifest_dir =
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by Cargo");
    let base = std::path::Path::new(&manifest_dir);

    let kani_gen = base.join("src/kani/generated");
    let creusot_gen = base.join("src/creusot/generated");
    let verus_gen = base.join("src/verus/generated");
    std::fs::create_dir_all(&kani_gen).expect("create src/kani/generated/");
    std::fs::create_dir_all(&creusot_gen).expect("create src/creusot/generated/");
    std::fs::create_dir_all(&verus_gen).expect("create src/verus/generated/");

    generate_kani_proofs(&kani_gen);
    generate_creusot_companions(&creusot_gen);
    generate_verus_companions(&verus_gen);

    println!("cargo:rerun-if-changed=../elicit_server/src/archive/vsm/connection.rs");
    println!("cargo:rerun-if-changed=../elicit_server/src/archive/vsm/nav.rs");
    println!("cargo:rerun-if-changed=../elicit_server/src/archive/vsm/overlay.rs");
    println!("cargo:rerun-if-changed=../elicit_server/src/archive/vsm/panel.rs");
}

// ─────────────────────────────────────────────────────────────────────────────
//  Kani
// ─────────────────────────────────────────────────────────────────────────────

fn generate_kani_proofs(gen_dir: &std::path::Path) {
    let mut manifest: Vec<(String, String)> = Vec::new();

    let body = dedup_kani_proofs(&[ArchiveConnectionMachine::vsm_kani_proof()]);
    for name in extract_harness_names(&body) {
        manifest.push(("kani::generated::archive_connection".to_string(), name));
    }
    write_vsm_file(
        gen_dir,
        "archive_connection.rs",
        "ArchiveConnectionMachine",
        &body,
    );

    let body = dedup_kani_proofs(&[ArchiveNavMachine::vsm_kani_proof()]);
    for name in extract_harness_names(&body) {
        manifest.push(("kani::generated::archive_nav".to_string(), name));
    }
    write_vsm_file(gen_dir, "archive_nav.rs", "ArchiveNavMachine", &body);

    let body = dedup_kani_proofs(&[ArchiveOverlayMachine::vsm_kani_proof()]);
    for name in extract_harness_names(&body) {
        manifest.push(("kani::generated::archive_overlay".to_string(), name));
    }
    write_vsm_file(
        gen_dir,
        "archive_overlay.rs",
        "ArchiveOverlayMachine",
        &body,
    );

    let body = dedup_kani_proofs(&[ArchivePanelMachine::vsm_kani_proof()]);
    for name in extract_harness_names(&body) {
        manifest.push(("kani::generated::archive_panel".to_string(), name));
    }
    write_vsm_file(gen_dir, "archive_panel.rs", "ArchivePanelMachine", &body);

    write_manifest(gen_dir, &manifest);
}

fn write_vsm_file(gen_dir: &std::path::Path, filename: &str, machine: &str, body: &str) {
    let raw = format!(
        "#[cfg(kani)] use elicitation::Established;\n\
         #[cfg(kani)] use elicit_server::archive::vsm::*;\n\
         #[cfg(kani)] use elicit_server::archive::types::*;\n\
         #[cfg(kani)] use elicit_server::archive::display::*;\n\
         #[cfg(kani)] use elicit_server::archive::nav_tree::*;\n\
         {body}"
    );
    let formatted = syn::parse_file(&raw)
        .map(|f| prettyplease::unparse(&f))
        .unwrap_or(raw);
    let code = format!(
        "// AUTO-GENERATED by elicit_proofs/build.rs — DO NOT EDIT\n\
         // Regenerate: cargo build -p elicit_proofs\n\
         //\n\
         // Composed Kani proof harnesses for {machine}.\n\
         // Source: elicit_server::archive::vsm\n\n\
         {formatted}"
    );
    let path = gen_dir.join(filename);
    std::fs::write(&path, &code).unwrap_or_else(|e| panic!("write {filename}: {e}"));
    fmt_file(&path);
}

// ─────────────────────────────────────────────────────────────────────────────
//  Creusot
// ─────────────────────────────────────────────────────────────────────────────

// Inline #[logic] predicate definitions for each machine invariant.
//
// These are copied from `src/creusot/vsm_invariants.rs` and emitted directly
// into the generated companion files so that why3find can see the predicate
// bodies (cross-module #[logic] bodies are opaque in Why3/COMA, causing 2/3
// proof goals to fail).  Update here whenever vsm_invariants.rs changes.

const INV_CONNECTION: &str = concat!(
    // All ArchiveConnectionState variants are well-formed by construction.
    // Strings (profile names, paths, error messages) are not validated by the
    // VSM, so there are no cross-field constraints to express.  Intentionally true.
    "#[cfg(creusot)] #[logic] pub fn archive_connection_consistent",
    "(_state: &ArchiveConnectionState) -> bool { true }",
);

const INV_NAV: &str = "\
#[cfg(creusot)]
#[logic]
pub fn archive_nav_consistent(state: &ArchiveNavState) -> bool {
    pearlite! {
        match state {
            ArchiveNavState::NavFiltered { filter, .. } => filter@.len() > 0,
            _ => true,
        }
    }
}";

// Non-trivial: pearlite body — syn/prettyplease will fall back to raw if they
// can't round-trip the macro invocation.
const INV_OVERLAY: &str = "\
#[cfg(creusot)]
#[logic]
pub fn archive_overlay_consistent(state: &ArchiveOverlayState) -> bool {
    pearlite! {
        match state {
            ArchiveOverlayState::ExportPickerOpen { idx, formats } =>
                idx@ <= formats@.len(),
            ArchiveOverlayState::SavedBrowserOpen { entries, idx } =>
                idx@ <= entries@.len(),
            _ => true,
        }
    }
}";

const INV_PANEL: &str = "\
#[cfg(creusot)]
#[logic]
pub fn archive_panel_consistent(state: &ArchivePanelState) -> bool {
    pearlite! {
        match state {
            ArchivePanelState::SqlEditor { running, result, .. } =>
                *running ==> match result { None => true, Some(_) => false },
            _ => true,
        }
    }
}";

fn generate_creusot_companions(gen_dir: &std::path::Path) {
    write_creusot_vsm_file(
        gen_dir,
        "archive_connection.rs",
        "ArchiveConnectionMachine",
        INV_CONNECTION,
        &ArchiveConnectionMachine::vsm_creusot_proof(),
    );
    write_creusot_vsm_file(
        gen_dir,
        "archive_nav.rs",
        "ArchiveNavMachine",
        INV_NAV,
        &ArchiveNavMachine::vsm_creusot_proof(),
    );
    write_creusot_vsm_file(
        gen_dir,
        "archive_overlay.rs",
        "ArchiveOverlayMachine",
        INV_OVERLAY,
        &ArchiveOverlayMachine::vsm_creusot_proof(),
    );
    write_creusot_vsm_file(
        gen_dir,
        "archive_panel.rs",
        "ArchivePanelMachine",
        INV_PANEL,
        &ArchivePanelMachine::vsm_creusot_proof(),
    );
}

fn write_creusot_vsm_file(
    gen_dir: &std::path::Path,
    filename: &str,
    machine: &str,
    inv_logic: &str,
    body: &proc_macro2::TokenStream,
) {
    let body_str = body.to_string();
    let raw = format!(
        "#[cfg(creusot)] use ::creusot_std::prelude::*;\n\
         #[cfg(creusot)] use elicitation::Established;\n\
         #[cfg(creusot)] use elicitation::kani_label;\n\
         #[cfg(creusot)] use elicit_server::archive::vsm::*;\n\
         #[cfg(creusot)] use elicit_server::archive::types::*;\n\
         #[cfg(creusot)] use elicit_server::archive::display::*;\n\
         #[cfg(creusot)] use elicit_server::archive::nav_tree::*;\n\
         {inv_logic}\n\
         {body_str}"
    );
    let formatted = syn::parse_file(&raw)
        .map(|f| prettyplease::unparse(&f))
        .unwrap_or(raw);
    let code = format!(
        "// AUTO-GENERATED by elicit_proofs/build.rs — DO NOT EDIT\n\
         // Regenerate: cargo build -p elicit_proofs\n\
         //\n\
         // Creusot companion contracts for {machine}.\n\
         // Source: elicit_server::archive::vsm\n\n\
         {formatted}"
    );
    let path = gen_dir.join(filename);
    std::fs::write(&path, &code).unwrap_or_else(|e| panic!("write {filename}: {e}"));
    fmt_file(&path);
}

// ─────────────────────────────────────────────────────────────────────────────
//  Verus
// ─────────────────────────────────────────────────────────────────────────────

// Inline `pub open spec fn` definitions for each machine invariant.
//
// These are emitted directly into the generated companion files so that Verus
// can see the predicate bodies.  All functions return `true` for Phase 3
// (trivially-provable stubs).  Update when real invariants are needed.

// All items are gated with #[cfg(verus)]; the verus!{} block uses Verus-specific
// syntax that is not valid Rust — the generated files carry #![rustfmt::skip].

const VERUS_INV_CONNECTION: &str = concat!(
    "#[cfg(verus)] verus! { pub open spec fn archive_connection_consistent",
    // All variants are well-formed by construction; no cross-field constraints.
    "(_state: &ArchiveConnectionState) -> bool { true } }",
);

const VERUS_INV_NAV: &str = "\
#[cfg(verus)]
verus! {
    pub open spec fn archive_nav_consistent(state: &ArchiveNavState) -> bool {
        match *state {
            ArchiveNavState::NavFiltered { filter, .. } => filter@.len() > 0,
            _ => true,
        }
    }
}";

const VERUS_INV_OVERLAY: &str = "\
#[cfg(verus)]
verus! {
    pub open spec fn archive_overlay_consistent(state: &ArchiveOverlayState) -> bool {
        match *state {
            ArchiveOverlayState::ExportPickerOpen { idx, formats } =>
                idx <= formats@.len(),
            ArchiveOverlayState::SavedBrowserOpen { entries, idx } =>
                idx <= entries@.len(),
            _ => true,
        }
    }
}";

const VERUS_INV_PANEL: &str = "\
#[cfg(verus)]
verus! {
    pub open spec fn archive_panel_consistent(state: &ArchivePanelState) -> bool {
        match *state {
            ArchivePanelState::SqlEditor { running, result, .. } =>
                running ==> result.is_None(),
            _ => true,
        }
    }
}";

fn generate_verus_companions(gen_dir: &std::path::Path) {
    write_verus_vsm_file(
        gen_dir,
        "archive_connection.rs",
        "ArchiveConnectionMachine",
        VERUS_INV_CONNECTION,
        &ArchiveConnectionMachine::vsm_verus_proof(),
    );
    write_verus_vsm_file(
        gen_dir,
        "archive_nav.rs",
        "ArchiveNavMachine",
        VERUS_INV_NAV,
        &ArchiveNavMachine::vsm_verus_proof(),
    );
    write_verus_vsm_file(
        gen_dir,
        "archive_overlay.rs",
        "ArchiveOverlayMachine",
        VERUS_INV_OVERLAY,
        &ArchiveOverlayMachine::vsm_verus_proof(),
    );
    write_verus_vsm_file(
        gen_dir,
        "archive_panel.rs",
        "ArchivePanelMachine",
        VERUS_INV_PANEL,
        &ArchivePanelMachine::vsm_verus_proof(),
    );
}

fn write_verus_vsm_file(
    gen_dir: &std::path::Path,
    filename: &str,
    machine: &str,
    inv_spec: &str,
    body: &proc_macro2::TokenStream,
) {
    // Verus syntax inside verus!{} blocks is not valid Rust — skip prettyplease.
    // Note: #![rustfmt::skip] is NOT used here because these files are only compiled
    // via #[cfg(verus)]-gated pub mod declarations, so rustfmt never reaches them.
    let body_str = body.to_string();
    let code = format!(
        "// AUTO-GENERATED by elicit_proofs/build.rs — DO NOT EDIT\n\
         // Regenerate: cargo build -p elicit_proofs\n\
         //\n\
         // Verus companion contracts for {machine}.\n\
         // Source: elicit_server::archive::vsm\n\
         //\n\
         // All items are gated with #[cfg(verus)]; invisible to normal Rust builds.\n\n\
         #[cfg(verus)]\n\
         use ::vstd::prelude::*;\n\
         #[cfg(verus)]\n\
         use ::verus_builtin_macros::verus;\n\
         #[cfg(verus)]\n\
         use elicitation::Established;\n\
         #[cfg(verus)]\n\
         use elicit_server::archive::vsm::*;\n\
         #[cfg(verus)]\n\
         use elicit_server::archive::types::*;\n\
         #[cfg(verus)]\n\
         use elicit_server::archive::display::*;\n\
         #[cfg(verus)]\n\
         use elicit_server::archive::nav_tree::*;\n\
         {inv_spec}\n\
         {body_str}\n"
    );
    let path = gen_dir.join(filename);
    std::fs::write(&path, &code).unwrap_or_else(|e| panic!("write {filename}: {e}"));
    fmt_file(&path);
}

fn fmt_file(path: &std::path::Path) {
    let cargo = std::env::var("CARGO").unwrap_or_else(|_| "cargo".to_string());
    // Use `cargo fmt` (not bare `rustfmt`) so it reads the correct edition and
    // workspace rustfmt.toml.  We pass the absolute file path after `--` so
    // rustfmt formats only this file instead of the whole crate.
    let manifest =
        std::path::Path::new(&std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"))
            .join("Cargo.toml");
    let status = std::process::Command::new(&cargo)
        .arg("fmt")
        .arg("--manifest-path")
        .arg(&manifest)
        .arg("--")
        .arg(path.canonicalize().unwrap_or_else(|_| path.to_path_buf()))
        .status()
        .unwrap_or_else(|e| panic!("failed to spawn cargo fmt on {}: {e}", path.display()));
    assert!(
        status.success(),
        "cargo fmt failed on {} — fix the generated code template in build.rs",
        path.display()
    );
}

fn dedup_kani_proofs(streams: &[proc_macro2::TokenStream]) -> String {
    let mut seen = std::collections::HashSet::new();
    let mut result = String::new();
    for ts in streams {
        let s = ts.to_string();
        for chunk in extract_proof_chunks(&s) {
            if let Some(name) = extract_fn_name(&chunk)
                && seen.insert(name)
            {
                result.push_str(&chunk);
                result.push('\n');
            }
        }
    }
    result
}

fn extract_harness_names(body: &str) -> Vec<String> {
    extract_proof_chunks(body)
        .into_iter()
        .filter_map(|chunk| extract_fn_name(&chunk))
        .collect()
}

fn write_manifest(gen_dir: &std::path::Path, harnesses: &[(String, String)]) {
    let mut json = String::from("[\n");
    for (i, (module, name)) in harnesses.iter().enumerate() {
        json.push_str(&format!(
            "  {{\"module\":\"{module}\",\"name\":\"{name}\"}}"
        ));
        if i + 1 < harnesses.len() {
            json.push(',');
        }
        json.push('\n');
    }
    json.push_str("]\n");
    std::fs::write(gen_dir.join("manifest.json"), json).expect("write manifest.json");
}

fn extract_proof_chunks(s: &str) -> Vec<String> {
    let mut chunks = Vec::new();
    let bytes = s.as_bytes();
    let len = bytes.len();
    let mut i = 0;
    while i < len {
        if i + 3 <= len && &s[i..i + 3] == "# [" {
            let start = i;
            let mut depth: i32 = 0;
            let mut found_brace = false;
            let mut j = i;
            while j < len {
                match bytes[j] {
                    b'{' => {
                        depth += 1;
                        found_brace = true;
                    }
                    b'}' => {
                        depth -= 1;
                        if found_brace && depth == 0 {
                            chunks.push(s[start..=j].to_string());
                            i = j + 1;
                            break;
                        }
                    }
                    _ => {}
                }
                j += 1;
            }
            if j >= len {
                break;
            }
        } else {
            i += 1;
        }
    }
    chunks
}

fn extract_fn_name(chunk: &str) -> Option<String> {
    let fn_pos = chunk.find("fn ")?;
    let after_fn = &chunk[fn_pos + 3..];
    let name_end = after_fn
        .find(|c: char| !c.is_alphanumeric() && c != '_')
        .unwrap_or(after_fn.len());
    Some(after_fn[..name_end].to_string())
}
