//! Build script: generates formal verification proof harnesses for archive VSMs
//! by composing token streams from `VerifiedStateMachine` impls.
//!
//! Generates files for all three verifiers into their respective `generated/` dirs:
//!
//! - `src/kani/generated/`    — Kani proof harnesses (`#[kani::proof]`)
//! - `src/creusot/generated/` — Creusot companions (`#[cfg(creusot)]`)
//! - `src/verus/generated/`   — Verus companions (`#[cfg(verus)]`)
//!
//! Regenerate: `cargo build -p elicit_proofs`

use elicit_server::archive::vsm::{
    ArchiveConnectionMachine, ArchiveNavMachine, ArchiveOverlayMachine, ArchivePanelMachine,
};
use elicitation::VerifiedStateMachine;

fn main() {
    let manifest_dir =
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by Cargo");
    let base = std::path::Path::new(&manifest_dir);

    let kani_gen = base.join("src/kani/generated");
    let creusot_gen = base.join("src/creusot/generated");
    let verus_gen = base.join("src/verus/generated");
    std::fs::create_dir_all(&kani_gen).expect("create src/kani/generated/");
    std::fs::create_dir_all(&creusot_gen).expect("create src/creusot/generated/");
    std::fs::create_dir_all(&verus_gen).expect("create src/verus/generated/");

    generate_kani_proofs(&kani_gen);
    // Creusot and Verus generation will be added as those companion impls mature.
    generate_creusot_stubs(&creusot_gen);
    generate_verus_stubs(&verus_gen);

    println!("cargo:rerun-if-changed=../elicit_server/src/archive/vsm/connection.rs");
    println!("cargo:rerun-if-changed=../elicit_server/src/archive/vsm/nav.rs");
    println!("cargo:rerun-if-changed=../elicit_server/src/archive/vsm/overlay.rs");
    println!("cargo:rerun-if-changed=../elicit_server/src/archive/vsm/panel.rs");
}

// ─────────────────────────────────────────────────────────────────────────────
//  Kani
// ─────────────────────────────────────────────────────────────────────────────

fn generate_kani_proofs(gen_dir: &std::path::Path) {
    write_vsm_file(
        gen_dir,
        "archive_connection.rs",
        "ArchiveConnectionMachine",
        &dedup_kani_proofs(&[ArchiveConnectionMachine::vsm_kani_proof()]),
    );
    write_vsm_file(
        gen_dir,
        "archive_nav.rs",
        "ArchiveNavMachine",
        &dedup_kani_proofs(&[ArchiveNavMachine::vsm_kani_proof()]),
    );
    write_vsm_file(
        gen_dir,
        "archive_overlay.rs",
        "ArchiveOverlayMachine",
        &dedup_kani_proofs(&[ArchiveOverlayMachine::vsm_kani_proof()]),
    );
    write_vsm_file(
        gen_dir,
        "archive_panel.rs",
        "ArchivePanelMachine",
        &dedup_kani_proofs(&[ArchivePanelMachine::vsm_kani_proof()]),
    );
}

fn write_vsm_file(gen_dir: &std::path::Path, filename: &str, machine: &str, body: &str) {
    let raw = format!(
        "use elicit_server::archive::vsm::*;\n{body}"
    );
    let formatted = syn::parse_file(&raw)
        .map(|f| prettyplease::unparse(&f))
        .unwrap_or(raw);
    let code = format!(
        "// AUTO-GENERATED by elicit_proofs/build.rs — DO NOT EDIT\n\
         // Regenerate: cargo build -p elicit_proofs\n\
         //\n\
         // Composed Kani proof harnesses for {machine}.\n\
         // Source: elicit_server::archive::vsm\n\n\
         {formatted}"
    );
    std::fs::write(gen_dir.join(filename), &code)
        .unwrap_or_else(|e| panic!("write {filename}: {e}"));
}

// ─────────────────────────────────────────────────────────────────────────────
//  Creusot / Verus stubs (wired up once companion token streams mature)
// ─────────────────────────────────────────────────────────────────────────────

fn generate_creusot_stubs(gen_dir: &std::path::Path) {
    let placeholder = "// AUTO-GENERATED by elicit_proofs/build.rs — DO NOT EDIT\n\
                        // Creusot companions will be generated here once\n\
                        // VerifiedStateMachine::vsm_creusot_proof() is implemented.\n";
    std::fs::write(gen_dir.join("archive.rs"), placeholder).expect("write creusot archive.rs");
}

fn generate_verus_stubs(gen_dir: &std::path::Path) {
    let placeholder = "// AUTO-GENERATED by elicit_proofs/build.rs — DO NOT EDIT\n\
                        // Verus companions will be generated here once\n\
                        // VerifiedStateMachine::vsm_verus_proof() is implemented.\n";
    std::fs::write(gen_dir.join("archive.rs"), placeholder).expect("write verus archive.rs");
}

// ─────────────────────────────────────────────────────────────────────────────
//  Deduplication helpers (adapted from strictly_proofs/build.rs)
// ─────────────────────────────────────────────────────────────────────────────

fn dedup_kani_proofs(streams: &[proc_macro2::TokenStream]) -> String {
    let mut seen = std::collections::HashSet::new();
    let mut result = String::new();
    for ts in streams {
        let s = ts.to_string();
        for chunk in extract_proof_chunks(&s) {
            if let Some(name) = extract_fn_name(&chunk)
                && seen.insert(name)
            {
                result.push_str(&chunk);
                result.push('\n');
            }
        }
    }
    result
}

fn extract_proof_chunks(s: &str) -> Vec<String> {
    let mut chunks = Vec::new();
    let bytes = s.as_bytes();
    let len = bytes.len();
    let mut i = 0;
    while i < len {
        if i + 3 <= len && &s[i..i + 3] == "# [" {
            let start = i;
            let mut depth: i32 = 0;
            let mut found_brace = false;
            let mut j = i;
            while j < len {
                match bytes[j] {
                    b'{' => {
                        depth += 1;
                        found_brace = true;
                    }
                    b'}' => {
                        depth -= 1;
                        if found_brace && depth == 0 {
                            chunks.push(s[start..=j].to_string());
                            i = j + 1;
                            break;
                        }
                    }
                    _ => {}
                }
                j += 1;
            }
            if j >= len {
                break;
            }
        } else {
            i += 1;
        }
    }
    chunks
}

fn extract_fn_name(chunk: &str) -> Option<String> {
    let fn_pos = chunk.find("fn ")?;
    let after_fn = &chunk[fn_pos + 3..];
    let name_end = after_fn
        .find(|c: char| !c.is_alphanumeric() && c != '_')
        .unwrap_or(after_fn.len());
    Some(after_fn[..name_end].to_string())
}
