//! Build script for elicit_proofs.
//!
//! Proof files are pre-generated by the `elicitation generate` CLI and committed
//! to the repository. To regenerate after changing VSM source files:
//!
//! ```text
//! elicitation generate kani    --crate-path crates/elicit_server/src/archive/vsm \
//!                               --out crates/elicit_proofs/src/kani/generated
//! elicitation generate creusot --crate-path crates/elicit_server/src/archive/vsm \
//!                               --out crates/elicit_proofs/src/creusot/generated
//! elicitation generate verus   --crate-path crates/elicit_server/src/archive/vsm \
//!                               --out crates/elicit_proofs/src/verus/generated
//! ```

fn main() {
    // Generated files are pre-committed; no build-time generation needed.
    println!("cargo:rerun-if-changed=build.rs");
}
