//! Creusot companion file generator for `elicitation generate creusot`.
//!
//! Takes a `VsmDescriptor` (produced by the source scanner) and emits a Rust
//! source file containing Creusot `#[requires]`/`#[ensures]` contracts that
//! replace what `VerifiedStateMachine::vsm_creusot_proof()` produces at build time.
//!
//! The generated file follows the pattern in `elicit_proofs/src/creusot/generated/`:
//! 1. `#[cfg(creusot)] use` imports
//! 2. `#[cfg(creusot)] #[logic] pub fn inv(state) -> bool { <body> }`
//! 3. `#[cfg(creusot)] #[trusted] pub fn verify_*_prop_creusot()` marker
//! 4. Per-transition: `#[cfg(creusot)] #[requires(inv)] #[ensures(inv)] pub(crate) fn t__creusot(...) { t(...) }`

use std::path::Path;

use crate::cli::generate::{find_crate_name, scanner::{ArgKind, TransitionFn, VsmDescriptor}};

// ─── Public API ───────────────────────────────────────────────────────────────

/// Generate the full Creusot companion file content for `vsm`.
///
/// `crate_root` is used to discover the crate name via `Cargo.toml` and emit
/// `use {crate_name}::*` alongside the Creusot stdlib imports.
///
/// Returns `Err` with an actionable message when a named invariant is present
/// but `creusot_inv_body` could not be resolved.
#[tracing::instrument(skip(vsm, crate_root), fields(machine = %vsm.machine))]
pub fn generate_creusot_file(
    vsm: &VsmDescriptor,
    crate_root: impl AsRef<Path>,
) -> Result<String, String> {
    let machine = &vsm.machine;
    let state_ty = machine.replace("Machine", "State");
    let crate_name = find_crate_name(crate_root.as_ref());

    // Resolve invariant — error only when an invariant exists without a body.
    let inv_parts: Option<(&str, &str, &str)> = match &vsm.invariant {
        Some(p) => {
            let fn_name = p
                .creusot_fn
                .as_deref()
                .unwrap_or_else(|| p.name.as_str());
            let body = p.creusot_inv_body.as_deref().ok_or_else(|| {
                let hint_fn = p.creusot_fn.as_deref().unwrap_or("creusot_invariant_fn");
                format!(
                    "cannot generate Creusot companion for {machine}: \
                     invariant body for `{hint_fn}` not found\n  \
                     hint: add `creusot_inv_body = \"...\"` to #[prop(...)] on `{name}`,\n  \
                        or define `pub fn {hint_fn}(state: &{state_ty}) -> bool {{ ... }}`\n  \
                           in a file under the scan root (without #[cfg(creusot)] gate)",
                    name = p.name,
                )
            })?;
            Some((fn_name, p.name.as_str(), body))
        }
        None => None,
    };

    let mut lines: Vec<String> = Vec::new();

    // ── Header ──────────────────────────────────────────────────────────────
    lines.push("// AUTO-GENERATED by `elicitation generate creusot` — DO NOT EDIT".to_string());
    lines.push("//".to_string());
    lines.push(format!("// Creusot companion contracts for {machine}."));
    lines.push("// Regenerate: elicitation generate creusot --crate-path <root>".to_string());
    lines.push("//".to_string());
    lines.push(
        "// All items are gated with #[cfg(creusot)]; invisible to normal Rust builds.".to_string(),
    );
    lines.push(String::new());

    // ── Imports ─────────────────────────────────────────────────────────────
    for import in &[
        "::creusot_std::prelude::*".to_string(),
        "elicitation::Established".to_string(),
        "elicitation::kani_label".to_string(),
        format!("{crate_name}::*"),
    ] {
        lines.push("#[cfg(creusot)]".to_string());
        lines.push(format!("use {import};"));
    }
    lines.push(String::new());

    // ── Logic invariant fn + wrappers ────────────────────────────────────────
    if let Some((inv_fn, consistent_ty, inv_body)) = inv_parts {
        lines.push("#[cfg(creusot)]".to_string());
        lines.push("#[logic]".to_string());
        lines.push(format!(
            "pub fn {inv_fn}(state: &{state_ty}) -> bool {{\n    pearlite! {{ {inv_body} }}\n}}"
        ));
        lines.push(String::new());

        // ── Marker proof fn ──────────────────────────────────────────────────
        let snake = to_snake(consistent_ty);
        lines.push("#[cfg(creusot)]".to_string());
        lines.push("#[requires(true)]".to_string());
        lines.push("#[ensures(result)]".to_string());
        lines.push("#[trusted]".to_string());
        lines.push(format!(
            "pub fn verify_{snake}_prop_creusot() -> bool {{ true }}"
        ));
        lines.push(String::new());

        // ── Per-transition call-through wrappers ─────────────────────────────
        for name in &vsm.transitions {
            let tf = vsm.transition_fns.iter().find(|tf| &tf.name == name);
            lines.push(emit_creusot_wrapper(name, &state_ty, consistent_ty, inv_fn, tf));
        }
    }

    Ok(lines.join("\n") + "\n")
}

// ─── Emitters ────────────────────────────────────────────────────────────────

/// Emit one `#[cfg(creusot)] ... pub(crate) fn {name}__creusot(...)` call-through wrapper.
fn emit_creusot_wrapper(
    fn_name: &str,
    state_ty: &str,
    consistent_ty: &str,
    inv_fn: &str,
    tf: Option<&TransitionFn>,
) -> String {
    let (params, call_args) = match tf {
        Some(tf) => (emit_params(tf, state_ty), emit_call_args(tf)),
        None => (
            format!("state: {state_ty}, proof: Established<{consistent_ty}>"),
            "state, proof".to_string(),
        ),
    };

    let mut lines: Vec<String> = Vec::new();
    lines.push("#[cfg(creusot)]".to_string());
    lines.push(format!("#[requires({inv_fn}(&state))]"));
    lines.push(format!("#[ensures({inv_fn}(&result.0))]"));
    lines.push(format!(
        "pub(crate) fn {fn_name}__creusot({params}) \
         -> ({state_ty}, Established<{consistent_ty}>) \
         {{ {fn_name}({call_args}) }}"
    ));
    lines.push(String::new());
    lines.join("\n")
}

/// Emit function parameter list: `state: State, proof: Established<T>, extra: Type, ...`
fn emit_params(tf: &TransitionFn, state_ty: &str) -> String {
    let mut parts: Vec<String> = Vec::new();
    for arg in &tf.args {
        let (name, ty) = match &arg.kind {
            ArgKind::State => ("state".to_string(), state_ty.to_string()),
            // Use the actual parameter name from the source (e.g. `proof`,
            // `square_proof`, `turn_proof`) so there are no duplicate bindings.
            ArgKind::Proof { inner } => (arg.name.clone(), format!("Established<{inner}>")),
            _ => (arg.name.trim_start_matches('_').to_string(), arg.ty.clone()),
        };
        parts.push(format!("{name}: {ty}"));
    }
    parts.join(", ")
}

/// Emit call argument list: `state, proof, extra, ...`
fn emit_call_args(tf: &TransitionFn) -> String {
    tf.args
        .iter()
        .map(|arg| match arg.kind {
            ArgKind::State => "state".to_string(),
            // Use the actual binding name so extra proofs forward correctly.
            ArgKind::Proof { .. } => arg.name.clone(),
            _ => arg.name.trim_start_matches('_').to_string(),
        })
        .collect::<Vec<_>>()
        .join(", ")
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/// Convert PascalCase to snake_case.
fn to_snake(s: &str) -> String {
    let mut out = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            out.push('_');
        }
        out.push(ch.to_ascii_lowercase());
    }
    out
}
