//! Creusot companion file generator for `elicitation generate creusot`.
//!
//! Takes a `VsmDescriptor` (produced by the source scanner) and emits a Rust
//! source file containing Creusot `#[requires]`/`#[ensures]` contracts that
//! replace what `VerifiedStateMachine::vsm_creusot_proof()` produces at build time.
//!
//! The generated file follows the pattern in `elicit_proofs/src/creusot/generated/`:
//! 1. `#![allow(unexpected_cfgs)]` — suppress unknown cfg key warnings
//! 2. `#[cfg(creusot)] use` imports (fixed prelude + type-resolved)
//! 3. `#[cfg(creusot)] #[logic] pub fn inv(state) -> bool { <body> }`
//! 4. `#[cfg(creusot)] #[trusted] pub fn verify_*_prop_creusot()` marker
//! 5. Per-transition: `#[cfg(creusot)] #[requires(inv)] #[ensures(inv)] pub fn t_creusot(...)` wrapper

use std::collections::BTreeSet;
use std::path::Path;

use crate::cli::generate::{
    TypeResolver,
    find_crate_name,
    scanner::{ArgKind, TransitionFn, VsmDescriptor},
};

// ─── Public API ───────────────────────────────────────────────────────────────

/// Generate the full Creusot companion file content for `vsm`.
///
/// `crate_root` is used to discover the crate name via `Cargo.toml`.  The VSM
/// source file is parsed with [`TypeResolver`] to produce precise `use` imports
/// rather than glob wildcards.
///
/// Returns `Err` with an actionable message when a named invariant is present
/// but `creusot_inv_body` could not be resolved.
#[tracing::instrument(skip(vsm, crate_root), fields(machine = %vsm.machine))]
pub fn generate_creusot_file(
    vsm: &VsmDescriptor,
    crate_root: impl AsRef<Path>,
) -> Result<String, String> {
    let machine = &vsm.machine;
    let state_ty = machine.replace("Machine", "State");
    let crate_root = crate_root.as_ref();
    let crate_name = find_crate_name(crate_root);

    // Resolve invariant — error only when an invariant exists without a body.
    let inv_parts: Option<(&str, &str, &str)> = match &vsm.invariant {
        Some(p) => {
            let fn_name = p
                .creusot_fn
                .as_deref()
                .unwrap_or_else(|| p.name.as_str());
            let body = p.creusot_inv_body.as_deref().ok_or_else(|| {
                let hint_fn = p.creusot_fn.as_deref().unwrap_or("creusot_invariant_fn");
                format!(
                    "cannot generate Creusot companion for {machine}: \
                     invariant body for `{hint_fn}` not found\n  \
                     hint: add `creusot_inv_body = \"...\"` to #[prop(...)] on `{name}`,\n  \
                        or define `pub fn {hint_fn}(state: &{state_ty}) -> bool {{ ... }}`\n  \
                           in a file under the scan root (without #[cfg(creusot)] gate)",
                    name = p.name,
                )
            })?;
            Some((fn_name, p.name.as_str(), body))
        }
        None => None,
    };

    // ── Collect the bare type names this file will reference ─────────────────
    let mut needed: BTreeSet<String> = BTreeSet::new();
    TypeResolver::collect_type(&state_ty, &mut needed);
    if let Some((_, consistent_ty, _)) = inv_parts {
        TypeResolver::collect_type(consistent_ty, &mut needed);
    }
    for tfn in &vsm.transition_fns {
        for arg in &tfn.args {
            match &arg.kind {
                ArgKind::State => {}
                ArgKind::Proof { inner } => TypeResolver::collect_type(inner, &mut needed),
                _ => TypeResolver::collect_type(&arg.ty, &mut needed),
            }
        }
    }
    let needs_kani_label = inv_parts
        .map(|(_, _, body)| body.contains("kani_label"))
        .unwrap_or(false);

    // ── Resolve imports ───────────────────────────────────────────────────────
    let resolver = TypeResolver::build(&vsm.source_file, &crate_name);
    let resolved_imports = resolver.grouped_imports(&needed);

    let mut lines: Vec<String> = Vec::new();

    // ── Header ──────────────────────────────────────────────────────────────
    lines.push("// AUTO-GENERATED by `elicitation generate creusot` — DO NOT EDIT".to_string());
    lines.push("//".to_string());
    lines.push(format!("// Creusot companion contracts for {machine}."));
    lines.push("// Regenerate: elicitation generate creusot --crate-path <root>".to_string());
    lines.push("//".to_string());
    lines.push(
        "// All items are gated with #[cfg(creusot)]; invisible to normal Rust builds.".to_string(),
    );
    lines.push("// The `creusot` cfg key is set by the Creusot toolchain, not by cargo.".to_string());
    lines.push("#![allow(unexpected_cfgs)]".to_string());
    lines.push(String::new());

    // ── Imports ─────────────────────────────────────────────────────────────
    // Fixed: creusot stdlib prelude and elicitation types.
    let mut fixed_imports = vec![
        "::creusot_std::prelude::*".to_string(),
        "elicitation::Established".to_string(),
    ];
    if needs_kani_label {
        fixed_imports.push("elicitation::kani_label".to_string());
    }
    for import in &fixed_imports {
        lines.push("#[cfg(creusot)]".to_string());
        lines.push(format!("use {import};"));
    }
    // Type-resolved: precise imports for every user-crate type referenced.
    for import in &resolved_imports {
        lines.push("#[cfg(creusot)]".to_string());
        lines.push(format!("use {import};"));
    }
    lines.push(String::new());

    // ── Logic invariant fn + wrappers ────────────────────────────────────────
    if let Some((inv_fn, consistent_ty, inv_body)) = inv_parts {
        lines.push("#[cfg(creusot)]".to_string());
        lines.push("#[logic]".to_string());
        lines.push(format!(
            "pub fn {inv_fn}(state: &{state_ty}) -> bool {{\n    pearlite! {{ {inv_body} }}\n}}"
        ));
        lines.push(String::new());

        // ── Marker proof fn ──────────────────────────────────────────────────
        let snake = to_snake(consistent_ty);
        lines.push("#[cfg(creusot)]".to_string());
        lines.push("#[requires(true)]".to_string());
        lines.push("#[ensures(result)]".to_string());
        lines.push("#[trusted]".to_string());
        lines.push(format!(
            "pub fn verify_{snake}_prop_creusot() -> bool {{ true }}"
        ));
        lines.push(String::new());

        // ── Per-transition call-through wrappers ─────────────────────────────
        for name in &vsm.transitions {
            let tf = vsm.transition_fns.iter().find(|tf| &tf.name == name);
            lines.push(emit_creusot_wrapper(name, &state_ty, consistent_ty, inv_fn, tf));
        }
    }

    Ok(lines.join("\n") + "\n")
}

// ─── Emitters ────────────────────────────────────────────────────────────────

/// Emit one `#[cfg(creusot)] ... pub fn {name}_creusot(...)` call-through wrapper.
fn emit_creusot_wrapper(
    fn_name: &str,
    state_ty: &str,
    consistent_ty: &str,
    inv_fn: &str,
    tf: Option<&TransitionFn>,
) -> String {
    let (params, call_args) = match tf {
        Some(tf) => (emit_params(tf, state_ty), emit_call_args(tf)),
        None => (
            format!("state: {state_ty}, proof: Established<{consistent_ty}>"),
            "state, proof".to_string(),
        ),
    };

    let mut lines: Vec<String> = Vec::new();
    lines.push("#[cfg(creusot)]".to_string());
    lines.push(format!("#[requires({inv_fn}(&state))]"));
    lines.push(format!("#[ensures({inv_fn}(&result.0))]"));
    // `pub` (not `pub(crate)`) avoids spurious `dead_code` warnings under
    // Creusot's compiler, where these functions are used as proof obligations
    // but have no regular Rust call sites.
    lines.push(format!(
        "pub fn {fn_name}_creusot({params}) \
         -> ({state_ty}, Established<{consistent_ty}>) \
         {{ {fn_name}({call_args}) }}"
    ));
    lines.push(String::new());
    lines.join("\n")
}

/// Emit function parameter list: `state: State, proof: Established<T>, extra: Type, ...`
fn emit_params(tf: &TransitionFn, state_ty: &str) -> String {
    let mut parts: Vec<String> = Vec::new();
    for arg in &tf.args {
        let (name, ty) = match &arg.kind {
            ArgKind::State => ("state".to_string(), state_ty.to_string()),
            ArgKind::Proof { inner } => (arg.name.clone(), format!("Established<{inner}>")),
            _ => (arg.name.trim_start_matches('_').to_string(), arg.ty.clone()),
        };
        parts.push(format!("{name}: {ty}"));
    }
    parts.join(", ")
}

/// Emit call argument list: `state, proof, extra, ...`
fn emit_call_args(tf: &TransitionFn) -> String {
    tf.args
        .iter()
        .map(|arg| match arg.kind {
            ArgKind::State => "state".to_string(),
            ArgKind::Proof { .. } => arg.name.clone(),
            _ => arg.name.trim_start_matches('_').to_string(),
        })
        .collect::<Vec<_>>()
        .join(", ")
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/// Convert PascalCase to snake_case.
fn to_snake(s: &str) -> String {
    let mut out = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            out.push('_');
        }
        out.push(ch.to_ascii_lowercase());
    }
    out
}

