//! Kani harness generator for `elicitation generate kani`.
//!
//! Takes a `VsmDescriptor` (produced by the source scanner) and emits a Rust
//! source file containing Kani `proof_for_contract` harnesses that replicate
//! what `VerifiedStateMachine::vsm_kani_proof()` produces at build time.
//!
//! The generated file follows the two-shadow pattern:
//! 1. depth-2 state via `KaniCompose::kani_depth2()` + `kani::assume(inv_fn(&state))` + `mem::forget`
//! 2. depth-0 state via `KaniCompose::kani_depth0()` + proof credential + extra args + call + `mem::forget`

use std::path::Path;

use crate::cli::generate::{find_crate_name, scanner::{ArgKind, TransitionFn, VsmDescriptor}};

// ─── Public API ───────────────────────────────────────────────────────────────

/// Generate the full Kani companion file content for `vsm`.
///
/// `crate_root` is used to discover the crate name via `Cargo.toml` and emit
/// a `use {crate_name}::*` wildcard import alongside `elicitation::Established`.
///
/// Returns a formatted Rust source string (not yet written to disk).
#[tracing::instrument(skip(vsm, crate_root), fields(machine = %vsm.machine))]
pub fn generate_kani_file(vsm: &VsmDescriptor, crate_root: impl AsRef<Path>) -> String {
    let machine = &vsm.machine;
    let inv_fn = vsm
        .invariant
        .as_ref()
        .and_then(|p| p.kani_fn.as_deref())
        .unwrap_or("/* TODO: kani_invariant_fn */");
    let consistent_ty = vsm
        .invariant
        .as_ref()
        .map(|p| p.name.as_str())
        .unwrap_or("/* TODO: ConsistentType */");

    let crate_name = find_crate_name(crate_root.as_ref());

    let mut out = String::new();

    // ── Header ──────────────────────────────────────────────────────────────
    out.push_str(&format!(
        "// AUTO-GENERATED by `elicitation generate kani` — DO NOT EDIT\n\
         //\n\
         // Kani proof_for_contract harnesses for {machine}.\n\
         // Regenerate: elicitation generate kani --crate-path <root>\n\
         \n"
    ));

    // ── Imports ─────────────────────────────────────────────────────────────
    for import in &[
        "elicitation::Established".to_string(),
        format!("{crate_name}::*"),
    ] {
        out.push_str(&format!("#[cfg(kani)]\nuse {import};\n"));
    }
    out.push('\n');

    // ── Marker proof ────────────────────────────────────────────────────────
    out.push_str(&format!(
        "#[cfg(kani)]\n\
         #[kani::proof]\n\
         fn verify_{consistent_lower}_prop_marker() {{\n\
             let established: bool = true;\n\
             assert!(established);\n\
         }}\n",
        consistent_lower = to_snake(consistent_ty)
    ));

    // ── per-transition harnesses ─────────────────────────────────────────────
    if vsm.transition_fns.is_empty() {
        // Fallback: emit minimal placeholder harnesses from names only.
        let state_ty = derive_state_ty(machine);
        for name in &vsm.transitions {
            out.push('\n');
            out.push_str(&emit_minimal_harness(
                name,
                &state_ty,
                consistent_ty,
                inv_fn,
            ));
        }
    } else {
        for tfn in &vsm.transition_fns {
            out.push('\n');
            out.push_str(&emit_harness(tfn, consistent_ty, inv_fn));
        }
    }

    out
}

// ─── Harness emitters ─────────────────────────────────────────────────────────

/// Emit a full `proof_for_contract` harness for a `TransitionFn` with known args.
fn emit_harness(tfn: &TransitionFn, consistent_ty: &str, inv_fn: &str) -> String {
    let fn_name = &tfn.name;
    let closure_name = format!("{fn_name}__kani_closure");

    let state_arg = tfn.state_arg();
    let state_ty = state_arg
        .map(|a| a.ty.as_str())
        .unwrap_or("/* TODO: StateTy */");
    let state_pat = state_arg.map(|a| a.name.as_str()).unwrap_or("_state");

    let call_args: Vec<&str> = tfn.args.iter().map(|a| a.name.as_str()).collect();

    let mut lines: Vec<String> = Vec::new();

    // Shadow 1: depth-2 non-det state + assume invariant + forget.
    lines.push(format!(
        "    let {state_pat}: {state_ty} = <{state_ty} as ::elicitation::KaniCompose>::kani_depth2();"
    ));
    lines.push(format!("    ::kani::assume({inv_fn}(&{state_pat}));"));
    lines.push(format!("    ::std::mem::forget({state_pat});"));

    // Shadow 2: depth-0 state.
    lines.push(format!(
        "    let {state_pat}: {state_ty} = <{state_ty} as ::elicitation::KaniCompose>::kani_depth0();"
    ));

    // Proof credential and extra args.
    for arg in &tfn.args {
        match &arg.kind {
            ArgKind::State => {} // already emitted above
            ArgKind::Proof { inner } => {
                let name = &arg.name;
                lines.push(format!("    let {name}: Established<{inner}> = {{"));
                lines.push(format!(
                    "        let __cred = {inner}::kani_proof_credential();"
                ));
                lines.push("        ::elicitation::Established::prove(&__cred)".to_string());
                lines.push("    };".to_string());
            }
            ArgKind::StringArg => {
                lines.push(format!(
                    "    let {name}: {ty} = ::std::string::String::new();",
                    name = arg.name,
                    ty = arg.ty,
                ));
            }
            ArgKind::VecArg => {
                lines.push(format!(
                    "    let {name}: {ty} = ::std::vec::Vec::new();",
                    name = arg.name,
                    ty = arg.ty,
                ));
            }
            ArgKind::OptionArg => {
                lines.push(format!(
                    "    let {name}: {ty} = ::core::option::Option::None;",
                    name = arg.name,
                    ty = arg.ty,
                ));
            }
            ArgKind::Other => {
                lines.push(format!(
                    "    let {name}: {ty} = <{ty} as ::elicitation::KaniCompose>::kani_depth0();",
                    name = arg.name,
                    ty = arg.ty,
                ));
            }
        }
    }

    let call_arg_str = call_args.join(", ");
    lines.push(format!("    let _result = {fn_name}({call_arg_str});"));
    lines.push("    ::std::mem::forget(_result);".to_string());

    let body = lines.join("\n");
    format!(
        "#[allow(unexpected_cfgs)]\n#[cfg(kani)]\n#[::kani::proof_for_contract({fn_name})]\nfn {closure_name}() {{\n{body}\n}}\n"
    )
}

/// Emit a minimal placeholder harness when function signatures are not available.
fn emit_minimal_harness(
    fn_name: &str,
    state_ty: &str,
    consistent_ty: &str,
    inv_fn: &str,
) -> String {
    let closure_name = format!("{fn_name}__kani_closure");
    let lines = [
        format!("// TODO: verify argument types for {fn_name} and regenerate"),
        "#[allow(unexpected_cfgs)]".to_string(),
        "#[cfg(kani)]".to_string(),
        format!("#[::kani::proof_for_contract({fn_name})]"),
        format!("fn {closure_name}() {{"),
        format!(
            "    let _state: {state_ty} = <{state_ty} as ::elicitation::KaniCompose>::kani_depth2();"
        ),
        format!("    ::kani::assume({inv_fn}(&_state));"),
        "    ::std::mem::forget(_state);".to_string(),
        format!(
            "    let _state: {state_ty} = <{state_ty} as ::elicitation::KaniCompose>::kani_depth0();"
        ),
        format!("    let proof: Established<{consistent_ty}> = {{"),
        format!("        let __cred = {consistent_ty}::kani_proof_credential();"),
        "        ::elicitation::Established::prove(&__cred)".to_string(),
        "    };".to_string(),
        format!("    let _result = {fn_name}(_state, proof);"),
        "    ::std::mem::forget(_result);".to_string(),
        "}".to_string(),
    ];
    lines.join("\n") + "\n"
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/// Infer the state enum type name from the machine struct name.
///
/// `ArchiveConnectionMachine` → `ArchiveConnectionState`
fn derive_state_ty(machine: &str) -> String {
    machine.replace("Machine", "State")
}

/// Convert a PascalCase or camelCase identifier to snake_case for use in fn names.
fn to_snake(s: &str) -> String {
    let mut out = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            out.push('_');
        }
        out.push(ch.to_ascii_lowercase());
    }
    out
}
