//! Verus companion file generator for `elicitation generate verus`.
//!
//! Takes a `VsmDescriptor` (produced by the source scanner) and emits a Rust
//! source file containing Verus `assume_specification` contracts that replace
//! what `VerifiedStateMachine::vsm_verus_proof()` produces at build time.
//!
//! The generated file follows the pattern in `elicit_proofs/src/verus/generated/`:
//! 1. `#[cfg(verus)] use` imports
//! 2. `#[cfg(verus)] verus! { pub open spec fn inv(state) -> bool { <body> } }`
//! 3. `verus! { pub fn verify_*_prop_contract() }` marker
//! 4. Per-transition: `verus! { pub assume_specification [fn_name](...) requires ..., ensures ...; }`

use std::path::Path;

use crate::cli::generate::scanner::{ArgKind, TransitionFn, VsmDescriptor};

// ─── Public API ───────────────────────────────────────────────────────────────

/// Generate the full Verus companion file content for `vsm`.
///
/// `crate_root` is used only for the module path comment; the generated
/// file uses `use elicit_server::...::*` wildcard imports.
#[tracing::instrument(skip(vsm, _crate_root), fields(machine = %vsm.machine))]
pub fn generate_verus_file(vsm: &VsmDescriptor, _crate_root: impl AsRef<Path>) -> String {
    let machine = &vsm.machine;
    let state_ty = machine.replace("Machine", "State");

    let (inv_fn, consistent_ty, inv_body) = match &vsm.invariant {
        Some(p) => (
            p.verus_fn
                .as_deref()
                .unwrap_or("/* TODO: verus_invariant_fn */"),
            p.name.as_str(),
            p.verus_inv_body
                .as_deref()
                .unwrap_or("true /* TODO: verus_inv_body */"),
        ),
        None => (
            "/* TODO: verus_invariant_fn */",
            "/* TODO: ConsistentType */",
            "true",
        ),
    };

    let mut lines: Vec<String> = Vec::new();

    // ── Header ──────────────────────────────────────────────────────────────
    lines.push(format!(
        "// AUTO-GENERATED by `elicitation generate verus` — DO NOT EDIT"
    ));
    lines.push("//".to_string());
    lines.push(format!("// Verus companion contracts for {machine}."));
    lines.push("// Regenerate: elicitation generate verus --crate-path <root>".to_string());
    lines.push("//".to_string());
    lines.push(
        "// All items are gated with #[cfg(verus)]; invisible to normal Rust builds.".to_string(),
    );
    lines.push(String::new());

    // ── Imports ─────────────────────────────────────────────────────────────
    for import in &[
        "::vstd::prelude::*",
        "::verus_builtin_macros::verus",
        "elicitation::Established",
        "elicit_server::archive::vsm::*",
        "elicit_server::archive::types::*",
        "elicit_server::archive::display::*",
        "elicit_server::archive::nav_tree::*",
    ] {
        lines.push(format!("#[cfg(verus)]"));
        lines.push(format!("use {import};"));
    }
    lines.push(String::new());

    // ── Invariant spec fn ────────────────────────────────────────────────────
    lines.push("#[cfg(verus)]".to_string());
    lines.push(format!(
        "verus! {{ pub open spec fn {inv_fn}(state: &{state_ty}) -> bool {{ {inv_body} }} }}"
    ));

    // ── Marker proof ─────────────────────────────────────────────────────────
    lines.push(format!(
        "verus! {{ pub fn verify_{consistent_lower}_prop_contract() \
         -> (result: bool) ensures result == true, {{ true }} }}",
        consistent_lower = to_snake(consistent_ty),
    ));

    // ── Per-transition assume_specifications ─────────────────────────────────
    for name in &vsm.transitions {
        let tf = vsm.transition_fns.iter().find(|tf| &tf.name == name);
        lines.push(emit_assume_specification(
            name,
            &state_ty,
            consistent_ty,
            inv_fn,
            tf,
        ));
    }

    lines.join("\n") + "\n"
}

// ─── Emitters ────────────────────────────────────────────────────────────────

/// Emit one `verus! { pub assume_specification [...] ... ; }` block.
fn emit_assume_specification(
    fn_name: &str,
    state_ty: &str,
    consistent_ty: &str,
    inv_fn: &str,
    tf: Option<&TransitionFn>,
) -> String {
    let args_str = match tf {
        Some(tf) => emit_args(tf),
        None => format!("(_state: {state_ty}, proof: Established<{consistent_ty}>,)"),
    };

    // The state parameter name (strip leading underscore for `requires`/`ensures`).
    let state_param = match tf {
        Some(tf) => tf.state_arg().map(|a| a.name.as_str()).unwrap_or("_state"),
        None => "_state",
    };
    // Verus uses the actual param name in requires/ensures — strip leading `_`.
    let state_ref = state_param.trim_start_matches('_');
    // If the param was named `state` (no underscore prefix) use it directly.
    let state_ref = if state_ref.is_empty() {
        "state"
    } else {
        state_ref
    };

    format!(
        "verus! {{ pub assume_specification [{fn_name}] \
         {args_str} \
         -> (r: ({state_ty}, Established<{consistent_ty}>,)) \
         requires {inv_fn}(&{state_ref}), \
         ensures {inv_fn}(&r.0), \
         ; }}"
    )
}

/// Emit the argument list as a Verus-style parenthesised tuple string.
fn emit_args(tf: &TransitionFn) -> String {
    let mut parts: Vec<String> = Vec::new();
    for arg in &tf.args {
        let ty = match &arg.kind {
            ArgKind::Proof { inner } => format!("Established<{inner}>"),
            _ => arg.ty.clone(),
        };
        parts.push(format!("{}: {ty},", arg.name));
    }
    format!("({})", parts.join(" "))
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/// Convert PascalCase to snake_case.
fn to_snake(s: &str) -> String {
    let mut out = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            out.push('_');
        }
        out.push(ch.to_ascii_lowercase());
    }
    out
}
