//! Drop-in replacement tests for `elicit_reqwest`.
//!
//! These tests verify that `elicit_reqwest` types work identically to their
//! reqwest counterparts at the call site. A `MockHttpClient` generated by
//! mockall proves that generic code written against [`HttpClient`] accepts
//! `elicit_reqwest::Client` without modification.

use elicit_reqwest::{Client, HttpClient, Method, RequestBuilder, Url};
use mockall::mock;
use mockall::predicate::eq;

mock! {
    /// Test double implementing the same [`HttpClient`] contract as the real client.
    pub TestClient {}

    impl HttpClient for TestClient {
        fn request_url(&self, method: Method, url: Url) -> RequestBuilder;
        fn get_url(&self, url: Url) -> RequestBuilder;
        fn post_url(&self, url: Url) -> RequestBuilder;
        fn put_url(&self, url: Url) -> RequestBuilder;
        fn delete_url(&self, url: Url) -> RequestBuilder;
        fn patch_url(&self, url: Url) -> RequestBuilder;
        fn head_url(&self, url: Url) -> RequestBuilder;
    }
}

fn example_url() -> Url {
    "https://example.com/api".parse().expect("valid URL")
}

fn real_builder_for(method: reqwest::Method, url: Url) -> RequestBuilder {
    Client::new().request_url(Method::from(method), url)
}

// ── Real client: verify method wiring ────────────────────────────────────────

#[test]
fn real_client_get_sets_get_method() {
    let url = example_url();
    let builder = Client::new().get_url(url.clone());
    let request = builder.build().expect("valid request");
    assert_eq!(request.method().as_str(), "GET");
    assert_eq!(request.url(), &url);
}

#[test]
fn real_client_post_sets_post_method() {
    let url = example_url();
    let builder = Client::new().post_url(url.clone());
    let request = builder.build().expect("valid request");
    assert_eq!(request.method().as_str(), "POST");
    assert_eq!(request.url(), &url);
}

#[test]
fn real_client_put_sets_put_method() {
    let url = example_url();
    let builder = Client::new().put_url(url.clone());
    let request = builder.build().expect("valid request");
    assert_eq!(request.method().as_str(), "PUT");
    assert_eq!(request.url(), &url);
}

#[test]
fn real_client_delete_sets_delete_method() {
    let url = example_url();
    let builder = Client::new().delete_url(url.clone());
    let request = builder.build().expect("valid request");
    assert_eq!(request.method().as_str(), "DELETE");
    assert_eq!(request.url(), &url);
}

#[test]
fn real_client_patch_sets_patch_method() {
    let url = example_url();
    let builder = Client::new().patch_url(url.clone());
    let request = builder.build().expect("valid request");
    assert_eq!(request.method().as_str(), "PATCH");
    assert_eq!(request.url(), &url);
}

#[test]
fn real_client_head_sets_head_method() {
    let url = example_url();
    let builder = Client::new().head_url(url.clone());
    let request = builder.build().expect("valid request");
    assert_eq!(request.method().as_str(), "HEAD");
    assert_eq!(request.url(), &url);
}

// ── Mock client: verify trait is callable identically ────────────────────────

#[test]
fn mock_client_get_url_records_call() {
    let url = example_url();
    let mut mock = MockTestClient::new();
    mock.expect_get_url()
        .with(eq(url.clone()))
        .times(1)
        .returning(|u| real_builder_for(reqwest::Method::GET, u));

    let builder = mock.get_url(url.clone());
    let request = builder.build().expect("valid request");
    assert_eq!(request.method().as_str(), "GET");
    assert_eq!(request.url(), &url);
}

#[test]
fn mock_client_post_url_records_call() {
    let url = example_url();
    let mut mock = MockTestClient::new();
    mock.expect_post_url()
        .with(eq(url.clone()))
        .times(1)
        .returning(|u| real_builder_for(reqwest::Method::POST, u));

    let builder = mock.post_url(url.clone());
    let request = builder.build().expect("valid request");
    assert_eq!(request.method().as_str(), "POST");
}

#[test]
fn mock_client_request_url_accepts_custom_method() {
    let url = example_url();
    let method = Method::from(reqwest::Method::from_bytes(b"QUERY").expect("valid method"));
    let mut mock = MockTestClient::new();

    let method_clone = method.clone();
    mock.expect_request_url().times(1).returning(move |m, u| {
        real_builder_for(
            reqwest::Method::from_bytes(m.as_str().as_bytes()).expect("valid method"),
            u,
        )
    });

    let builder = mock.request_url(method_clone, url.clone());
    let request = builder.build().expect("valid request");
    assert_eq!(request.url(), &url);
}

// ── Drop-in: generic function works with both real and mock client ────────────

fn fetch_plan(client: &dyn HttpClient, url: Url) -> elicit_reqwest::Request {
    client.get_url(url).build().expect("valid request")
}

#[test]
fn generic_function_accepts_real_client() {
    let url = example_url();
    let client = Client::new();
    let request = fetch_plan(&client, url.clone());
    assert_eq!(request.method().as_str(), "GET");
    assert_eq!(request.url(), &url);
}

#[test]
fn generic_function_accepts_mock_client() {
    let url = example_url();
    let mut mock = MockTestClient::new();
    mock.expect_get_url()
        .times(1)
        .returning(|u| real_builder_for(reqwest::Method::GET, u));

    let request = fetch_plan(&mock, url.clone());
    assert_eq!(request.method().as_str(), "GET");
    assert_eq!(request.url(), &url);
}
