//! Shadow of `bevy::app::PluginGroup` and `PluginGroupBuilder` trenchcoat.
//!
//! [`PluginGroup`] is a shadow Rust trait generated by `#[reflect_trait]` with
//! `shadow_trait`.  Downstream code implements `PluginGroup` instead of
//! `bevy::app::PluginGroup`, then calls `impl_bevy__app__plugin_group!(Type)` to
//! generate the real Bevy impl.
//!
//! [`PluginGroupBuilder`] is a trenchcoat newtype around
//! `bevy::app::PluginGroupBuilder`.  Because the builder is stateful and
//! `!Clone`, serialization round-trips create a fresh `DefaultPlugins` builder.
//!
//! # Factory
//!
//! Use [`prime_bevy__app__plugin_group`] at server startup to register a type
//! that implements `PluginGroup + ElicitComplete` with the dynamic tool registry.

use bevy::app::PluginGroup as BevyPluginGroup;
use elicitation_derive::reflect_trait;

// ── PluginGroupBuilder trenchcoat ─────────────────────────────────────────────

/// Shadow of `bevy::app::PluginGroupBuilder`.
///
/// Wraps Bevy's plugin group builder so it can cross the `type_map` boundary
/// in shadow trait signatures.  The inner value is the authoritative builder;
/// serialization round-trips produce a fresh `DefaultPlugins` builder because
/// `bevy::app::PluginGroupBuilder` has no stable serialized form.
pub struct PluginGroupBuilder(pub bevy::app::PluginGroupBuilder);

impl std::fmt::Debug for PluginGroupBuilder {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("PluginGroupBuilder").finish_non_exhaustive()
    }
}

impl Clone for PluginGroupBuilder {
    /// Returns a fresh `DefaultPlugins` builder; state is not preserved.
    ///
    /// Matches the round-trip behaviour of `Deserialize`, so no information is
    /// lost beyond what serialisation already discards.
    fn clone(&self) -> Self {
        Self(bevy::DefaultPlugins.build())
    }
}

impl From<bevy::app::PluginGroupBuilder> for PluginGroupBuilder {
    fn from(b: bevy::app::PluginGroupBuilder) -> Self {
        Self(b)
    }
}

impl From<PluginGroupBuilder> for bevy::app::PluginGroupBuilder {
    fn from(b: PluginGroupBuilder) -> Self {
        b.0
    }
}

impl serde::Serialize for PluginGroupBuilder {
    /// Serializes as `{}`.  `bevy::app::PluginGroupBuilder` carries runtime
    /// state that has no meaningful JSON representation.
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeMap;
        serializer.serialize_map(Some(0))?.end()
    }
}

impl<'de> serde::Deserialize<'de> for PluginGroupBuilder {
    /// Deserializes from any map object by constructing a fresh
    /// `DefaultPlugins` builder.
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        use serde::de::{MapAccess, Visitor};
        struct V;
        impl<'de> Visitor<'de> for V {
            type Value = PluginGroupBuilder;
            fn expecting(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "an empty object {{}} for a PluginGroupBuilder handle")
            }
            fn visit_map<A: MapAccess<'de>>(
                self,
                mut map: A,
            ) -> Result<PluginGroupBuilder, A::Error> {
                while map.next_entry::<String, serde::de::IgnoredAny>()?.is_some() {}
                Ok(PluginGroupBuilder(bevy::DefaultPlugins.build()))
            }
        }
        deserializer.deserialize_map(V)
    }
}

impl schemars::JsonSchema for PluginGroupBuilder {
    fn schema_name() -> std::borrow::Cow<'static, str> {
        std::borrow::Cow::Borrowed("PluginGroupBuilder")
    }
    fn json_schema(_gen: &mut schemars::SchemaGenerator) -> schemars::Schema {
        schemars::json_schema!({ "type": "object" })
    }
}

// ── PluginGroup shadow trait ──────────────────────────────────────────────────

/// Expose [`bevy::app::PluginGroup`] as a shadow Rust trait + MCP tools.
///
/// The `shadow_trait` flag generates:
/// - A `PluginGroup` trait using `crate::PluginGroupBuilder` in all signatures
///   (drop-in for `bevy::app::PluginGroup`)
/// - `impl_bevy__app__plugin_group!(Type)` — generates `impl bevy::app::PluginGroup for Type`
///   by bridging from the shadow trait
/// - MCP tool factories for `build` and `name`
#[reflect_trait(bevy::app::PluginGroup,
    type_map(bevy::app::PluginGroupBuilder => crate::PluginGroupBuilder),
    shadow_trait)]
pub trait PluginGroupTools {
    /// Build the group into a [`PluginGroupBuilder`].
    fn build(self) -> bevy::app::PluginGroupBuilder;
    /// Returns the canonical name for this plugin group.
    fn name() -> String {
        ::std::any::type_name::<Self>().to_string()
    }
}

// ── DefaultPlugins ────────────────────────────────────────────────────────────

/// Shadow of `bevy::DefaultPlugins`.
///
/// Implements the shadow [`PluginGroup`] trait.  Use
/// `impl_bevy__app__plugin_group!(DefaultPlugins)` is called here so that
/// `bevy::app::PluginGroup` is also implemented, letting this type be passed
/// wherever Bevy expects a plugin group.
#[derive(Debug, Clone)]
pub struct DefaultPlugins;

impl serde::Serialize for DefaultPlugins {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeMap;
        serializer.serialize_map(Some(0))?.end()
    }
}

impl<'de> serde::Deserialize<'de> for DefaultPlugins {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        use serde::de::{IgnoredAny, MapAccess, Visitor};
        struct V;
        impl<'de> Visitor<'de> for V {
            type Value = DefaultPlugins;
            fn expecting(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "an empty object {{}} for DefaultPlugins")
            }
            fn visit_map<A: MapAccess<'de>>(self, mut map: A) -> Result<DefaultPlugins, A::Error> {
                while map.next_entry::<String, IgnoredAny>()?.is_some() {}
                Ok(DefaultPlugins)
            }
        }
        deserializer.deserialize_map(V)
    }
}

impl schemars::JsonSchema for DefaultPlugins {
    fn schema_name() -> std::borrow::Cow<'static, str> {
        std::borrow::Cow::Borrowed("DefaultPlugins")
    }
    fn json_schema(_gen: &mut schemars::SchemaGenerator) -> schemars::Schema {
        schemars::json_schema!({ "type": "object" })
    }
}

impl PluginGroup for DefaultPlugins {
    fn build(self) -> PluginGroupBuilder {
        PluginGroupBuilder(bevy::DefaultPlugins.build())
    }

    fn name() -> String {
        "DefaultPlugins".to_string()
    }
}

impl_bevy__app__plugin_group!(DefaultPlugins);
