//! Kani proof harnesses for archive VSMs.
//!
//! Generated harnesses live in `generated/` (auto-generated by `build.rs`).
//! Add hand-written harnesses as additional modules alongside the generated ones.

pub mod generated;
pub mod diag;
pub mod composition;
pub mod suite;
