//! Kani proof harnesses for archive VSMs.
//!
//! Generated harnesses live in `generated/` (auto-generated by `build.rs`).
//! Add hand-written harnesses as additional modules alongside the generated ones.

#[cfg(feature = "kani")]
pub mod composition;
#[cfg(feature = "kani")]
pub mod diag;
#[cfg(feature = "kani")]
pub mod gallery;
pub mod generated;
#[cfg(feature = "kani")]
pub mod suite;
