//! `elicit_temporal` — Temporal contract interface crate.
//!
//! Provides a standards-anchored vocabulary of temporal propositions (`contracts`)
//! for date, time, offset, and timestamp interchange across producer and
//! consumer crates, plus neutral descriptors (`types`), descriptor-oriented
//! runtime seams, and associated native-carrier trait families (`traits`) that
//! exchange `Established<P>` proof sidecars.
//!
//! # Design
//!
//! This crate is an interface layer, not an implementation. Temporal producers
//! such as `elicit_time`, `elicit_chrono`, and `elicit_jiff` can establish these
//! propositions; downstream consumers can require them without coupling to a
//! particular datetime backend.
//!
//! The current implementation remains contract-first, but now includes an
//! initial runtime seam: neutral temporal descriptors, a crate-local
//! `TemporalError`/`TemporalResult`, descriptor-oriented parser, formatter,
//! zone, conversion, interval, and reporter traits, and native associated-type
//! families for backend-owned temporal carriers.

#![forbid(unsafe_code)]
#![warn(missing_docs)]

mod contracts;
mod error;
mod traits;
mod types;

pub use contracts::{
    ApproximationQualificationDeclared, BackendConversionEvidence, BackendConversionSemanticsValid,
    BasicFormatUsesMinimumComponentsForRequiredAccuracy, BeforeOrAfterQualificationIsLevelTwoOnly,
    BeforeOrOnDateUsesLeadingDoubleDotQualifier, BeforeYearOneValueUsesTrailingBSuffix,
    CalendarDateEvidence, CalendarDateHasYearMonthDay, CalendarDateUsesGregorianCalendar,
    CalendarDateValid, CalendarDayDurationMayBeModifiedByLeapSecondsOrLocalTimeShifts,
    CalendarDayIsIntervalOfSingleCalendarDateAdvance, CalendarDayWithinMonthBounds,
    CalendarMonthInRangeOneToTwelve, CalendarMonthIsNamedIntervalWithinCalendarYear,
    CalendarWeekIsSevenDayIntervalBeginningOnMonday, CalendarWeekNumberUsesFirstThursdayRule,
    CalendarWeekStartsOnMonday, CalendarYearInRangeZeroToNineThousandNineHundredNinetyNine,
    CalendarYearIsIntervalOfSuccessiveCalendarMonths,
    CalendarYearThrough1582RequiresMutualAgreement, CentennialYearDivisibleByOneHundred,
    CenturyEvidence, CenturyOrdinalInRangeZeroToNinetyNine, CenturyValid,
    ColonSeparatesTimeComponents, CombinedDateTimeDateComponentMustNotUseReducedAccuracy,
    CombinedDateTimeDateEvidence, CombinedDateTimePermitsCalendarDateComponent,
    CombinedDateTimePermitsOrdinalDateComponent, CombinedDateTimePermitsWeekDateComponent,
    CombinedDateTimeUsesSingleFormatAcrossDateAndTimeComponents,
    CombinedDateTimeUsesTimeDesignator, CommonYearHasThreeHundredSixtyFiveCalendarDays,
    CompleteDateEvidence, CompleteDurationEndIntervalSubstitutionEvidence,
    CompleteIntervalCalendarDateMayBeSubstitutedByOrdinalDate,
    CompleteIntervalCalendarDateMayBeSubstitutedByWeekDate,
    CompleteIntervalDurationMaySubstituteWeekForm, CompleteIntervalDurationRepresentationEvidence,
    CompleteIntervalLocalTimeMayBeSubstitutedByLocalTimeAndUtcDifference,
    CompleteIntervalLocalTimeMayBeSubstitutedByUtcOfDay,
    CompleteIntervalSubstitutionSemanticsValid, CompleteRecurringIntervalRepresentationEvidence,
    CompleteRecurringIntervalRepresentationSemanticsValid,
    CompleteRepresentationCarriesAllRequiredComponents,
    CompleteStartDurationIntervalSubstitutionEvidence,
    CompleteStartEndIntervalSubstitutionEvidence, CompleteTimePointDateRepresentationEvidence,
    CompleteTimePointRepresentationEvidence, CompleteTimePointTimeRepresentationEvidence,
    ComponentQualificationAppliesOnlyToMarkedComponent,
    ComponentQualificationUsesImmediateLeftPlacement, ContextDependentDurationSemanticsDeclared,
    ConversionDropsNamedZoneIdentity, ConversionDropsSubsecondPrecision, ConversionLossless,
    ConversionPreservesRepresentedInstant, ConversionPreservesTemporalOrdering,
    ConversionRequiresExplicitAuthorityWhenLossy, ConversionSourceSemanticKindDeclared,
    ConversionTargetSemanticKindDeclared, ConversionTruncatesSubseconds,
    CriticalTimeZoneInconsistencyEvidence, CriticalTimeZoneInconsistencyHandlingValid,
    CriticalTimeZoneSuffixInconsistencyRequiresAction, DateEvidence,
    DateIdentifiesPositionWithinCalendar,
    DateTimeFormatRepresentationDescribesRepresentationFamily,
    DateTimeFormatRepresentationsForbiddenInTelexRepertoire,
    DateTimeFormulaCombinesTemporalValueWithDuration, DateTimeFormulaEvaluationModeDeclared,
    DateTimeFormulaEvaluationResultEvidence, DateTimeFormulaEvaluationResultValid,
    DateTimeFormulaEvaluationSemanticsEvidence, DateTimeFormulaEvaluationSemanticsValid,
    DateTimeFormulaEvidence, DateTimeFormulaTruncatesAtComponentBoundaries,
    DateTimeFormulaUsesCarryOverSemantics, DateTimeFormulaValid,
    DateTimeRepresentationIdentifiesPointIntervalOrRecurrence, DateValid, DateWithShiftEvidence,
    DateWithShiftValid, DayDurationMaySpanSameTimeOfDayOnAdjacentCalendarDays,
    DayEqualsTwentyFourHours, DecadeEvidence, DecadeOrdinalInRangeZeroToNineHundredNinetyNine,
    DecadeValid, DecimalRepresentationUsesLowestOrderComponentFraction,
    DurationAlternativeFormCarriesCompleteCalendarAndClockComponents,
    DurationAlternativeFormEvidence, DurationAlternativeFormRequiresPartnerAgreement,
    DurationAlternativeFormUsesDateAndTimeComponentSlots, DurationDesignatorRepresentationEvidence,
    DurationEqualsDifferenceBetweenIntervalEndpoints, DurationFormEvidence, DurationFormValid,
    DurationRepresentationEvidence, DurationRepresentationSemanticsValid,
    DurationTimeComponentsFollowTimeDesignator, DurationUsesPeriodDesignator,
    DurationWeekFormEvidence, DurationWeekFormNotMixedWithCalendarOrClockUnits,
    DurationWeekFormUsesSingleWeekUnit, ElectiveTimeZoneInconsistencyEvidence,
    ElectiveTimeZoneInconsistencyHandlingValid, ElectiveTimeZoneSuffixInconsistencyMayBeHandled,
    EndOfDayTwentyFourHourAllowedOnlyWithinIntervalOrRecurrence,
    EndOfDayTwentyFourHourForbiddenForSingleTimePoint, EnhancedIntervalLevelOneEvidence,
    EnhancedIntervalLevelOnePermitsTerminalBoundaryQualification,
    EnhancedIntervalLevelOneSemanticsValid, EnhancedIntervalLevelTwoEvidence,
    EnhancedIntervalLevelTwoPermitsBeforeOrAfterBoundaryQualification,
    EnhancedIntervalLevelTwoPermitsInternalBoundaryQualification,
    EnhancedIntervalLevelTwoPermitsInternalBoundaryUnspecifiedDigits,
    EnhancedIntervalLevelTwoSemanticsValid, ExactDurationSemanticsDeclared,
    ExpandedRepresentationRequiresAdditionalAgreement, ExplicitDateTimeEvidence,
    ExplicitDateTimeTimePortionMayBeReducedPrecision,
    ExplicitDateTimeUsesDateThenTimeConcatenation, ExplicitDateTimeValid,
    ExplicitDateTimeWithShiftEvidence, ExplicitDateTimeWithShiftUsesDateTimeThenShiftConcatenation,
    ExplicitDateTimeWithShiftValid, ExplicitDateWithShiftUsesDateThenShiftConcatenation,
    ExplicitDurationCompositeRepresentationDeclared, ExplicitDurationEvidence,
    ExplicitDurationMayBeNegative, ExplicitDurationMayUseFractionalLowestOrderUnit,
    ExplicitDurationPrecedenceRepresentationCarriesEvaluationOrder,
    ExplicitDurationRepresentationEvidence, ExplicitDurationRepresentationKindDeclared,
    ExplicitDurationSemanticEvidence, ExplicitDurationUsesDurationalUnitDesignators,
    ExplicitDurationValid, ExplicitIntervalDurationSubstitutionEvidence,
    ExplicitIntervalDurationSubstitutionSemanticsValid,
    ExplicitIntervalEndComponentInheritanceEvidence,
    ExplicitIntervalEndComponentInheritanceSemanticsValid,
    ExplicitIntervalShiftPropagationEvidence, ExplicitIntervalShiftPropagationSemanticsValid,
    ExplicitTemporalFormEvidence, ExplicitTemporalFormMayOmitZeroValuedComponents,
    ExplicitTemporalFormUsesDesignatorSymbols, ExplicitTemporalFormValid,
    ExplicitTemporalPrecisionUsesLowestDenotedComponent,
    ExplicitTimeIntervalDurationSubstitutionInfersMissingBoundary, ExplicitTimeIntervalEvidence,
    ExplicitTimeIntervalLeadingShiftAppliesToTrailingComponentUnlessOverridden,
    ExplicitTimeIntervalTrailingEndMayInheritHigherOrderComponents,
    ExplicitTimeIntervalUsesDateTimeEndpointFamily, ExplicitTimeIntervalValid,
    ExplicitTimeOfDayEvidence, ExplicitTimeOfDayForbidsEndOfDayRepresentation,
    ExplicitTimeOfDayUsesHourMinuteSecondUnitDesignators, ExplicitTimeOfDayUsesTimeDesignator,
    ExplicitTimeOfDayValid, ExplicitTimeOfDayWithShiftUsesTimeThenShiftConcatenation,
    ExplicitTimeShiftBareZuluRepresentsUtcZero, ExplicitTimeShiftEvidence,
    ExplicitTimeShiftPayloadUsesExplicitTimeOfDay,
    ExplicitTimeShiftUsesLeadingMinusOnlyWhenBehindUtc, ExplicitTimeShiftUsesZuluDesignator,
    ExplicitTimeShiftValid, ExplicitUtcRelationshipUsesZuluOrSignedShift,
    ExponentialYearExponentIsPositiveInteger, ExponentialYearUsesPowerOfTenNotation,
    ExtendedIntervalBoundaryEvidence, ExtendedIntervalBoundarySemanticsValid,
    ExtendedYearBaseEvidence, ExtendedYearEvidence, ExtendedYearSignificantDigitsEvidence,
    ExtendedYearValid, FixedInstantEvidence, FixedWidthComponentsRequireLeadingZeros,
    FormatRepresentationUsesPlaceholderCharactersForDigitsAndSigns,
    FractionAppliesToLowestOrderComponent, FractionUsesDecimalSign,
    FractionalSecondDigitsAreContiguous, FractionalSecondPrecisionDeclared,
    GregorianLeapYearUsesDivisibleByFourAndFourHundredException,
    GroupQualificationAppliesToMarkedAndMoreSignificantComponents,
    GroupQualificationUsesImmediateRightPlacement,
    GroupedTimeScaleUnitCarriesOneOrMoreDurationUnits, GroupedTimeScaleUnitConvertsToTimeInterval,
    GroupedTimeScaleUnitDateTimeMayCarryExplicitTimeShift,
    GroupedTimeScaleUnitDefinitionIsContinuous, GroupedTimeScaleUnitEvidence,
    GroupedTimeScaleUnitLowerOrderUnitsRemainWithinGroupBounds,
    GroupedTimeScaleUnitTruncatesOutOfBoundsRemainder, GroupedTimeScaleUnitUsesGroupingDesignators,
    GroupedTimeScaleUnitValid, GroupedTimeScaleUnitValueCarriesExplicitCoefficient,
    HourEqualsSixtyMinutes, HourInRangeZeroToTwentyFour, HyphenSeparatesDateComponents,
    InheritedIntervalEndComponentsEvidence, InheritedIntervalEndComponentsSemanticsValid,
    InheritedIntervalZoneEvidence, InheritedIntervalZoneSemanticsValid, InstantIsPointOnTimeAxis,
    IntervalDurationIsNonNegative, IntervalEndOmittedHigherOrderComponentsInheritFromStart,
    IntervalEndpointOrderingEvidence, IntervalEndpointsOrdered, IntervalStartPrecedesEnd,
    IntervalTrailingComponentInheritsZoneOrUtcFromLeadingComponentWhenOmitted,
    Iso8601BasicFormUsesCompactRepresentation, Iso8601ExtendedFormUsesSeparators,
    IxdtfAdditionalInformationEvidence, IxdtfAdditionalInformationSemanticsValid,
    IxdtfCalendarAnnotationDeclaresPreferredPresentationCalendar, IxdtfCalendarAnnotationPresent,
    IxdtfCalendarAwareTimestampEvidence, IxdtfCalendarKeyRegistryEvidence,
    IxdtfCalendarKeyRegistrySemanticsValid, IxdtfCalendarKeyUsesUCa,
    IxdtfCalendarValueUsesUnicodeCalendarIdentifier,
    IxdtfCriticalFlagIsLeadingExclamationWhenPresent,
    IxdtfCriticalSuffixTagsRequireProcessingOrErrorHandling,
    IxdtfDuplicateElectiveSuffixUsesFirstOccurrence,
    IxdtfExperimentalSuffixKeysAreNotForInterchange, IxdtfExperimentalSuffixKeysCannotBeRegistered,
    IxdtfExperimentalSuffixKeysUseLeadingUnderscore,
    IxdtfExpertReviewAscertainsBasicSpecificationExists,
    IxdtfExpertReviewReservesConciseGenerallyApplicableKeys,
    IxdtfExpertsMayInitiateRegistrationToAvoidFutureCollisions, IxdtfGeneratorsMayOmitSuffixTags,
    IxdtfPermanentEntriesUseSpecificationRequiredPolicy,
    IxdtfPermanentRegisteredSuffixKeyRequiresFullSpecificationReference,
    IxdtfPermanentSuffixKeyRegistrationEvidence, IxdtfPermanentSuffixKeyRegistrationSemanticsValid,
    IxdtfProvisionalEntriesUseExpertReviewPolicy,
    IxdtfProvisionalRegisteredSuffixKeyReferenceExpectedToImproveOverTime,
    IxdtfProvisionalRegisteredSuffixKeyRequiresReferenceInformation,
    IxdtfProvisionalSuffixKeyRegistrationEvidence,
    IxdtfProvisionalSuffixKeyRegistrationSemanticsValid,
    IxdtfRecipientsMayIgnoreElectiveSuffixTags,
    IxdtfRecipientsMustRejectUnconfiguredExperimentalSuffixKeys,
    IxdtfRegisteredSuffixKeyCarriesChangeController, IxdtfRegisteredSuffixKeyCarriesDescription,
    IxdtfRegisteredSuffixKeyCarriesKeyIdentifier, IxdtfRegisteredSuffixKeyCarriesReference,
    IxdtfRegisteredSuffixKeyCarriesRegistrationStatus,
    IxdtfRegisteredSuffixKeyStatusIsProvisionalOrPermanent, IxdtfRegistryInitiallyContainsUCaEntry,
    IxdtfSerializationCarriesNamedZoneAnnotation, IxdtfSuffixFollowsRfc3339Timestamp,
    IxdtfSuffixKeyRegistryEntryEvidence, IxdtfSuffixKeyRegistryEntryValid,
    IxdtfSuffixKeyRegistryPolicyEvidence, IxdtfSuffixKeyRegistryPolicySemanticsValid,
    IxdtfSuffixKeysAreLowercase, IxdtfSuffixTagsUseBracketedKeyValueForm,
    IxdtfSuffixValuesAreCaseSensitiveUnlessOtherwiseSpecified,
    IxdtfSuffixValuesUseHyphenDelimitedItems, IxdtfTimeZoneSuffixUsesBracketedNameOrOffset,
    IxdtfTimestampEvidence, IxdtfTimestampHasPreferredPresentationCalendar, IxdtfTimestampValid,
    IxdtfUCaRegistryEntryIsPermanent, IxdtfUCaRegistryEntryReferencesSectionFive,
    IxdtfUCaRegistryEntryUsesIetfChangeController,
    IxdtfUCaRegistryEntryUsesPreferredCalendarForPresentationDescription, KnownUtcOffsetEvidence,
    LeapDayOccursOnlyInLeapYear, LeapSecondOccursOnlyAtUtcBoundary,
    LeapYearHasThreeHundredSixtySixCalendarDays,
    LetterPrefixedCalendarYearMagnitudeExceedsFourDigits,
    LetterPrefixedCalendarYearUsesLeadingYDesignator,
    LevelOneUnspecifiedDigitsOccupyRightmostPositions,
    LevelTwoUnspecifiedDigitsMayAppearWithinComponent,
    LiteralFormatCharactersCopyIntoRepresentations, LocalDateTimeDoesNotIdentifyFixedInstant,
    LocalDateTimeEvidence, LocalDateTimeMayBeAmbiguousAtZoneTransition,
    LocalDateTimeMayFallInZoneTransitionGap, LocalDateTimeRequiresZoneOrOffsetForInstant,
    LocalDateTimeValid, LocalTimeEvidence, LocalTimeHasHourMinuteSecond,
    LocalTimeRequiresTimeDesignatorWhenContextAmbiguous, LocalTimeScaleEvidence,
    LocalTimeScaleMayBeStandardOrNonUtcBased, LocalTimeScaleValid, LocalTimeSemanticsEvidence,
    LocalTimeSemanticsValid, LocalTimeUsesLocallyApplicableTimeScale, LocalTimeValid,
    LocalTimestampSemanticsEvidence, LosslessConversionEvidence, LossyConversionAuthorityEvidence,
    LossyConversionAuthorityValid, MinuteEqualsSixtySeconds, MinuteInRangeZeroToFiftyNine,
    MonthDurationInRangeTwentyEightToThirtyOneCalendarDays,
    MonthDurationMayRequireAgreedEndingCalendarDay,
    MonthMayBeConsideredThirtyCalendarDaysInCertainApplications, MutualAgreementAuthorityEvidence,
    MutualAgreementAuthorityScopeEvidence, MutualAgreementAuthorityValid,
    NamedTimeZoneAnnotationPresent, NamedTimeZoneIdentifierExcludesDotSegments,
    NamedTimeZoneIdentifierIsCaseSensitive, NamedTimeZoneIdentityEvidence,
    NamedTimeZoneIdentityValid, NamedTimeZoneInterpretationTracksTzdbRevision,
    NamedTimeZoneIsNotNumericOffsetAlias, NamedTimeZoneMeaningUsesCurrentTzdbRules,
    NamedTimeZoneRetainsCivilRuleIdentity, NamedTimeZoneRevisionEvidence,
    NamedTimeZoneUsesIanaIdentifier, NamedZoneAttachmentEvidence,
    NegativeCalendarYearUsesLeadingMinusSign, NominalDayDurationMayDifferFromExactElapsedTime,
    NominalDurationDependsOnCalendarContext, NominalMonthDurationDependsOnCalendarContext,
    NominalWeekDurationIsDistinctFromExactElapsedTime, NominalYearDurationDependsOnCalendarContext,
    NumericOffsetDoesNotIdentifyNamedZone, OffsetConsistencyEvidence,
    OffsetConsistentWithNamedZone, OffsetDateTimeEvidence, OffsetDateTimeIdentifiesSingleInstant,
    OffsetDateTimeValid, OffsetOnlySemanticsEvidence, OffsetOnlyZoneSemanticsLimited,
    OffsetTimeZoneAnnotationConsistentWithTimestamp, OffsetTimeZoneAnnotationEvidence,
    OffsetTimeZoneAnnotationPresent, OffsetTimeZoneMustNotBeSynthesizedFromTimestampOffset,
    OffsetTimeZoneRepeatsTimestampOffset, OffsetTimeZoneUseIsStronglyDiscouraged,
    OnOrAfterDateUsesTrailingDoubleDotQualifier, OpenIntervalBoundaryDeclared, OrdinalDateEvidence,
    OrdinalDateHasYearAndDayOfYear, OrdinalDateValid, OrdinalDayInRangeOneToThreeHundredSixtySix,
    OrdinalDayOfYearUsesThreeDigits, OtherThanCompleteRecurringIntervalRepresentationEvidence,
    OtherThanCompleteRecurringIntervalRepresentationSemanticsValid, PrecisionPreservationEvidence,
    PrecisionPreserved, PrecisionReductionDeclared,
    ProlepticGregorianDatesBefore1583RequireMutualAgreement, QualificationPlacementEvidence,
    QualificationScopeDeclared, QualifiedTemporalExpressionEvidence,
    QualifiedTemporalExpressionValid, QualifiedTemporalValueEvidence, QualifiedTemporalValueValid,
    RecurringIntervalCarriesIntervalComponent, RecurringIntervalCountIsNonNegativeWhenBounded,
    RecurringIntervalEvidence, RecurringIntervalFormValid,
    RecurringIntervalOmittedCountDenotesUnboundedOccurrences,
    RecurringIntervalUsesCompleteTimeIntervalRepresentation,
    RecurringIntervalUsesOtherThanCompleteTimeIntervalRepresentation,
    RecurringIntervalUsesRepeatDesignator, RecurringIntervalWithRepeatRuleEvidence,
    RecurringIntervalWithRepeatRuleUsesCompleteRepresentation,
    RecurringIntervalWithRepeatRuleValid, ReducedAccuracyLocalTimeUsesHourMinuteRepresentation,
    ReducedAccuracyLocalTimeUsesHourOnlyRepresentation,
    ReducedAccuracyRepresentationOmitsLowerOrderComponents,
    ReducedAccuracyWeekDateOmitsWeekdayComponent, ReducedCalendarDateEvidence,
    ReducedCalendarDateHasYearComponent, ReducedCalendarDateOmitsLowerOrderDigitsFromExtremeRight,
    ReducedCalendarDatePrecisionEvidence, ReducedCalendarDateUsesYearMonthRepresentation,
    ReducedCalendarDateUsesYearOnlyRepresentation, ReducedCalendarDateValid,
    ReducedLocalTimeEvidence, ReducedLocalTimePrecisionEvidence, ReducedLocalTimeValid,
    RepeatRuleDeclaresEligibleTimeIntervals,
    RepeatRuleEvaluationInheritsInitialStartComponentInformation, RepeatRuleEvidence,
    RepeatRuleSelectionAppliesWithinEligibleIntervals, RepeatRuleUsesFrequencyDesignator,
    RepeatRuleValid, Rfc3339ApplicationsMayAllowSpaceDateTimeSeparator,
    Rfc3339ClientsShouldTransformDatesForLocalityDisplay, Rfc3339DisplayGuidanceEvidence,
    Rfc3339DisplayGuidanceValid, Rfc3339FractionUsesDotSeparator,
    Rfc3339FractionalSecondsAreOnlyRarelyUsedOption, Rfc3339GenerationGuidanceEvidence,
    Rfc3339GenerationGuidanceValid, Rfc3339GeneratorsShouldUseUppercaseTAndZ,
    Rfc3339LeapSecondGenerationRequiresPriorAnnouncement, Rfc3339LexicalOrderingEvidence,
    Rfc3339LexicalOrderingRequiresUniformFractionalSecondDigits,
    Rfc3339LexicalOrderingRequiresUniformUtcRelationshipEncoding,
    Rfc3339LexicalOrderingSemanticsValid, Rfc3339LocalOffsetNotUnknown,
    Rfc3339LocalityDisplayMayTranslateUtcToLocalTime, Rfc3339OffsetIsUtcOrNumeric,
    Rfc3339PositiveZeroOffsetDeclaresPreferredUtcReferencePoint,
    Rfc3339ProfileMakesMostFieldsAndPunctuationMandatory, Rfc3339RequiresUtcRelationship,
    Rfc3339TimestampEvidence, Rfc3339TimestampExcludesRedundantWeekdayInformation,
    Rfc3339TimestampValid, Rfc3339UnknownLocalOffsetUsesZuluDesignator,
    Rfc3339UnqualifiedLocalTimeForbidden, Rfc3339UsesExtendedCalendarDate,
    Rfc3339UsesFourDigitYear, Rfc3339UsesFullTime, RoundingModeDeclared,
    SeasonCodeDeclaresNamedSeason, SeasonCodeDeclaresSeasonScope,
    SeasonalExpressionUsesSeasonCodeInMonthSlot, SeasonalExpressionUsesYearAndSeasonForm,
    SeasonalTemporalExpressionEvidence, SeasonalTemporalExpressionValid, SecondInRangeZeroToSixty,
    SecondIsBaseUnitForExpressingDuration, SecondIsSiBaseUnitOfTime, SelectionExpressionEvidence,
    SelectionExpressionMaySelectSingleInstance,
    SelectionExpressionUsesRecognizedSelectionRuleVocabulary,
    SelectionExpressionUsesSelectionDelimiters, SelectionExpressionValid,
    SelectionRuleDayOfMonthUsesDayExpression, SelectionRuleHourUsesHourExpression,
    SelectionRuleMinuteUsesMinuteExpression, SelectionRuleMonthUsesMonthExpression,
    SelectionRuleOrdinalDayOfYearUsesOrdinalDayExpression, SelectionRulePositionAppliesLast,
    SelectionRulePositionUsesInstanceDesignatorSuffix, SelectionRuleSecondUsesSecondExpression,
    SelectionRuleWeekDayUsesDayOfWeekExpression, SelectionRuleWeekUsesWeekExpression,
    SelectionRulesApplyWithinSelectedResults, SelectionWithDurationUsesDurationSuffix,
    SerializationCarriesExplicitUtcRelationship, SerializationProfileDeclared,
    SignificantDigitYearCountIsPositiveInteger, SignificantDigitYearUsesTrailingSSuffix,
    SpaceForbiddenUnlessExplicitlyPermitted, SpeculativeDurationSemanticsDeclared,
    StandardTimeDerivedFromUtcByLocalShift, StandardTimeEvidence, StandardTimeOfDayEvidence,
    StandardTimeOfDayUsesStandardTimeScale, StandardTimeOfDayValid, StandardTimeValid,
    SubYearGroupingCodeDeclaresQuadrimester, SubYearGroupingCodeDeclaresQuarter,
    SubYearGroupingCodeDeclaresSemestral, SubYearGroupingExpressionEvidence,
    SubYearGroupingExpressionUsesGroupingCodeInMonthSlot,
    SubYearGroupingExpressionUsesYearAndGroupingForm, SubYearGroupingExpressionValid,
    SubYearGroupingKindEvidence, SubsecondDigitsPreserved, SubsecondTruncationEvidence,
    TemporalChoiceSetUsesSquareBrackets, TemporalInclusiveSetUsesCurlyBraces,
    TemporalOrderingEvidence, TemporalOrderingPreserved, TemporalSetCarriesMultipleMembers,
    TemporalSetDeclaresAlternativeSemantics, TemporalSetDeclaresInclusiveMemberSemantics,
    TemporalSetExpressionEvidence, TemporalSetExpressionValid,
    TemporalSetForbidsInternalWhitespace, TemporalSetMemberSeparatorDeclared,
    TemporalSetOpenRangeUsesBoundaryDoubleDot, TemporalSetRangeNeighborhoodSharesPrecision,
    TemporalSetRangeSemanticsEvidence, TemporalSetRangeSemanticsValid,
    TemporalSetRangeUsesInclusiveDoubleDotSemantics, TimeAxisOrdersTimePointsByTemporalPosition,
    TimeEvidence, TimeIntervalBoundaryOrDurationFormDeclared, TimeIntervalEvidence,
    TimeIntervalHasTwoComponents, TimeIntervalUsesSolidusSeparator, TimeIntervalValid,
    TimeIsMarkOnSpecifiedTimeScale, TimeOfDayOccursWithinCalendarDay, TimeOfDayWithShiftEvidence,
    TimeOfDayWithShiftValid, TimeScaleAssociatesTimePointsWithOrderedMeasure,
    TimeShiftIsConstantDurationBetweenTimeScales, TimeValid, TimestampHasExplicitUtcOffset,
    TimestampRepresentsFixedInstant, TwentyFourHourRequiresZeroMinuteSecondAndFraction,
    TwentyFourHourReservedForEndOfDay, UncertaintyAndApproximationMayBeCombined,
    UncertaintyQualificationDeclared, UnderlineFallbackPrecedesQualifiedFormatCharacter,
    UnderlinedFormatPlaceholderRepresentsZeroOrMoreDigits, UnknownIntervalBoundaryDeclared,
    UnknownNamedTimeZoneIdentifierTreatedAsInconsistency, UnspecifiedComponentExpressionEvidence,
    UnspecifiedComponentExpressionValid, UnspecifiedDigitUsesUppercaseXPlaceholder,
    UnspecifiedDigitsDeclareUnknownValue, UtcDesignatorIsUppercaseZ,
    UtcDifferenceAppendedImmediatelyWithoutSpace, UtcDifferenceExpressionIsNotSelfStanding,
    UtcDifferenceMinutesOmittedOnlyForIntegralHourOffsets,
    UtcDifferenceSignEncodesDirectionRelativeToUtc, UtcIsReferenceTimeScale, UtcOfDayEvidence,
    UtcOfDayIdentifiesTimeWithinUtcCalendarDay, UtcOfDayUsesTrailingZuluDesignatorImmediately,
    UtcOfDayValid, UtcOffsetCarriesSignHourAndOptionalMinute, UtcOffsetEvidence,
    UtcOffsetHourInRangeZeroToTwentyThree, UtcOffsetKnown, UtcOffsetMinuteInRangeZeroToFiftyNine,
    UtcOffsetValid, UtcTimeScaleEvidence, UtcTimeScaleValid,
    UtcTimelineOrderingAppliesToFixedInstants, WeekDateEvidence, WeekDateHasWeekYearWeekAndWeekday,
    WeekDateUsesWeekDesignator, WeekDateValid, WeekDurationMaySpanSameTimeOfDayInNextCalendarWeek,
    WeekNumberInRangeOneToFiftyThree, WeekdayInRangeOneToSeven,
    YearDurationInRangeThreeHundredSixtyFiveToThreeHundredSixtySixCalendarDays,
    YearDurationMayRequireAgreedEndingCalendarDate, ZoneOffsetResolvedForRepresentedInstant,
    ZoneTransitionAmbiguityDeclared, ZoneTransitionAmbiguityEvidence,
    ZoneTransitionAmbiguitySemanticsValid, ZoneTransitionDisambiguationAuthorityDeclared,
    ZoneTransitionGapDeclared, ZoneTransitionGapEvidence,
    ZoneTransitionGapHandlingAuthorityDeclared, ZoneTransitionGapSemanticsValid,
    ZoneTransitionResolutionAuthorityEvidence, ZoneTransitionResolutionAuthorityValid,
    ZonedDateTimeHasNamedZone, ZonedTimestampEvidence, ZuluTimeZoneInconsistencyAvoidanceEvidence,
    ZuluTimeZoneInconsistencyAvoidanceValid, ZuluTimeZoneSuffixAvoidsOffsetInconsistency,
};
pub use error::{TemporalError, TemporalErrorKind, TemporalResult};
pub use traits::{
    TemporalBackend, TemporalCalConnectFactory, TemporalCivilNativeBridge, TemporalCivilProps,
    TemporalConversionFactory, TemporalDateTimeFormulaNativeBridge, TemporalDateTimeFormulaProps,
    TemporalDurationNativeBridge, TemporalDurationProps, TemporalExplicitDurationNativeBridge,
    TemporalExplicitDurationProps, TemporalExplicitTemporalFormNativeBridge,
    TemporalExplicitTemporalFormProps, TemporalExplicitTimeIntervalNativeBridge,
    TemporalExplicitTimeIntervalProps, TemporalExtensionProps, TemporalFormatter,
    TemporalGroupedTimeScaleUnitNativeBridge, TemporalGroupedTimeScaleUnitProps,
    TemporalInstantNativeBridge, TemporalInstantProps, TemporalIntervalFactory,
    TemporalNativeBridge, TemporalNativeConversionFactory, TemporalNativeDateTimeFormulaFactory,
    TemporalNativeExtensionBridge, TemporalNativeIntervalFactory, TemporalNativeProps,
    TemporalNativeSpanBridge, TemporalNativeZoneFactory, TemporalParser,
    TemporalQualifiedTemporalValueNativeBridge, TemporalQualifiedTemporalValueProps,
    TemporalRecurringIntervalNativeBridge, TemporalRecurringIntervalProps, TemporalReporter,
    TemporalSetNativeBridge, TemporalSetProps, TemporalSpanProps, TemporalTimeIntervalNativeBridge,
    TemporalTimeIntervalProps, TemporalZoneFactory, TemporalZoneNativeBridge, TemporalZoneProps,
};
pub use types::{
    AttachedNamedZoneResult, BackendConversionSemanticBundle, CalendarDateDescriptor,
    CenturyDescriptor, CompleteDateDescriptor, CompleteIntervalSubstitutionProofBranch,
    ConfirmedNamedZoneRevisionResult, ConfirmedProvenNamedZoneRevisionResult,
    ConfirmedZoneTransitionResolutionAuthorityResult, DateDescriptor, DateTimeFormulaDescriptor,
    DateTimeFormulaEvaluationKindDescriptor, DateTimeFormulaEvaluationResultBundle,
    DateTimeFormulaSemanticBundle, DateWithShiftDescriptor, DecadeDescriptor, DurationDescriptor,
    DurationFractionDescriptor, DurationRepresentationProofBranch, DurationSemanticBundle,
    EligibleTimeIntervalsDescriptor, EvaluatedDateTimeFormulaResult, ExplicitDateTimeDescriptor,
    ExplicitDateTimeWithShiftDescriptor, ExplicitDurationDescriptor,
    ExplicitDurationRepresentationKindDescriptor, ExplicitDurationSemanticBundle,
    ExplicitDurationSemanticKindDescriptor, ExplicitDurationSignDescriptor,
    ExplicitIntervalDurationSubstitutionProofBranch,
    ExplicitIntervalEndComponentInheritanceProofBranch,
    ExplicitIntervalShiftPropagationProofBranch, ExplicitTemporalFormDescriptor,
    ExplicitTemporalFormSemanticBundle, ExplicitTemporalValueDescriptor,
    ExplicitTimeIntervalDescriptor, ExplicitTimeIntervalEndpointDescriptor,
    ExplicitTimeIntervalRepresentation, ExplicitTimeIntervalSemanticBundle,
    ExplicitTimeOfDayDescriptor, ExplicitTimeShiftDescriptor, ExtendedYearBaseDescriptor,
    ExtendedYearDescriptor, FormattedCenturyResult, FormattedDateTimeFormulaResult,
    FormattedDateWithShiftResult, FormattedDecadeResult, FormattedDurationResult,
    FormattedExplicitDurationResult, FormattedExplicitTemporalFormResult,
    FormattedExplicitTimeIntervalResult, FormattedExtendedYearResult,
    FormattedGroupedTimeScaleUnitResult, FormattedIxdtfTimestampResult,
    FormattedQualifiedTemporalValueResult, FormattedRecurringIntervalResult,
    FormattedRecurringIntervalWithRepeatRuleResult, FormattedRepeatRuleResult,
    FormattedSeasonalTemporalExpressionResult, FormattedSelectionExpressionResult,
    FormattedSubYearGroupingExpressionResult, FormattedTemporalSetResult,
    FormattedTimeIntervalResult, FormattedTimeOfDayWithShiftResult,
    FormattedUnspecifiedComponentExpressionResult, FractionalSecondDescriptor,
    GroupedTimeScaleUnitDescriptor, GroupedTimeScaleUnitSemanticBundle,
    IntervalEndComponentInheritanceProofBranch, IntervalEndpointOrderingBundle,
    IntervalZoneInheritanceProofBranch, IxdtfAdditionalInformationProofBranch,
    IxdtfAnnotationDescriptor, IxdtfCalendarAnnotationDescriptor,
    IxdtfCalendarAnnotationProofBranch, IxdtfTimeZoneAnnotationDescriptor,
    IxdtfTimeZoneAnnotationProofBranch, IxdtfTimestampDescriptor, LocalDateTimeDescriptor,
    LocalDateTimeSemanticBundle, LocalTimeDescriptor, LocalTimeScaleDescriptor,
    LocalTimeZoneResolutionAuthorityDescriptor, LocalTimeZoneResolutionProofBranch,
    LosslessConversionBundle, LosslessPrecisionAdjustedTimestampResult,
    LossyConversionAuthorityBundle, MaskedNumericComponentDescriptor, NamedSeasonDescriptor,
    NamedTimeZoneDescriptor, NamedTimeZoneRevisionBundle, NamedTimeZoneSemanticBundle,
    NativeAttachedNamedZoneResult, NativeAttachedProvenNamedZoneResult,
    NativeEvaluatedProvenDateTimeFormulaResult,
    NativeLosslessPrecisionAdjustedProvenTimestampResult,
    NativeLosslessPrecisionAdjustedTimestampResult, NativeNormalizedProvenUtcTimestampResult,
    NativeNormalizedUtcTimestampResult, NativeOrderedOffsetEndpointsResult,
    NativeOrderedProvenOffsetEndpointsResult, NativeResolvedLocalDateTimeAtNamedZoneResult,
    NativeResolvedProvenLocalDateTimeAtNamedZoneResult, NativeStrippedNamedZoneTimestampResult,
    NativeStrippedProvenNamedZoneTimestampResult, NativeTruncatedProvenSubsecondsTimestampResult,
    NativeTruncatedSubsecondsTimestampResult, NormalizedUtcTimestampResult,
    OffsetDateTimeDescriptor, OffsetDateTimeSemanticBundle, OrdinalDateDescriptor,
    ParsedCenturyResult, ParsedDateTimeFormulaResult, ParsedDateWithShiftResult,
    ParsedDecadeResult, ParsedDurationResult, ParsedExplicitDurationResult,
    ParsedExplicitTemporalFormResult, ParsedExplicitTimeIntervalResult, ParsedExtendedYearResult,
    ParsedGroupedTimeScaleUnitResult, ParsedIxdtfTimestampResult, ParsedOffsetDateTimeResult,
    ParsedQualifiedTemporalValueResult, ParsedRecurringIntervalResult,
    ParsedRecurringIntervalWithRepeatRuleResult, ParsedReducedCalendarDateResult,
    ParsedReducedLocalTimeResult, ParsedRepeatRuleResult, ParsedRfc3339TimestampResult,
    ParsedSeasonalTemporalExpressionResult, ParsedSelectionExpressionResult,
    ParsedSubYearGroupingExpressionResult, ParsedTemporalSetResult, ParsedTimeIntervalResult,
    ParsedTimeOfDayWithShiftResult, ParsedUnspecifiedComponentExpressionResult,
    PrecisionDescriptor, ProvenDateTimeFormulaCarrier, ProvenDurationCarrier,
    ProvenExplicitDurationCarrier, ProvenExplicitTemporalFormCarrier,
    ProvenExplicitTimeIntervalCarrier, ProvenGroupedTimeScaleUnitCarrier,
    ProvenLocalDateTimeCarrier, ProvenNamedTimeZoneCarrier, ProvenOffsetDateTimeCarrier,
    ProvenQualifiedTemporalValueCarrier, ProvenRecurringIntervalCarrier, ProvenTemporalCarrier,
    ProvenTemporalSetCarrier, ProvenTimeIntervalCarrier, ProvenZonedDateTimeCarrier,
    QuadrimesterOfYearDescriptor, QualificationPlacementDescriptor, QualificationScopeDescriptor,
    QualifiedOrBareTemporalValueDescriptor, QualifiedTemporalExpressionDescriptor,
    QualifiedTemporalValueDescriptor, QualifiedTemporalValueSemanticBundle,
    QuarterOfYearDescriptor, RealizedDurationResult, RealizedLocalDateTimeResult,
    RealizedNamedTimeZoneResult, RealizedOffsetDateTimeResult, RealizedProvenDateTimeFormulaResult,
    RealizedProvenDurationResult, RealizedProvenExplicitDurationResult,
    RealizedProvenExplicitTemporalFormResult, RealizedProvenExplicitTimeIntervalResult,
    RealizedProvenGroupedTimeScaleUnitResult, RealizedProvenLocalDateTimeResult,
    RealizedProvenNamedTimeZoneResult, RealizedProvenOffsetDateTimeResult,
    RealizedProvenQualifiedTemporalValueResult, RealizedProvenRecurringIntervalResult,
    RealizedProvenTemporalSetResult, RealizedProvenTimeIntervalResult,
    RealizedProvenZonedDateTimeResult, RealizedRecurringIntervalResult, RealizedTimeIntervalResult,
    RealizedZonedDateTimeResult, RecurringIntervalDescriptor,
    RecurringIntervalRepresentationProofBranch, RecurringIntervalSemanticBundle,
    RecurringIntervalWithRepeatRuleDescriptor, RecurringIntervalWithRepeatRuleIntervalDescriptor,
    RecurringIntervalWithRepeatRuleIntervalProofBranch, ReducedCalendarDateDescriptor,
    ReducedLocalTimeDescriptor, ReflectedDurationResult, ReflectedLocalDateTimeResult,
    ReflectedNamedTimeZoneResult, ReflectedOffsetDateTimeResult,
    ReflectedProvenDateTimeFormulaResult, ReflectedProvenDurationResult,
    ReflectedProvenExplicitDurationResult, ReflectedProvenExplicitTemporalFormResult,
    ReflectedProvenExplicitTimeIntervalResult, ReflectedProvenGroupedTimeScaleUnitResult,
    ReflectedProvenLocalDateTimeResult, ReflectedProvenNamedTimeZoneResult,
    ReflectedProvenOffsetDateTimeResult, ReflectedProvenQualifiedTemporalValueResult,
    ReflectedProvenRecurringIntervalResult, ReflectedProvenTemporalSetResult,
    ReflectedProvenTimeIntervalResult, ReflectedProvenZonedDateTimeResult,
    ReflectedRecurringIntervalResult, ReflectedTimeIntervalResult, ReflectedZonedDateTimeResult,
    RepeatRuleDescriptor, ResolvedLocalDateTimeAtNamedZoneResult, ResolvedNamedTimeZoneResult,
    RoundingModeDescriptor, SeasonScopeDescriptor, SeasonalTemporalExpressionDescriptor,
    SelectionExpressionDescriptor, SelectionRuleDescriptor, SemestralHalfDescriptor,
    SerializationProfile, StandardTimeDescriptor, StandardTimeOfDayDescriptor,
    StrippedNamedZoneTimestampResult, SubYearGroupingDescriptor,
    SubYearGroupingExpressionDescriptor, SubsecondTruncationBundle, TemporalComponent,
    TemporalSerializationDescriptor, TemporalSetDescriptor, TemporalSetMemberDescriptor,
    TemporalSetSemanticBundle, TemporalSetSemanticsDescriptor, TemporalValueDescriptor,
    TimeDescriptor, TimeIntervalDescriptor, TimeIntervalEndpoint, TimeIntervalRepresentation,
    TimeIntervalSemanticBundle, TimeOfDayWithShiftDescriptor, TimeScaleUnitDescriptor,
    TimeScaleUnitFractionDescriptor, TimeScaleUnitValueDescriptor,
    TruncatedSubsecondsTimestampResult, UnspecifiedComponentExpressionDescriptor,
    UnspecifiedDigitDescriptor, UnspecifiedPrecisionProfileDescriptor,
    UnspecifiedTemporalShapeDescriptor, UtcOfDayDescriptor, UtcOffsetDescriptor,
    UtcOffsetRelationship, UtcOffsetSign, UtcTimeScaleDescriptor, WeekDateDescriptor,
    ZoneAmbiguityResolutionDescriptor, ZoneGapResolutionDescriptor,
    ZoneTransitionResolutionAuthorityBundle, ZonedDateTimeDescriptor, ZonedDateTimeSemanticBundle,
};
