//! Contracts re-exports.

pub mod fgdc;
pub mod iso_19111;
pub mod iso_19115;
pub mod ogc_sfs;
pub mod rfc7946;

pub use iso_19111::{
    AngularAxisMustUseAngularUnit,
    AxisAbbreviationNonEmpty,
    AxisAbbreviationUniqueInCs,
    AxisAbbreviationUniqueWithinCs,
    AxisDirectionIsValidCode,
    AxisDirectionMemberOfCodeList,
    AxisMinMaxValueOptional,
    AxisNameNonEmpty,
    AxisOrderChangeRequiresExplicitOperation,
    AxisOrderMustFollowCrsDefinition,
    AxisRangeMeaningExactOrWraparound,
    AxisUnitAppropriateForAxisType,
    CompoundCrsComponentsNonOverlapping,
    CompoundCrsComponentsOrthogonal,
    CompoundCrsEpsgRange6000To6999,
    // §12 Compound CRS
    CompoundCrsHasAtLeastTwoComponents,
    CompoundCrsMinimumTwoComponents,
    CompoundCrsNameNonEmpty,
    CompoundCrsNoTwoHorizontalComponents,
    CompoundCrsNoTwoVerticalComponents,
    CompoundCrsTotalAxisCountIsSumOfComponents,
    CompoundCrsTypicalIs2dPlusVertical,
    ConcatenatedOperationHasAtLeastTwoSteps,
    ConcatenatedOperationMinimumTwoSteps,
    ConcatenatedOperationSourceCrsIsFirstStep,
    ConcatenatedOperationStepsFormAChain,
    ConcatenatedOperationTargetCrsIsLastStep,
    ConversionDefinesMapProjection,
    ConversionHasOperationMethod,
    ConversionHasParameterValues,
    ConversionInverseExists,
    ConversionInvolvesNoDatumChange,
    CoordinateElementAlignedToAxisOrdinalPosition,
    CoordinateEpochDistinctFromFrameReferenceEpoch,
    CoordinateEpochIsDecimalYear,
    CoordinateEpochPositiveFinite,
    CoordinateMetadataApplicableAtSetOrTupleLevel,
    CoordinateMetadataCrsNonNull,
    CoordinateMetadataDynamicCrsRequiresEpoch,
    CoordinateMetadataEpochIsDecimalYear,
    // §23 CoordinateMetadata
    CoordinateMetadataHasCrs,
    CoordinateMetadataStaticCrsEpochShouldBeAbsent,
    CoordinateMetadataValid,
    CoordinateOperationDomainOfValidityOptional,
    CoordinateOperationHasSourceCrs,
    CoordinateOperationHasTargetCrs,
    CoordinateOperationInheritsIdentifiedObjectInterface,
    // §14 Coordinate operations
    CoordinateOperationNameNonEmpty,
    CoordinateOperationVersionOptional,
    // §8 Coordinate system
    CoordinateSystemAxisCountOneToFour,
    CoordinateSystemMaximumFourAxes,
    // §20 Additional value constraints
    CoordinateSystemMinimumOneAxis,
    CoordinateSystemNameNonEmpty,
    // §8 aggregate
    CoordinateSystemValid,
    CoordinateTupleDimensionMatchesAxes,
    CoordinateTupleElementCountEqualsAxisCount,
    CoordinatesTransformed,
    CrsComponentGraphAcyclic,
    // §6 CRS general
    CrsConsistsOfCsAndDatum,
    CrsDomainOfValidityExtentTypes,
    CrsDomainOfValidityOptionalImpliesGlobal,
    CrsIdentifierAuthorityNonEmpty,
    CrsIdentifierCodeNonEmpty,
    // §18 Cross-cutting
    CrsIdentityAuthorityPlusCodeUnique,
    CrsIdentityByAuthorityAndCode,
    CrsInheritsIdentifiedObjectInterface,
    CrsMandatoryStringNonNull,
    // Trait operation contracts
    CrsResolved,
    CrsScopeDescribesIntendedUse,
    CrsStringValuesUtf8Encoded,
    CrsTypeMemberOfDefinedTypes,
    CrsValid,
    CsAxisCountMatchesTupleDimensionality,
    CsTypeMemberOfDefinedTypes,
    DatumEnsembleAccuracyFinite,
    DatumEnsembleAccuracyPositive,
    // §22 DatumEnsemble
    DatumEnsembleGroupsRelatedDatums,
    DatumEnsembleHasAtLeastTwoMembers,
    DatumEnsembleMemberNoNullEntries,
    DatumEnsembleMembersHomogeneous,
    DatumEnsembleNameNonEmpty,
    DatumEnsembleResolved,
    DatumEnsembleSubMetreRequiresMemberSelection,
    DatumEnsembleWgs84EpsgCode6326,
    DatumInheritsIdentifiedObjectInterface,
    DerivedCrsCsDiffersFromBaseCrsAllowed,
    DerivedCrsDerivingConversionIsConversion,
    // §13 Derived CRS
    DerivedCrsHasBaseCrs,
    DerivedCrsInheritsDatumFromBase,
    DerivedCrsNameNonEmpty,
    DerivedProjectedCrsBaseMustBeProjCrs,
    DifferentCrsCodesRequireExplicitOperation,
    DynamicCrsOmittingEpochIntroducesError,
    DynamicCrsRequiresCoordinateEpoch,
    DynamicReferenceFrameHasFrameReferenceEpoch,
    DynamicReferenceFrameVelocityModelReferenced,
    EllipsoidInverseFlatteningPositiveWhenNonSphere,
    EllipsoidInverseFlatteningZeroMeansSphere,
    EllipsoidIsSphereConsistentWithParameters,
    // §7.3 Ellipsoid
    EllipsoidNameNonEmpty,
    EllipsoidSecondParameterEitherInverseFlatteningOrSemiMinor,
    EllipsoidSemiMajorAxisFinite,
    EllipsoidSemiMajorAxisInMetres,
    EllipsoidSemiMajorAxisPositive,
    EllipsoidSemiMinorAxisFinite,
    EllipsoidSemiMinorAxisInMetres,
    EllipsoidSemiMinorAxisLessThanSemiMajor,
    EllipsoidValid,
    EllipsoidWgs84InverseFlatteningApprox298,
    EngineeringCrsCsTypeFlexible,
    // §11 Engineering CRS
    EngineeringCrsDatumIsEngineeringDatum,
    EngineeringCrsIsLocalContextOnly,
    EngineeringCrsNameNonEmpty,
    EngineeringDatumAnchorOptional,
    EngineeringDatumNameNonEmpty,
    Epsg4326AxisOrderLatFirst,
    Epsg4326LatitudeRangeValid,
    Epsg4326LongitudeRangeValid,
    Epsg4326UsesDatumEnsemble,
    Epsg4978IsWgs84Geocentric,
    Epsg4978XAxisTowardsPrimeMeridian,
    Epsg4978ZAxisTowardsNorthPole,
    Epsg4979HeightUnbounded,
    Epsg4979IsWgs84Geographic3d,
    EpsgAuthorityNameIsEpsg,
    // §16 EPSG registry
    EpsgCodePositiveInteger,
    EpsgCompoundCrsRange6000To6999,
    EpsgGeographicCrsRange4000To4999,
    EpsgProjectedCrsRange20000To32767,
    EpsgVerticalCrsRange5000To5999,
    GeocentricCrsUsesCartesianCs,
    GeodeticCrsCsIsEllipsoidalOrCartesian,
    // §7 Geodetic CRS
    GeodeticCrsDatumIsGeodeticReferenceFrame,
    GeodeticReferenceFrameAnchorOptional,
    GeodeticReferenceFrameHasExactlyOneEllipsoid,
    GeodeticReferenceFrameHasExactlyOnePrimeMeridian,
    // §7.2 Reference frame
    GeodeticReferenceFrameNameNonEmpty,
    GeodeticReferenceFrameRealizationEpochIsIso8601,
    // §7.2 aggregate
    GeodeticReferenceFrameValid,
    Geographic2dCrsHasTwoAxes,
    // §15 Axis order
    Geographic2dIsoAxisOrderLatitudeFirst,
    Geographic3dCrsHasThreeAxes,
    Geographic3dIsoAxisOrderLatLonHeight,
    // §27 Grid-based datum shifts
    GridBasedDatumShiftUsesExternalFile,
    HelmertConventionMustBeIdentified,
    HelmertConventionsEquivalentOnlyForZeroRotation,
    HelmertCoordinateFrameConvention,
    HelmertEpsgMethodCodes9606And9607,
    HelmertPositionVectorConvention,
    // §26 Helmert conventions
    HelmertSevenParameterStructure,
    IdentifiedObjectAliasNoDuplicates,
    IdentifiedObjectAliasNoNullEntries,
    IdentifiedObjectAliasOptionalList,
    IdentifiedObjectIdentifierEntryComplete,
    // §21 IO_IdentifiedObject
    IdentifiedObjectPrimaryNameNonEmpty,
    IdentifiedObjectRemarksOptional,
    IdentifiedObjectRemarksWhenPresentNonNull,
    Igs20IsDynamicDatum,
    Itrf2014IsDynamicDatum,
    Itrf2020IsDynamicDatum,
    LatitudePolesValid,
    LatitudeRangeNegative90To90,
    LinearAxisMustUseLinearUnit,
    LongitudeNegative180Excluded,
    LongitudeRangeNegative180To180,
    MapProjectionFalseOriginFiniteReal,
    MapProjectionScaleFactorFinite,
    MapProjectionScaleFactorPositive,
    MolodenskyBadenkasTenParameter,
    Nad27EnsembleEpsg6267,
    Nadcon5IsUsHorizontalDatumShift,
    Ntv2IsGridHorizontalShift,
    NullAuthorityCodeInvalidForRegisteredCrs,
    OgcAuthorityNameIsOgc,
    OperationMethodFormulaOptional,
    OperationMethodHasParameterList,
    OperationMethodNameNonEmpty,
    OperationMethodParameterNoDuplicates,
    OperationParameterNameNonEmpty,
    OperationParameterValueFiniteReal,
    OperationParameterValueHasUnit,
    OtherAuthorityNamesEsriIgnf,
    ParameterFileStoresFilenameNotValue,
    ParametricAxisMustUseParametricUnit,
    ParametricCrsCsIsParametricCs,
    ParametricCrsDatumIsParametricDatum,
    ParametricCrsHasOneAxis,
    PassThroughOperationCompoundCrsUsage,
    PassThroughOperationDimensionConsistency,
    PassThroughOperationIndexInRange,
    PassThroughOperationInnerOperationNonNull,
    PassThroughOperationModifiedCoordinatesNonEmpty,
    // §24 PassThroughOperation
    PassThroughOperationPreservesSomeAxes,
    PrimeMeridianGreenwichIsZero,
    PrimeMeridianGreenwichLongitudeFinite,
    PrimeMeridianGreenwichLongitudeInDegreeBounds,
    PrimeMeridianGreenwichLongitudeUnitIsAngular,
    // §7.4 Prime meridian
    PrimeMeridianNameNonEmpty,
    PrimeMeridianNonGreenwichAllowed,
    // §7.4 aggregate
    PrimeMeridianValid,
    ProjectedConventionalAxisOrderEastingFirst,
    ProjectedCrsAxesUseLinearUnit,
    // §9 Projected CRS
    ProjectedCrsBaseCrsIsGeographic,
    ProjectedCrsConventionalAxisDirections,
    ProjectedCrsCsIsCartesian,
    ProjectedCrsHasTwoAxes,
    ProjectedCrsNameNonEmpty,
    ProjectedCrsProjectionIsConversion,
    ProjectedNorthingFirstVariantsExist,
    RegisteredCrsNullAuthorityCodeInvalid,
    ScCrsDomainOfValidityIsExtent,
    ScCrsIdentifierHasAuthorityAndCode,
    ScCrsIsAbstract,
    ScCrsNameNonEmpty,
    ScCrsScopeNonEmpty,
    SphericalCsAngularAxesThenLinear,
    SphericalCsApplicableToGeocentricContext,
    // §25 SphericalCS
    SphericalCsHasThreeAxes,
    StaticCrsDatumAtFixedEpoch,
    // §17 Dynamic / static CRS
    StaticCrsPlateFixedNoEpochRequired,
    TemporalCrsCsIsTemporalCs,
    // §19 Temporal / parametric CRS
    TemporalCrsDatumIsTemporalDatum,
    TemporalCrsHasOneAxis,
    TemporalDatumOriginIsIso8601DateTime,
    TimeAxisMustUseTemporalUnit,
    TransformationAccuracyNonZero,
    TransformationAccuracyPositiveReal,
    TransformationInverseApproximate,
    TransformationInvolvesDatumChange,
    TransformationNad27ToWgs84UsesHelmert,
    UomAngularConvertToRadians,
    UomConversionFactorFinite,
    UomConversionFactorPositive,
    UomFeetAmbiguityInternationalVsSurvey,
    UomLinearConvertToMetres,
    // §28 UoM
    UomNameNonEmpty,
    UomScaleDimensionless,
    UomTimeConvertToSeconds,
    UtmAxisOrderEastingFirst,
    UtmCommonParametersFalseEastingAndScale,
    UtmFalseEasting500000,
    UtmNorthZoneEpsgRange32601To32660,
    UtmNorthZoneFalseNorthing0,
    UtmScaleFactorAtCentralMeridian0996,
    UtmSouthZoneEpsgRange32701To32760,
    // §29 UTM south zone
    UtmSouthZoneFalseNorthing10000000,
    UtmZoneNumberOneToSixty,
    UtmZoneWidthSixDegrees,
    VertconIsUsVerticalDatumShift,
    VerticalCrsAxisLinearUnit,
    VerticalCrsCsIsVerticalCs,
    // §10 Vertical CRS
    VerticalCrsDatumIsVerticalReferenceFrame,
    VerticalCrsDepthAxisDirectionDown,
    VerticalCrsEpsgRange5000To5999,
    VerticalCrsHasOneAxis,
    VerticalCrsHeightAxisDirectionUp,
    VerticalCrsNameNonEmpty,
    VerticalReferenceFrameAnchorOptional,
    VerticalReferenceFrameGravityRelated,
    VerticalReferenceFrameNameNonEmpty,
    VerticalReferenceFrameRealizationEpochIsIso8601,
};

pub use ogc_sfs::{
    Area0DReturnsZero, Area1DReturnsZero, Area2DReturnsPositive, AreaEmptyGeometryIsZero,
    AreaIsFinite, AreaNonNegative, AreaUnitsSquaredSrsUnits, AsBinaryMethodDefined,
    AsBinaryReturnsWkb, AsTextMethodDefined, AsTextReturnsWkt, BoundaryOfBoundaryIsEmpty,
    BufferNegativeDistanceShrinks, BufferPositiveDistanceIncreasesArea, BufferResultIsValid,
    BufferReturnsContainingGeometry, BufferZeroContainsSelf, CentroidDefinedForAll,
    CentroidReturnsPoint, CentroidWithinConvexHull, CentroidXIsFinite, CentroidYIsFinite,
    CollectionCoordDimMatchesComponents, CollectionGeometryNIndexed, CollectionGeometryNNeverNull,
    CollectionNumGeometriesCount, CollectionNumGeometriesNonNegative,
    ConformanceClass0RequiresSevenTypes, ConformanceClass0RequiresWkbWkt,
    ConformanceClass1AddsPredicates, ConformanceClass1AddsSetOps, ContainsDe9ImPattern,
    ContainsIsInverseOfWithin, ContainsIsNotSymmetric, ConvexHullContainsSelf,
    ConvexHullIdempotent, ConvexHullOfConvexPolygonIsSelf, ConvexHullReturnsSmallestConvex,
    Coord2DMPosition, Coord2DPosition, Coord3DMPosition, Coord3DPosition, Coord3DZIsElevation,
    CoordDimUniformInGeometry, CoordDimensionalityIsConsistent, CoordDimensionalityUniform,
    CoordMIsFiniteWhenPresent, CoordMIsMeasure, CoordXIsFinite, CoordYIsFinite,
    CoordZIsFiniteWhenPresent, CoveredByIsInverseOfCovers, CoversDe9ImPattern, CoversImpliesWithin,
    CrossesDe9ImPattern, CrossesDimIntersectionLessThanMax, CrossesDimensionConstraint,
    CrossesIsNotSymmetric, De9ImCellValues, De9ImInteriorBoundaryExteriorAxes, De9ImMatrixDefined,
    De9ImRelatePatternIsNineChars, DifferenceAsymmetric, DifferenceDimensionAtMostSelf,
    DifferenceDisjointFromSubtracted, DifferenceSubsetOfSelf, DimensionConsistencyInHierarchy,
    DisjointDe9ImPattern, DisjointIsInverseOfIntersects, DisjointIsSymmetric, DistanceInSrsUnits,
    DistanceIsFinite, DistanceNonNegative, DistanceSymmetric, DistanceTriangleInequality,
    DistanceZeroIffIntersecting, EmptyGeometryBoundaryIsEmpty,
    EmptyGeometryBoundaryIsEmptyGeometry, EmptyGeometryEnvelopeIsEmpty, EmptyHandlingConsistent,
    EnvelopeEmptyWhenGeometryEmpty, EnvelopeIsPointWhenDegenerate, EnvelopeIsPolygon,
    EqualsDe9ImPattern, EqualsIsReflexive, EqualsIsSymmetric, EwkbBaseTypeCodeMasked,
    EwkbSridIsUint32, EwkbSridPresent, GeometryBoundaryDefinedPerType,
    GeometryCollectionAllComponentsValid, GeometryCollectionBoundaryMod2Rule,
    GeometryCollectionHeterogeneousAllowed, GeometryCollectionIsSimpleAllSimple,
    GeometryCollectionMayBeEmpty, GeometryCollectionValid, GeometryDimension0ForPoint,
    GeometryDimension1ForLine, GeometryDimension2ForSurface, GeometryDimensionMinus1WhenEmpty,
    GeometryEnvelopeReturnsMbr, GeometryHasSrs, GeometryIsEmptyPredicate,
    GeometryIsSimpleAndIsValidDistinct, GeometryIsSimplePredicate, GeometryIsValidPredicate,
    GeometrySridReturnsInteger, GeometrySrsNotNull, GeometryTypeMatchesConcreteName,
    GeometryTypeReturnsString, IntersectionDimensionAtMostMin, IntersectionIsCommutative,
    IntersectionOfDisjointIsEmpty, IntersectionSubsetOfBothInputs, IntersectsAtLeastOneSharedPoint,
    IntersectsIsNotDisjoint, IntersectsIsSymmetric, IsEmptyFalseForNonEmpty, IsEmptyTrueForEmpty,
    IsSimpleNoSelfIntersection, IsValidImpliesSubComponentsValid, IsValidWellFormed,
    Length0DReturnsZero, Length1DReturnsPositive, Length2DReturnsZero, LengthEmptyGeometryIsZero,
    LengthInSrsUnits, LengthIsFinite, LengthNonNegative, LineStringAdjacentPointsDistinct,
    LineStringBoundaryIsEndpoints, LineStringClosedBoundaryEmpty, LineStringClosedEqualsLinearRing,
    LineStringEndPointIsPointNLast, LineStringHasTwoOrMorePoints, LineStringIsClosedStartEqualsEnd,
    LineStringIsRingImpliesClosedAndSimple, LineStringMinimumTwoPositions,
    LineStringNonClosedBoundaryIsEndpointMultiPoint, LineStringNumPointsMatchesCoordCount,
    LineStringOpenBoundaryTwoPoints, LineStringPointNInRange, LineStringSimpleNoSelfIntersection,
    LineStringStartPointIsPointNZero, LineStringValid, LinearRingBoundaryIsEmpty,
    LinearRingBoundaryIsEmptySet, LinearRingFirstPositionEqualsLast, LinearRingIsClosedLineString,
    LinearRingIsSimple, LinearRingMinimumFourPositions, LinearRingNonDegenerate, LinearRingValid,
    MultiLineStringComponentsAreLineStrings, MultiLineStringIsClosedAllClosed2,
    MultiLineStringMayBeEmpty, MultiLineStringSimpleWhenIntersectAtEndpointsOnly,
    MultiLineStringValid, MultiPointComponentsArePoints, MultiPointMayBeEmpty,
    MultiPointSimpleWhenNoTwoEqual, MultiPointValid, MultiPolygonBoundariesDontOverlap,
    MultiPolygonBoundariesTouchAtPoints, MultiPolygonBoundaryIsAllRings,
    MultiPolygonComponentsArePolygons, MultiPolygonInteriorsDisjoint, MultiPolygonMayBeEmpty,
    MultiPolygonValid, OverlapsDe9ImPattern2D, OverlapsDe9ImPatternLowDim,
    OverlapsDimensionConstraint, OverlapsIsSymmetric, PointAlwaysValid, PointBoundaryIsEmpty,
    PointEmptyHasNoCoords, PointEmptyIsEmpty, PointMDefinedWhenMPresent,
    PointOnSurfaceDefinedForAll, PointOnSurfaceIsOnGeometry, PointOnSurfaceReturnsPoint,
    PointValid, PointXIsFinite, PointXReturnsXOrdinate, PointYIsFinite, PointYReturnsYOrdinate,
    PointZDefinedWhen3D, PointZIsFiniteWhenPresent, PolygonBoundaryIsAllRings,
    PolygonExteriorIsCCW, PolygonExteriorIsLinearRing, PolygonExteriorRingNeverNull,
    PolygonHasExactlyOneExteriorRing, PolygonHoleCountNonNegative, PolygonHolesAreCW,
    PolygonHolesDontContainEachOther, PolygonHolesInsideExterior, PolygonInteriorRingNInRange,
    PolygonInteriorRingNReturnsHole, PolygonInteriorRingsAreLinearRings,
    PolygonNoRingSelfIntersects, PolygonNumInteriorRingsNonNegative, PolygonRingsDontCross,
    PolygonRingsDontTouchAlongSegment, PolygonRingsTouchAtPoints, PolygonValid,
    RelatePatternCharacters, RelatePatternLength9, RelateReturnsBooleanMatchingPattern,
    SfsGeometryValid, SridAssignedAtConstruction, SridIsInteger, SridNonNegative,
    SrsConsistentInCollection, SymDifferenceEqualsUnionMinusIntersection,
    SymDifferenceIsCommutative, TouchesDe9ImPattern, TouchesInteriorsDisjoint, TouchesIsSymmetric,
    UnionDimensionIsMax, UnionEqualsIntersectionPlusSymDifference, UnionIsAssociative,
    UnionIsCommutative, UnionSupersetOfBothInputs, WithinDe9ImPattern, WithinIsInverseOfContains,
    WithinIsNotSymmetric, WkbByteOrderBigEndian, WkbByteOrderLittleEndian,
    WkbByteOrderMarkerPresent, WkbByteOrderMarkerTwoValues, WkbCoordinateIsDouble,
    WkbCoordinatesByteOrderMatches, WkbCountFieldsAreUint32, WkbLengthValid, WkbMVariant,
    WkbPointLength21Bytes2D, WkbRingHasCount, WkbRoundTrip, WkbSubGeometriesAreCompleteBlobs,
    WkbTypeCodeGeometryCollection, WkbTypeCodeLineString, WkbTypeCodeMultiLineString,
    WkbTypeCodeMultiPoint, WkbTypeCodeMultiPolygon, WkbTypeCodePoint, WkbTypeCodePolygon,
    WkbTypeCodeValid, WkbZMVariant, WkbZVariant, WktCoordinateListInParens,
    WktCoordsSeparatedBySpace, WktDimensionTagPrecedesParens, WktEmptyApplicableToAllTypes,
    WktEmptyGeometry, WktGeometryCollectionProduction, WktKeywordCaseInsensitive, WktKeywordValid,
    WktLineStringProduction, WktMVariant, WktMultiLineStringProduction, WktMultiPointProduction,
    WktMultiPolygonProduction, WktNestingForMultiTypes, WktPointProduction,
    WktPolygonExteriorFirstRing, WktPolygonProduction, WktPositionsSeparatedByComma,
    WktRingsParenthesized, WktRingsSeparatedByComma, WktRoundTrip, WktZMVariant, WktZVariant,
};

pub use iso_19115::{
    CiAddressAdministrativeAreaOptional, CiAddressCityOptional, CiAddressCountryIsIso3166,
    CiAddressCountryOptional, CiAddressDeliveryPointOptional, CiAddressEmailOptional,
    CiAddressPostalCodeOptional, CiCitationAlternateTitleOptional,
    CiCitationCollectiveTitleOptional, CiCitationDateMandatory, CiCitationEditionDateOptional,
    CiCitationEditionOptional, CiCitationIdentifierOptional, CiCitationIsbnFormatValid,
    CiCitationIssnFormatValid, CiCitationOtherDetailsOptional, CiCitationPresentationFormOptional,
    CiCitationResponsiblePartyOptional, CiCitationSeriesOptional, CiCitationTitleMandatory,
    CiCitationTitleNonEmpty, CiCitationValid, CiContactAddressOptional,
    CiContactHoursOfServiceOptional, CiContactInstructionsOptional,
    CiContactOnlineResourceOptional, CiContactPhoneOptional, CiDateTypeAdopted,
    CiDateTypeCodeMandatory, CiDateTypeCreation, CiDateTypeDeprecated, CiDateTypeDistribution,
    CiDateTypeExpiry, CiDateTypeInForce, CiDateTypeLastRevision, CiDateTypeLastUpdate,
    CiDateTypeNextUpdate, CiDateTypePublication, CiDateTypeReleased, CiDateTypeRevision,
    CiDateTypeSuperseded, CiDateTypeUnavailable, CiDateTypeValidityBegins,
    CiDateTypeValidityExpires, CiDateValueMandatory, CiIndividualContactInfoOptional,
    CiIndividualNameOptional, CiIndividualNameOrPositionRequired, CiIndividualPositionNameOptional,
    CiOnlineFunctionBrowseGraphic, CiOnlineFunctionBrowsing, CiOnlineFunctionCompleteMetadata,
    CiOnlineFunctionDownload, CiOnlineFunctionEmailService, CiOnlineFunctionFileAccess,
    CiOnlineFunctionInformation, CiOnlineFunctionOfflineAccess, CiOnlineFunctionOrder,
    CiOnlineFunctionSearch, CiOnlineFunctionUpload, CiOnlineResourceApplicationProfileOptional,
    CiOnlineResourceDescriptionOptional, CiOnlineResourceFunctionOptional,
    CiOnlineResourceLinkageMandatory, CiOnlineResourceLinkageValidUrl,
    CiOnlineResourceNameOptional, CiOnlineResourceProtocolOptional,
    CiOrganisationContactInfoOptional, CiOrganisationIndividualOptional,
    CiOrganisationNameOptional, CiPartyIsAbstract, CiResponsibilityExtentOptional,
    CiResponsibilityPartyMandatory, CiResponsibilityPartyNameNonNull,
    CiResponsibilityRoleMandatory, CiResponsibilityValid, CiRoleAuthor, CiRoleCoAuthor,
    CiRoleCollaborator, CiRoleContributor, CiRoleCustodian, CiRoleDistributor, CiRoleEditor,
    CiRoleFunder, CiRoleMediator, CiRoleOriginator, CiRoleOwner, CiRolePointOfContact,
    CiRolePrincipalInvestigator, CiRoleProcessor, CiRolePublisher, CiRoleResourceProvider,
    CiRoleRightsHolder, CiRoleSponsor, CiRoleStakeholder, CiRoleUser, CiTelephoneFacsimile,
    CiTelephoneNumberMandatory, CiTelephoneNumberNonEmpty, CiTelephoneSms, CiTelephoneTypeVoice,
    DqAbsoluteExternalPositionalAccuracy, DqCompletenessCommission, DqCompletenessOmission,
    DqConceptualConsistency, DqConformanceResultPassMandatory,
    DqConformanceResultSpecificationMandatory, DqDataQualityReportOptional,
    DqDataQualityScopeMandatory, DqDataQualityStandaloneOptional, DqDomainConsistency,
    DqElementResultMandatory, DqFormatConsistency, DqGriddedDataPositionalAccuracy,
    DqNonQuantitativeAttributeCorrectness, DqQuantitativeAttributeAccuracy,
    DqQuantitativeResultValueNonEmpty, DqQuantitativeResultValueUnitMandatory,
    DqRelativeInternalPositionalAccuracy, DqTemporalConsistency, DqTemporalValidity,
    DqThematicClassificationCorrectness, DqTopologicalConsistency, DsAssociationTypeCrossReference,
    DsAssociationTypeIsComposedOf, DsAssociationTypeLargerWorkCitation,
    DsAssociationTypePartOfSeamlessDatabase, DsAssociationTypeRevisionOf, DsInitiativeTypeMission,
    DsInitiativeTypePlatform, DsInitiativeTypeProject, ExBboxEastBoundIsFinite,
    ExBboxEastBoundMandatory, ExBboxExtentTypeCodeOptional, ExBboxLatitudeRange,
    ExBboxLongitudeRange, ExBboxNorthBoundIsFinite, ExBboxNorthBoundMandatory,
    ExBboxSouthBoundIsFinite, ExBboxSouthBoundMandatory, ExBboxSouthLeNorth,
    ExBboxWestBoundIsFinite, ExBboxWestBoundMandatory, ExBboxWestLeEastOrAntimeridian,
    ExBoundingPolygonAtLeastOneGeometry, ExBoundingPolygonExtentTypeCodeOptional,
    ExBoundingPolygonGeometryIsValid, ExBoundingPolygonPolygonMandatory,
    ExExtentAtLeastOneElementRequired, ExExtentDescriptionOptional,
    ExExtentGeographicElementConditional, ExExtentTemporalElementOptional, ExExtentValid,
    ExExtentVerticalElementOptional, ExGeographicBoundingBoxValid, ExTemporalExtentExtentMandatory,
    ExTemporalExtentPeriodBeginLeEnd, ExVerticalExtentCrsOptional, ExVerticalExtentMaxIsFinite,
    ExVerticalExtentMaximumMandatory, ExVerticalExtentMinIsFinite, ExVerticalExtentMinLeMax,
    ExVerticalExtentMinimumMandatory, Iso19115AllMandatoryElementsPresent,
    Iso19115CitationTitleNeverEmpty, Iso19115ConditionalElementsTriggered,
    Iso19115ContactPartyNameNonNull, Iso19115CountryCodeIso3166, Iso19115DateIso8601Format,
    Iso19115EnumerationValuesValid, Iso19115LanguageCodeIso6392,
    Iso19115MultiplicityConstraintsMet, Iso19115ProcessStepDescriptionNeverEmpty,
    LiLineageAdditionalDocumentationOptional, LiLineageAtLeastOneProvided,
    LiLineageProcessStepOptional, LiLineageScopeOptional, LiLineageSourceOptional,
    LiLineageStatementConditional, LiLineageValid, LiProcessStepDateTimeOptional,
    LiProcessStepDescriptionMandatory, LiProcessStepDescriptionNonEmpty,
    LiProcessStepProcessorOptional, LiProcessStepRationaleOptional, LiProcessStepReferenceOptional,
    LiProcessStepScopeOptional, LiProcessStepSourceOptional, LiSourceCitationOptional,
    LiSourceDescriptionConditional, LiSourceDescriptionOrCitationRequired,
    LiSourceReferenceSystemOptional, LiSourceSpatialResolutionOptional, LiSourceStepOptional,
    MdAssociatedResourceAssociationTypeMandatory, MdAssociatedResourceInitiativeTypeOptional,
    MdAssociatedResourceMetadataRefConditional, MdAssociatedResourceNameConditional,
    MdAssociatedResourceNameOrMetaRefRequired, MdBrowseGraphicFileDescriptionOptional,
    MdBrowseGraphicFileNameMandatory, MdBrowseGraphicFileNameNonEmpty,
    MdBrowseGraphicFileTypeOptional, MdBrowseGraphicLinkageOptional, MdCharsetArabic,
    MdCharsetBig5, MdCharsetCyrillic, MdCharsetEucJp, MdCharsetGb2312, MdCharsetGreek,
    MdCharsetHebrew, MdCharsetLatin1, MdCharsetLatin2, MdCharsetLatin5, MdCharsetShiftJis,
    MdCharsetUcs2, MdCharsetUcs4, MdCharsetUsAscii, MdCharsetUtf8, MdCharsetUtf16, MdCharsetUtf32,
    MdClassificationConfidential, MdClassificationForOfficialUseOnly,
    MdClassificationLimitedDistribution, MdClassificationProtected, MdClassificationRestricted,
    MdClassificationSecret, MdClassificationSensitiveButUnclassified, MdClassificationTopSecret,
    MdClassificationUnclassified, MdConstraintsApplicationScopeOptional,
    MdConstraintsUseLimitationOptional, MdDataIdentificationCharacterSetConditional,
    MdDataIdentificationExtentConditional, MdDataIdentificationLanguageConditional,
    MdDataIdentificationSpatialResolutionOptional, MdDataIdentificationSupplementalInfoOptional,
    MdDataIdentificationTopicCategoryConditional, MdDimensionNameColumn, MdDimensionNameMandatory,
    MdDimensionNameRow, MdDimensionNameTime, MdDimensionNameVertical,
    MdDimensionResolutionOptional, MdDimensionSizeMandatory, MdDimensionSizePositive,
    MdDistributionAtLeastOneElement, MdDistributionDistributorOptional,
    MdDistributionFormatOptional, MdDistributionTransferOptionsOptional,
    MdDistributorContactMandatory, MdDistributorFormatOptional, MdDistributorOrderProcessOptional,
    MdDistributorTransferOptionsOptional, MdFormatAmendmentNumberOptional,
    MdFormatDistributorOptional, MdFormatFileDecompressionOptional, MdFormatMediumOptional,
    MdFormatSpecificationCitationMandatory, MdGridSpatialRepAxisDimensionProperties,
    MdGridSpatialRepCellGeometry, MdGridSpatialRepNumberOfDimensions,
    MdGridSpatialRepNumberOfDimensionsPositive, MdGridSpatialRepTransformationAvailable,
    MdIdentificationAbstractMandatory, MdIdentificationAbstractNonEmpty,
    MdIdentificationCitationMandatory, MdIdentificationCreditOptional,
    MdIdentificationDescriptiveKeywordsOptional, MdIdentificationGraphicOverviewOptional,
    MdIdentificationPointOfContactOptional, MdIdentificationPurposeOptional,
    MdIdentificationResourceConstraintsOptional, MdIdentificationResourceFormatOptional,
    MdIdentificationResourceMaintenanceOptional, MdIdentificationStatusOptional,
    MdIdentificationValid, MdKeywordTypeDataCentre, MdKeywordTypeDiscipline,
    MdKeywordTypeFeatureType, MdKeywordTypeInstrument, MdKeywordTypePlace, MdKeywordTypePlatform,
    MdKeywordTypeProcess, MdKeywordTypeProduct, MdKeywordTypeProject, MdKeywordTypeService,
    MdKeywordTypeStratum, MdKeywordTypeSubTopicCategory, MdKeywordTypeTaxon, MdKeywordTypeTemporal,
    MdKeywordTypeTheme, MdKeywordsKeywordClassOptional, MdKeywordsKeywordMandatory,
    MdKeywordsThesaurusNameOptional, MdKeywordsTypeOptional,
    MdLegalConstraintsAccessConstraintsOptional, MdLegalConstraintsOtherConstraintsConditional,
    MdLegalConstraintsUseConstraintsOptional, MdMaintenanceContactOptional,
    MdMaintenanceDateOptional, MdMaintenanceFrequencyAnnually, MdMaintenanceFrequencyAsNeeded,
    MdMaintenanceFrequencyContinual, MdMaintenanceFrequencyDaily, MdMaintenanceFrequencyIrregular,
    MdMaintenanceFrequencyMandatory, MdMaintenanceFrequencyMonthly,
    MdMaintenanceFrequencyNotPlanned, MdMaintenanceFrequencyQuarterly,
    MdMaintenanceFrequencyUnknown, MdMaintenanceFrequencyWeekly, MdMaintenanceNoteOptional,
    MdMaintenanceScopeOptional, MdMaintenanceUserDefinedFreqConditional,
    MdMediumDensityUnitsConditional, MdMediumVolumesOptional, MdMetadataCharacterSetConditional,
    MdMetadataConstraintsOptional, MdMetadataContactMandatory, MdMetadataContactPartyNameNonNull,
    MdMetadataDataQualityInfoOptional, MdMetadataDateInfoMandatory,
    MdMetadataDistributionInfoOptional, MdMetadataFileIdentifierOptional,
    MdMetadataHierarchyLevelNameMatchesLevel, MdMetadataHierarchyLevelScopeCode,
    MdMetadataIdentificationInfoMandatory, MdMetadataLanguageConditional, MdMetadataLocaleOptional,
    MdMetadataMaintenanceOptional, MdMetadataParentIdentifierOptional,
    MdMetadataReferenceSystemInfoOptional, MdMetadataResourceLineageOptional,
    MdMetadataSpatialRepresentationInfoOptional, MdMetadataStandardNameOptional,
    MdMetadataStandardVersionOptional, MdMetadataValid, MdProgressCodeAccepted,
    MdProgressCodeCompleted, MdProgressCodeDeprecated, MdProgressCodeFinal,
    MdProgressCodeHistoricalArchive, MdProgressCodeNotAccepted, MdProgressCodeObsolete,
    MdProgressCodeOnGoing, MdProgressCodePending, MdProgressCodePlanned, MdProgressCodeProposed,
    MdProgressCodeRequired, MdProgressCodeRetired, MdProgressCodeSuperseded,
    MdProgressCodeTentative, MdProgressCodeUnderDevelopment, MdProgressCodeValid,
    MdProgressCodeWithdrawn, MdReferenceSystemIdentifierOptional, MdReferenceSystemTypeOptional,
    MdRepresentativeFractionDenominatorMandatory, MdRepresentativeFractionDenominatorPositive,
    MdResolutionDistanceIsFinite, MdResolutionDistanceIsPositive,
    MdResolutionEquivalentScaleOrDistance, MdResolutionScaleImpliesSmallIsCoarse,
    MdRestrictionConfidentialCode, MdRestrictionCopyrightCode, MdRestrictionInConfidenceCode,
    MdRestrictionIntellectualPropertyCode, MdRestrictionLicenceCode,
    MdRestrictionLicenceDistributorCode, MdRestrictionLicenceEndUserCode,
    MdRestrictionLicenceUnrestrictedCode, MdRestrictionOtherRestrictionsCode,
    MdRestrictionPatentCode, MdRestrictionPatentPendingCode, MdRestrictionPrivateCode,
    MdRestrictionRestrictedCode, MdRestrictionSbuCode, MdRestrictionStatutoryCode,
    MdRestrictionTrademarkCode, MdRestrictionUnrestrictedCode, MdScopeAttribute,
    MdScopeAttributeType, MdScopeCollectionSession, MdScopeDataset, MdScopeDimensionGroup,
    MdScopeFeature, MdScopeFeatureType, MdScopeFieldSession, MdScopeInitiative, MdScopeModel,
    MdScopeNonGeographicDataset, MdScopeSeries, MdScopeService, MdScopeSoftware, MdScopeTile,
    MdSecurityConstraintsClassSystemOptional, MdSecurityConstraintsClassificationMandatory,
    MdSecurityConstraintsHandlingDescOptional, MdSecurityConstraintsUserNoteOptional,
    MdSpatialRepTypeGrid, MdSpatialRepTypeStereoModel, MdSpatialRepTypeTextTable,
    MdSpatialRepTypeTin, MdSpatialRepTypeVector, MdSpatialRepTypeVideo, MdTopicCategoryBiota,
    MdTopicCategoryBoundaries, MdTopicCategoryClimatologyMeteorologyAtmosphere,
    MdTopicCategoryDisaster, MdTopicCategoryEconomy, MdTopicCategoryElevation,
    MdTopicCategoryEnvironment, MdTopicCategoryExtraTerrestrial, MdTopicCategoryFarming,
    MdTopicCategoryGeoscientificInformation, MdTopicCategoryHealth,
    MdTopicCategoryImageryBaseMapsEarthCover, MdTopicCategoryInlandWaters,
    MdTopicCategoryIntelligenceMilitary, MdTopicCategoryLocation, MdTopicCategoryOceans,
    MdTopicCategoryPlanningCadastre, MdTopicCategorySociety, MdTopicCategoryStructure,
    MdTopicCategoryTransportation, MdTopicCategoryUtilitiesCommunication,
    MdTransferOptionsOfflineOptional, MdTransferOptionsOnlineOptional,
    MdTransferOptionsSizeIsFinite, MdTransferOptionsSizePositive,
    MdVectorSpatialRepGeometricObjects, MdVectorSpatialRepTopologyLevel,
    PtLocaleCharacterEncodingMandatory, PtLocaleCountryOptional,
    PtLocaleLanguageCodeThreeLetterLowercase, PtLocaleLanguageMandatory,
};

pub use rfc7946::{
    AllPositionsInGeometryHaveConsistentDimension, AntimeridianCrossingGeometriesShouldBeSplit,
    AntimeridianCutPreservesTopology, AntimeridianLineStringSplitsToMultiLineString,
    AntimeridianNoLongitudeOutsideRange, AntimeridianPolygonSplitsToMultiPolygon,
    AntimeridianSplitPartDoesNotCrossLine, Bbox2dHasExactlyFourElements,
    Bbox2dOrderIsMinLonMinLatMaxLonMaxLat, Bbox3dHasExactlySixElements,
    Bbox3dOrderIsMinLonMinLatMinAltMaxLonMaxLatMaxAlt, BboxAllElementsAreJsonNumbers,
    BboxAntimeridianWestValueMayExceedEast, BboxDimensionMatchesGeometryDimension,
    BboxEdgesFollowConstantCoordinateLines, BboxElementsAreFinite, BboxLatitudeMustNotBelowNeg90,
    BboxLatitudeMustNotExceed90, BboxLengthIsTwiceN, BboxMemberIsOptional, BboxMinAltLeMaxAlt,
    BboxMinLatLeMaxLat, BboxMustNotUseOutOfRangeLatForSphericalCap,
    BboxShouldContainAllGeometryPositions, BboxSouthwestCornerPrecedesNortheast,
    BboxWhenPresentIsJsonArray, CoordPrecisionMustNotImplyAccuracyLevel,
    CoordPrecisionNotInDmsFormat, CoordPrecisionNotInSexagesimalFormat,
    CoordPrecisionSixDecimalPlacesIsSufficient, CoordinatePrecisionMustNotImplyUncertainty,
    CoordinatesAreInDecimalDegreesOnly, CrsAbsentAltitudeTreatedAsSurface,
    CrsAlternativeForbiddenWithoutArrangement, CrsAltitudeIsAboveWgs84Ellipsoid,
    CrsAxisOrderLatitudeSecond, CrsAxisOrderLongitudeFirst, CrsEquivalentToOgcUrn,
    CrsMemberMustNotAppearInDocument, CrsNoEpsgCodesPermitted, CrsNoNamedCrsObjectPermitted,
    CrsOnlyWgs84IsPermitted, DigitCountIsNotDataAccuracyIndicator,
    ExistingGeometrySemanticsMustNotChange, FeatureCollectionConsistentCoordinateDimension,
    FeatureCollectionEachElementIsFeatureObject, FeatureCollectionEachElementIsNotNull,
    FeatureCollectionFeaturesIsJsonArray, FeatureCollectionFeaturesIsNotNull,
    FeatureCollectionFeaturesIsNotSingleFeature, FeatureCollectionHasFeaturesMember,
    FeatureCollectionIdIsNotRequired, FeatureCollectionMayBeEmpty,
    FeatureCollectionSemanticsMustNotChange, FeatureCollectionTypeEqualsFeatureCollection,
    FeatureCollectionValid, FeatureGeometryIsGeometryObjectOrNull,
    FeatureGeometryWhenPresentIsValidGeometry, FeatureHasGeometryMember,
    FeatureHasPropertiesMember, FeatureIdMemberIsOptional, FeatureIdMustNotBeArray,
    FeatureIdMustNotBeBoolean, FeatureIdMustNotBeNull, FeatureIdMustNotBeObject,
    FeatureIdNumberIsAllowed, FeatureIdStringIsAllowed,
    FeatureIdUniquenessWithinCollectionRecommended, FeatureIdWhenPresentIsStringOrNumber,
    FeatureNullGeometryMeansUnlocated, FeaturePropertiesIsJsonObjectOrNull,
    FeatureSemanticsMustNotChange, FeatureTypeEqualsFeature, FeatureValid, FileExtensionIsGeojson,
    ForeignMembersAtAnyLevelShouldBeIgnored, ForeignMembersCannotOverrideTypeMember,
    ForeignMembersDoNotAlterSemantics, FullRfc7946Compliance, GeoJsonBboxMemberIsOptional,
    GeoJsonBboxWhenPresentIsArray, GeoJsonDocumentValid, GeoJsonForeignMembersShouldBeIgnored,
    GeoJsonGeometryCollectionMayBeEmpty, GeoJsonGeometryCollectionValid, GeoJsonGeometryValid,
    GeoJsonLineStringValid, GeoJsonMultiLineStringMayBeEmpty, GeoJsonMultiLineStringValid,
    GeoJsonMultiPointValid, GeoJsonMultiPolygonMayBeEmpty, GeoJsonMultiPolygonValid,
    GeoJsonObjectHasTypeMember, GeoJsonObjectMustNotUseNullType,
    GeoJsonObjectTypeMemberNeverMissing, GeoJsonPointMappableToGeoUri, GeoJsonPointValid,
    GeoJsonPolygonValid, GeoJsonRootIsObject, GeoJsonTextIsSingleJsonValue,
    GeoJsonTypeIsCaseSensitive, GeoJsonTypeIsNotExtensible, GeoJsonTypeIsOneOfNineValues,
    GeoJsonTypeMemberIsNotNull, GeoJsonTypeMemberIsString, GeoUriMappableToGeoJsonPoint,
    GeometryCollectionEachElementIsValidGeometry, GeometryCollectionEachGeometryHasTypeMember,
    GeometryCollectionGeometriesIsJsonArray, GeometryCollectionGeometriesIsNotNull,
    GeometryCollectionHasGeometriesMember, GeometryCollectionMustNotHaveCoordinatesMember,
    GeometryCollectionShouldNotBeNested, GeometryCollectionShouldNotReplaceMultiXType,
    GeometryCollectionTypeEqualsGeometryCollection, GeometryTypeValueMatchesCoordinateStructure,
    IJsonNoBomShouldBeAdded, IJsonNoDuplicateKeysAllowed, IJsonNoInfinityValues, IJsonNoNaNValues,
    IJsonNoUnescapedControlCharacters, IJsonNumbersMustBeIeee754Representable,
    IJsonStringsAreUnicode, IJsonUtf8EncodingRequired, LineStringCoordinatesHasMinTwoPositions,
    LineStringCoordinatesIsArray, LineStringCoordinatesIsNotEmpty, LineStringCoordinatesIsNotNull,
    LineStringEachElementIsValidPosition, LineStringHasCoordinatesMember,
    LineStringMinTwoPositionsFormPath, LineStringTypeEqualsLineString, MediaTypeCharsetIsUtf8,
    MediaTypeIsApplicationGeoJson, MediaTypeNotApplicationJson, MultiLineStringCoordinatesIsArray,
    MultiLineStringCoordinatesIsNotNull, MultiLineStringEachElementIsArray,
    MultiLineStringEachLineStringHasMinTwoPositions, MultiLineStringEachPositionIsValid,
    MultiLineStringHasCoordinatesMember, MultiLineStringTypeEqualsMultiLineString,
    MultiPointCoordinatesIsArrayOfPositions, MultiPointCoordinatesIsNotNull,
    MultiPointCoordinatesMayBeEmpty, MultiPointEachElementIsValidPosition,
    MultiPointHasCoordinatesMember, MultiPointTypeEqualsMultiPoint, MultiPolygonCoordinatesIsArray,
    MultiPolygonCoordinatesIsNotNull, MultiPolygonEachElementIsPolygonCoordinates,
    MultiPolygonEachPolygonObeysPolygonRules, MultiPolygonHasCoordinatesMember,
    MultiPolygonTypeEqualsMultiPolygon, NoNewGeometryTypesMayBeDefined,
    NoProjectedCoordinatesPermitted, NullGeometryDistinctFromAbsentGeometry,
    PointCoordinatesHasMinTwoElements, PointCoordinatesIsNotNestedArray, PointCoordinatesIsNotNull,
    PointCoordinatesIsSinglePosition, PointHasCoordinatesMember, PointTypeEqualsPoint,
    PolygonCoordinatesHasAtLeastOneRing, PolygonCoordinatesIsArrayOfRings,
    PolygonCoordinatesIsNotNull, PolygonExteriorRingHasPositiveSignedArea,
    PolygonExteriorRingIsCounterclockwise, PolygonFirstRingIsExteriorBoundary,
    PolygonHasCoordinatesMember, PolygonHoleRingHasNegativeSignedArea,
    PolygonHoleRingsAreClockwise, PolygonHolesAreInteriorToExteriorRing, PolygonHolesDoNotOverlap,
    PolygonLinearRingFirstAndLastAreIdentical, PolygonLinearRingHasMinFourPositions,
    PolygonLinearRingIsClosedLineString, PolygonLinearRingRepresentationShouldBeIdentical,
    PolygonRightHandRuleAreaToLeft, PolygonRingDoesNotSelfIntersect,
    PolygonSubsequentRingsAreInteriorHoles, PolygonTypeEqualsPolygon, PositionAltitudeIsFinite,
    PositionAltitudeReferencesWgs84Ellipsoid, PositionElementOneIsLatitude,
    PositionElementTwoIsAltitudeWhenPresent, PositionElementZeroIsLongitude,
    PositionElementsAreJsonNumbers, PositionExtraElementsBeyondThreeIgnored,
    PositionHasAtLeastTwoElements, PositionInterpolationIsCartesian, PositionIsJsonArray,
    PositionIsNotJsonNull, PositionIsNotJsonNumber, PositionIsNotJsonObject,
    PositionIsNotJsonString, PositionLatitudeInRange, PositionLatitudeIsFinite,
    PositionLongitudeInRange, PositionLongitudeIsFinite, PositionShouldNotExceedThreeElements,
    PositionValid, PropertiesIsPreferredLocationForAppData,
};

pub use fgdc::{
    FgdcAccessConstraintsPresent, FgdcAltitudeDatumNamePresent, FgdcAltitudeDistanceUnitsPresent,
    FgdcAltitudeEncodingMethodPresent, FgdcAltitudeResolutionAtLeastOne,
    FgdcArcZoneIdentifier1To18, FgdcAttributeAccuracyReportPresent, FgdcAttributeDefinitionPresent,
    FgdcAttributeDefinitionSourcePresent, FgdcAttributeDomainTypeExclusive,
    FgdcAttributeHasAtLeastOneDomain, FgdcAttributeLabelPresent,
    FgdcAttributeMeasurementResolutionPositive, FgdcBoundingEastCoordInRange,
    FgdcBoundingNorthCoordInRange, FgdcBoundingNorthGeqSouth, FgdcBoundingSouthCoordInRange,
    FgdcBoundingWestCoordInRange, FgdcBrowseGraphicFileDescriptionPresent,
    FgdcBrowseGraphicFileNamePresent, FgdcBrowseGraphicFileTypePresent,
    FgdcCalendarDateIsYyyymmddOrToken, FgdcCitationHasAtLeastOneOriginator, FgdcCitationInfoValid,
    FgdcCitationOriginatorNonEmpty, FgdcCitationPublicationDateIsYyyymmddOrToken,
    FgdcCitationPublicationDatePresent, FgdcCitationTitleNonEmpty, FgdcCitationTitlePresent,
    FgdcCloudCoverZeroToHundred, FgdcCodesetNamePresent, FgdcCodesetSourcePresent,
    FgdcContactAddressCityPresent, FgdcContactAddressPostalCodePresent,
    FgdcContactAddressStatePresent, FgdcContactAddressTypeCodeValid,
    FgdcContactHasAtLeastOneAddress, FgdcContactHasAtLeastOneVoiceTelephone,
    FgdcContactHasPersonOrOrganizationPrimary, FgdcContactInfoValid,
    FgdcDataQualityCompletenessReportPresent, FgdcDataQualityLineagePresent,
    FgdcDataQualityLogicalConsistencyPresent, FgdcDataQualitySectionValid,
    FgdcDepthDatumNamePresent, FgdcDepthDistanceUnitsPresent, FgdcDepthEncodingMethodPresent,
    FgdcDepthResolutionAtLeastOne, FgdcDescriptionAbstractPresent, FgdcDescriptionPurposePresent,
    FgdcDialupDataBitsSevenOrEight, FgdcDialupHighestBpsGtLowest, FgdcDialupLowestBpsGeq110,
    FgdcDialupParityCodeValid, FgdcDialupStopBitsOneOrTwo, FgdcDigitalFormatNamePresent,
    FgdcDirectSpatialRefMethodCodeValid, FgdcDistributionDistributorPresent,
    FgdcDistributionLiabilityPresent, FgdcDistributionSectionValid,
    FgdcEntityAttributeHasDetailedOrOverview, FgdcEntityAttributeSectionValid,
    FgdcEntityTypeDefinitionPresent, FgdcEntityTypeDefinitionSourcePresent,
    FgdcEntityTypeLabelPresent, FgdcEnumeratedDomainHasAtLeastOneValue,
    FgdcEnumeratedDomainValueDefinitionPresent, FgdcEnumeratedDomainValueDefinitionSourcePresent,
    FgdcEnumeratedDomainValuePresent, FgdcGPolygonOuterRingHasAtLeastFourPoints,
    FgdcGRingLatitudeInRange, FgdcGRingLongitudeInRange, FgdcGeodeticModelEllipsoidNamePresent,
    FgdcGeodeticModelFlatteningRatioDenominatorPositive, FgdcGeodeticModelSemiMajorAxisPositive,
    FgdcGeographicCoordUnitsCodeValid, FgdcGeographicLatResolutionPositive,
    FgdcGeographicLonResolutionPositive, FgdcHorizAccuracyAssessmentPaired,
    FgdcHorizCrsTypeIsGeographicPlanarOrLocal, FgdcIdentificationSectionValid,
    FgdcKeywordsHasAtLeastOneTheme, FgdcLineageHasAtLeastOneProcessStep,
    FgdcMapProjAzimuthalAngle0To360, FgdcMapProjCentralMeridianInRange,
    FgdcMapProjLatitudeOriginInRange, FgdcMapProjNamePresent, FgdcMapProjScaleFactorPositive,
    FgdcMapProjStandardParallelInRange, FgdcMetadataContactPresent, FgdcMetadataDatePresent,
    FgdcMetadataFutureReviewDateAfterReviewDate, FgdcMetadataHasIdentificationSection,
    FgdcMetadataHasMetadataReferenceSection, FgdcMetadataReferenceSectionValid,
    FgdcMetadataReviewDateAfterMetadataDate, FgdcMetadataSecurityClassificationCodeValid,
    FgdcMetadataStandardNamePresent, FgdcMetadataStandardVersionPresent,
    FgdcMetadataTimeConventionCodeValid, FgdcOfflineMediaCodeValid,
    FgdcOverviewDescriptionTextPresent, FgdcOverviewDetailCitationAtLeastOne,
    FgdcPlaceHasAtLeastOneKeyword, FgdcPlaceHasKeywordThesaurus,
    FgdcPositionalAccuracyHasAtLeastOneComponent, FgdcProcessStepDateFgdcFormat,
    FgdcProcessStepDatePresent, FgdcProcessStepDescriptionPresent,
    FgdcPvectInfoIsSdtsOrVpfExclusive, FgdcQaaValueAndExplanationPaired,
    FgdcRangeDomainMaximumPresent, FgdcRangeDomainMinimumLeMaximum, FgdcRangeDomainMinimumPresent,
    FgdcRangeEndingDateAfterBeginning, FgdcRasterColumnCountPositive,
    FgdcRasterObjectTypeCodeValid, FgdcRasterRowCountPositive, FgdcRasterVerticalCountPositive,
    FgdcRecordValid, FgdcRecordingDensityPositive, FgdcRecordingFormatCodeValid,
    FgdcSdtsObjectCountPositive, FgdcSdtsObjectTypeCodeValid, FgdcSecurityClassificationCodeValid,
    FgdcSecurityClassificationSystemPresent, FgdcSecurityHandlingDescriptionPresent,
    FgdcSourceCitationAbbreviationPresent, FgdcSourceCitationPresent,
    FgdcSourceContributionPresent, FgdcSourceMediaTypePresent, FgdcSourceScaleDenominatorGt1,
    FgdcSourceTimePeriodPresent, FgdcSpatialDataOrgSectionValid, FgdcSpatialReferenceSectionValid,
    FgdcStandardOrderFeesPresent, FgdcStandardOrderHasFormNondigitalOrDigital,
    FgdcStatusProgressCodeValid, FgdcStatusUpdateFrequencyCodeValid,
    FgdcStratumHasAtLeastOneKeyword, FgdcStratumHasKeywordThesaurus,
    FgdcTemporalKeywordHasAtLeastOneKeyword, FgdcTemporalKeywordHasThesaurus,
    FgdcThemeHasAtLeastOneKeyword, FgdcThemeHasKeywordThesaurus,
    FgdcTimeOfContentCurrentnessReferenceValid, FgdcTimeOfContentTimePeriodPresent,
    FgdcTimePeriodInfoValid, FgdcTimePeriodTypeExclusive, FgdcTransferSizePositive,
    FgdcUpsZoneIdentifierCodeValid, FgdcUseConstraintsPresent, FgdcUtmZoneNumberInRange,
    FgdcVertAccuracyAssessmentPaired, FgdcVpfObjectTypeCodeValid, FgdcVpfTopologyLevelZeroToThree,
};
