//! Contracts re-exports.

pub mod iso_19111;

pub use iso_19111::{
    AngularAxisMustUseAngularUnit,
    AxisAbbreviationNonEmpty,
    AxisAbbreviationUniqueInCs,
    AxisAbbreviationUniqueWithinCs,
    AxisDirectionIsValidCode,
    AxisDirectionMemberOfCodeList,
    AxisMinMaxValueOptional,
    AxisNameNonEmpty,
    AxisOrderChangeRequiresExplicitOperation,
    AxisOrderMustFollowCrsDefinition,
    AxisRangeMeaningExactOrWraparound,
    AxisUnitAppropriateForAxisType,
    CompoundCrsComponentsNonOverlapping,
    CompoundCrsComponentsOrthogonal,
    CompoundCrsEpsgRange6000To6999,
    // §12 Compound CRS
    CompoundCrsHasAtLeastTwoComponents,
    CompoundCrsMinimumTwoComponents,
    CompoundCrsNameNonEmpty,
    CompoundCrsNoTwoHorizontalComponents,
    CompoundCrsNoTwoVerticalComponents,
    CompoundCrsTotalAxisCountIsSumOfComponents,
    CompoundCrsTypicalIs2dPlusVertical,
    ConcatenatedOperationHasAtLeastTwoSteps,
    ConcatenatedOperationMinimumTwoSteps,
    ConcatenatedOperationSourceCrsIsFirstStep,
    ConcatenatedOperationStepsFormAChain,
    ConcatenatedOperationTargetCrsIsLastStep,
    ConversionDefinesMapProjection,
    ConversionHasOperationMethod,
    ConversionHasParameterValues,
    ConversionInverseExists,
    ConversionInvolvesNoDatumChange,
    CoordinateElementAlignedToAxisOrdinalPosition,
    CoordinateEpochDistinctFromFrameReferenceEpoch,
    CoordinateEpochIsDecimalYear,
    CoordinateEpochPositiveFinite,
    CoordinateMetadataApplicableAtSetOrTupleLevel,
    CoordinateMetadataCrsNonNull,
    CoordinateMetadataDynamicCrsRequiresEpoch,
    CoordinateMetadataEpochIsDecimalYear,
    // §23 CoordinateMetadata
    CoordinateMetadataHasCrs,
    CoordinateMetadataStaticCrsEpochShouldBeAbsent,
    CoordinateMetadataValid,
    CoordinateOperationDomainOfValidityOptional,
    CoordinateOperationHasSourceCrs,
    CoordinateOperationHasTargetCrs,
    CoordinateOperationInheritsIdentifiedObjectInterface,
    // §14 Coordinate operations
    CoordinateOperationNameNonEmpty,
    CoordinateOperationVersionOptional,
    // §8 Coordinate system
    CoordinateSystemAxisCountOneToFour,
    CoordinateSystemMaximumFourAxes,
    // §20 Additional value constraints
    CoordinateSystemMinimumOneAxis,
    CoordinateSystemNameNonEmpty,
    CoordinateTupleDimensionMatchesAxes,
    CoordinateTupleElementCountEqualsAxisCount,
    CoordinatesTransformed,
    // §6 CRS general
    CrsConsistsOfCsAndDatum,
    CrsDomainOfValidityExtentTypes,
    CrsDomainOfValidityOptionalImpliesGlobal,
    CrsIdentifierAuthorityNonEmpty,
    CrsIdentifierCodeNonEmpty,
    // §18 Cross-cutting
    CrsIdentityAuthorityPlusCodeUnique,
    CrsIdentityByAuthorityAndCode,
    CrsInheritsIdentifiedObjectInterface,
    CrsMandatoryStringNonNull,
    // Trait operation contracts
    CrsResolved,
    CrsScopeDescribesIntendedUse,
    CrsStringValuesUtf8Encoded,
    CrsTypeMemberOfDefinedTypes,
    CrsValid,
    CsAxisCountMatchesTupleDimensionality,
    CsTypeMemberOfDefinedTypes,
    DatumEnsembleAccuracyPositive,
    // §22 DatumEnsemble
    DatumEnsembleGroupsRelatedDatums,
    DatumEnsembleHasAtLeastTwoMembers,
    DatumEnsembleMemberNoNullEntries,
    DatumEnsembleMembersHomogeneous,
    DatumEnsembleNameNonEmpty,
    DatumEnsembleResolved,
    DatumEnsembleSubMetreRequiresMemberSelection,
    DatumEnsembleWgs84EpsgCode6326,
    DatumInheritsIdentifiedObjectInterface,
    DerivedCrsCsDiffersFromBaseCrsAllowed,
    DerivedCrsDerivingConversionIsConversion,
    // §13 Derived CRS
    DerivedCrsHasBaseCrs,
    DerivedCrsInheritsDatumFromBase,
    DerivedCrsNameNonEmpty,
    DerivedProjectedCrsBaseMustBeProjCrs,
    DifferentCrsCodesRequireExplicitOperation,
    DynamicCrsOmittingEpochIntroducesError,
    DynamicCrsRequiresCoordinateEpoch,
    DynamicReferenceFrameHasFrameReferenceEpoch,
    EllipsoidInverseFlatteningPositiveWhenNonSphere,
    EllipsoidInverseFlatteningZeroMeansSphere,
    EllipsoidIsSphereConsistentWithParameters,
    // §7.3 Ellipsoid
    EllipsoidNameNonEmpty,
    EllipsoidSecondParameterEitherInverseFlatteningOrSemiMinor,
    EllipsoidSemiMajorAxisInMetres,
    EllipsoidSemiMajorAxisPositive,
    EllipsoidSemiMinorAxisInMetres,
    EllipsoidSemiMinorAxisLessThanSemiMajor,
    EllipsoidValid,
    EllipsoidWgs84InverseFlatteningApprox298,
    EngineeringCrsCsTypeFlexible,
    // §11 Engineering CRS
    EngineeringCrsDatumIsEngineeringDatum,
    EngineeringCrsIsLocalContextOnly,
    EngineeringCrsNameNonEmpty,
    EngineeringDatumAnchorOptional,
    EngineeringDatumNameNonEmpty,
    Epsg4326AxisOrderLatFirst,
    Epsg4326LatitudeRangeValid,
    Epsg4326LongitudeRangeValid,
    Epsg4326UsesDatumEnsemble,
    Epsg4978IsWgs84Geocentric,
    Epsg4978XAxisTowardsPrimeMeridian,
    Epsg4978ZAxisTowardsNorthPole,
    Epsg4979HeightUnbounded,
    Epsg4979IsWgs84Geographic3d,
    EpsgAuthorityNameIsEpsg,
    // §16 EPSG registry
    EpsgCodePositiveInteger,
    EpsgCompoundCrsRange6000To6999,
    EpsgGeographicCrsRange4000To4999,
    EpsgProjectedCrsRange20000To32767,
    EpsgVerticalCrsRange5000To5999,
    GeocentricCrsUsesCartesianCs,
    GeodeticCrsCsIsEllipsoidalOrCartesian,
    // §7 Geodetic CRS
    GeodeticCrsDatumIsGeodeticReferenceFrame,
    GeodeticReferenceFrameAnchorOptional,
    GeodeticReferenceFrameHasExactlyOneEllipsoid,
    GeodeticReferenceFrameHasExactlyOnePrimeMeridian,
    // §7.2 Reference frame
    GeodeticReferenceFrameNameNonEmpty,
    GeodeticReferenceFrameRealizationEpochIsIso8601,
    Geographic2dCrsHasTwoAxes,
    // §15 Axis order
    Geographic2dIsoAxisOrderLatitudeFirst,
    Geographic3dCrsHasThreeAxes,
    Geographic3dIsoAxisOrderLatLonHeight,
    // §27 Grid-based datum shifts
    GridBasedDatumShiftUsesExternalFile,
    HelmertConventionMustBeIdentified,
    HelmertConventionsEquivalentOnlyForZeroRotation,
    HelmertCoordinateFrameConvention,
    HelmertEpsgMethodCodes9606And9607,
    HelmertPositionVectorConvention,
    // §26 Helmert conventions
    HelmertSevenParameterStructure,
    IdentifiedObjectAliasNoNullEntries,
    IdentifiedObjectAliasOptionalList,
    IdentifiedObjectIdentifierEntryComplete,
    // §21 IO_IdentifiedObject
    IdentifiedObjectPrimaryNameNonEmpty,
    IdentifiedObjectRemarksOptional,
    IdentifiedObjectRemarksWhenPresentNonNull,
    Igs20IsDynamicDatum,
    Itrf2014IsDynamicDatum,
    Itrf2020IsDynamicDatum,
    LatitudePolesValid,
    LatitudeRangeNegative90To90,
    LinearAxisMustUseLinearUnit,
    LongitudeNegative180Excluded,
    LongitudeRangeNegative180To180,
    MapProjectionFalseOriginFiniteReal,
    MapProjectionScaleFactorPositive,
    MolodenskyBadenkasTenParameter,
    Nad27EnsembleEpsg6267,
    Nadcon5IsUsHorizontalDatumShift,
    Ntv2IsGridHorizontalShift,
    NullAuthorityCodeInvalidForRegisteredCrs,
    OgcAuthorityNameIsOgc,
    OperationMethodFormulaOptional,
    OperationMethodHasParameterList,
    OperationMethodNameNonEmpty,
    OperationParameterNameNonEmpty,
    OperationParameterValueHasUnit,
    OtherAuthorityNamesEsriIgnf,
    ParameterFileStoresFilenameNotValue,
    ParametricAxisMustUseParametricUnit,
    ParametricCrsCsIsParametricCs,
    ParametricCrsDatumIsParametricDatum,
    ParametricCrsHasOneAxis,
    PassThroughOperationCompoundCrsUsage,
    PassThroughOperationDimensionConsistency,
    PassThroughOperationIndexInRange,
    PassThroughOperationInnerOperationNonNull,
    PassThroughOperationModifiedCoordinatesNonEmpty,
    // §24 PassThroughOperation
    PassThroughOperationPreservesSomeAxes,
    PrimeMeridianGreenwichIsZero,
    PrimeMeridianGreenwichLongitudeFinite,
    PrimeMeridianGreenwichLongitudeInDegreeBounds,
    PrimeMeridianGreenwichLongitudeUnitIsAngular,
    // §7.4 Prime meridian
    PrimeMeridianNameNonEmpty,
    PrimeMeridianNonGreenwichAllowed,
    ProjectedConventionalAxisOrderEastingFirst,
    ProjectedCrsAxesUseLinearUnit,
    // §9 Projected CRS
    ProjectedCrsBaseCrsIsGeographic,
    ProjectedCrsConventionalAxisDirections,
    ProjectedCrsCsIsCartesian,
    ProjectedCrsHasTwoAxes,
    ProjectedCrsNameNonEmpty,
    ProjectedCrsProjectionIsConversion,
    ProjectedNorthingFirstVariantsExist,
    RegisteredCrsNullAuthorityCodeInvalid,
    ScCrsDomainOfValidityIsExtent,
    ScCrsIdentifierHasAuthorityAndCode,
    ScCrsIsAbstract,
    ScCrsNameNonEmpty,
    ScCrsScopeNonEmpty,
    SphericalCsAngularAxesThenLinear,
    SphericalCsApplicableToGeocentricContext,
    // §25 SphericalCS
    SphericalCsHasThreeAxes,
    StaticCrsDatumAtFixedEpoch,
    // §17 Dynamic / static CRS
    StaticCrsPlateFixedNoEpochRequired,
    TemporalCrsCsIsTemporalCs,
    // §19 Temporal / parametric CRS
    TemporalCrsDatumIsTemporalDatum,
    TemporalCrsHasOneAxis,
    TemporalDatumOriginIsIso8601DateTime,
    TimeAxisMustUseTemporalUnit,
    TransformationAccuracyNonZero,
    TransformationAccuracyPositiveReal,
    TransformationInverseApproximate,
    TransformationInvolvesDatumChange,
    TransformationNad27ToWgs84UsesHelmert,
    UomAngularConvertToRadians,
    UomConversionFactorPositive,
    UomFeetAmbiguityInternationalVsSurvey,
    UomLinearConvertToMetres,
    // §28 UoM
    UomNameNonEmpty,
    UomScaleDimensionless,
    UomTimeConvertToSeconds,
    UtmAxisOrderEastingFirst,
    UtmCommonParametersFalseEastingAndScale,
    UtmFalseEasting500000,
    UtmNorthZoneEpsgRange32601To32660,
    UtmNorthZoneFalseNorthing0,
    UtmScaleFactorAtCentralMeridian0996,
    UtmSouthZoneEpsgRange32701To32760,
    // §29 UTM south zone
    UtmSouthZoneFalseNorthing10000000,
    UtmZoneNumberOneToSixty,
    UtmZoneWidthSixDegrees,
    VertconIsUsVerticalDatumShift,
    VerticalCrsAxisLinearUnit,
    VerticalCrsCsIsVerticalCs,
    // §10 Vertical CRS
    VerticalCrsDatumIsVerticalReferenceFrame,
    VerticalCrsDepthAxisDirectionDown,
    VerticalCrsEpsgRange5000To5999,
    VerticalCrsHasOneAxis,
    VerticalCrsHeightAxisDirectionUp,
    VerticalCrsNameNonEmpty,
    VerticalReferenceFrameAnchorOptional,
    VerticalReferenceFrameGravityRelated,
    VerticalReferenceFrameNameNonEmpty,
    VerticalReferenceFrameRealizationEpochIsIso8601,
};
