//! Contracts re-exports.

pub mod iso_19111;
pub mod iso_19115;
pub mod ogc_sfs;

pub use iso_19111::{
    AngularAxisMustUseAngularUnit,
    AxisAbbreviationNonEmpty,
    AxisAbbreviationUniqueInCs,
    AxisAbbreviationUniqueWithinCs,
    AxisDirectionIsValidCode,
    AxisDirectionMemberOfCodeList,
    AxisMinMaxValueOptional,
    AxisNameNonEmpty,
    AxisOrderChangeRequiresExplicitOperation,
    AxisOrderMustFollowCrsDefinition,
    AxisRangeMeaningExactOrWraparound,
    AxisUnitAppropriateForAxisType,
    CompoundCrsComponentsNonOverlapping,
    CompoundCrsComponentsOrthogonal,
    CompoundCrsEpsgRange6000To6999,
    // §12 Compound CRS
    CompoundCrsHasAtLeastTwoComponents,
    CompoundCrsMinimumTwoComponents,
    CompoundCrsNameNonEmpty,
    CompoundCrsNoTwoHorizontalComponents,
    CompoundCrsNoTwoVerticalComponents,
    CompoundCrsTotalAxisCountIsSumOfComponents,
    CompoundCrsTypicalIs2dPlusVertical,
    ConcatenatedOperationHasAtLeastTwoSteps,
    ConcatenatedOperationMinimumTwoSteps,
    ConcatenatedOperationSourceCrsIsFirstStep,
    ConcatenatedOperationStepsFormAChain,
    ConcatenatedOperationTargetCrsIsLastStep,
    ConversionDefinesMapProjection,
    ConversionHasOperationMethod,
    ConversionHasParameterValues,
    ConversionInverseExists,
    ConversionInvolvesNoDatumChange,
    CoordinateElementAlignedToAxisOrdinalPosition,
    CoordinateEpochDistinctFromFrameReferenceEpoch,
    CoordinateEpochIsDecimalYear,
    CoordinateEpochPositiveFinite,
    CoordinateMetadataApplicableAtSetOrTupleLevel,
    CoordinateMetadataCrsNonNull,
    CoordinateMetadataDynamicCrsRequiresEpoch,
    CoordinateMetadataEpochIsDecimalYear,
    // §23 CoordinateMetadata
    CoordinateMetadataHasCrs,
    CoordinateMetadataStaticCrsEpochShouldBeAbsent,
    CoordinateMetadataValid,
    CoordinateOperationDomainOfValidityOptional,
    CoordinateOperationHasSourceCrs,
    CoordinateOperationHasTargetCrs,
    CoordinateOperationInheritsIdentifiedObjectInterface,
    // §14 Coordinate operations
    CoordinateOperationNameNonEmpty,
    CoordinateOperationVersionOptional,
    // §8 Coordinate system
    CoordinateSystemAxisCountOneToFour,
    CoordinateSystemMaximumFourAxes,
    // §20 Additional value constraints
    CoordinateSystemMinimumOneAxis,
    CoordinateSystemNameNonEmpty,
    CoordinateTupleDimensionMatchesAxes,
    CoordinateTupleElementCountEqualsAxisCount,
    CoordinatesTransformed,
    // §6 CRS general
    CrsConsistsOfCsAndDatum,
    CrsDomainOfValidityExtentTypes,
    CrsDomainOfValidityOptionalImpliesGlobal,
    CrsIdentifierAuthorityNonEmpty,
    CrsIdentifierCodeNonEmpty,
    // §18 Cross-cutting
    CrsIdentityAuthorityPlusCodeUnique,
    CrsIdentityByAuthorityAndCode,
    CrsInheritsIdentifiedObjectInterface,
    CrsMandatoryStringNonNull,
    // Trait operation contracts
    CrsResolved,
    CrsScopeDescribesIntendedUse,
    CrsStringValuesUtf8Encoded,
    CrsTypeMemberOfDefinedTypes,
    CrsValid,
    CsAxisCountMatchesTupleDimensionality,
    CsTypeMemberOfDefinedTypes,
    DatumEnsembleAccuracyPositive,
    // §22 DatumEnsemble
    DatumEnsembleGroupsRelatedDatums,
    DatumEnsembleHasAtLeastTwoMembers,
    DatumEnsembleMemberNoNullEntries,
    DatumEnsembleMembersHomogeneous,
    DatumEnsembleNameNonEmpty,
    DatumEnsembleResolved,
    DatumEnsembleSubMetreRequiresMemberSelection,
    DatumEnsembleWgs84EpsgCode6326,
    DatumInheritsIdentifiedObjectInterface,
    DerivedCrsCsDiffersFromBaseCrsAllowed,
    DerivedCrsDerivingConversionIsConversion,
    // §13 Derived CRS
    DerivedCrsHasBaseCrs,
    DerivedCrsInheritsDatumFromBase,
    DerivedCrsNameNonEmpty,
    DerivedProjectedCrsBaseMustBeProjCrs,
    DifferentCrsCodesRequireExplicitOperation,
    DynamicCrsOmittingEpochIntroducesError,
    DynamicCrsRequiresCoordinateEpoch,
    DynamicReferenceFrameHasFrameReferenceEpoch,
    EllipsoidInverseFlatteningPositiveWhenNonSphere,
    EllipsoidInverseFlatteningZeroMeansSphere,
    EllipsoidIsSphereConsistentWithParameters,
    // §7.3 Ellipsoid
    EllipsoidNameNonEmpty,
    EllipsoidSecondParameterEitherInverseFlatteningOrSemiMinor,
    EllipsoidSemiMajorAxisInMetres,
    EllipsoidSemiMajorAxisPositive,
    EllipsoidSemiMinorAxisInMetres,
    EllipsoidSemiMinorAxisLessThanSemiMajor,
    EllipsoidValid,
    EllipsoidWgs84InverseFlatteningApprox298,
    EngineeringCrsCsTypeFlexible,
    // §11 Engineering CRS
    EngineeringCrsDatumIsEngineeringDatum,
    EngineeringCrsIsLocalContextOnly,
    EngineeringCrsNameNonEmpty,
    EngineeringDatumAnchorOptional,
    EngineeringDatumNameNonEmpty,
    Epsg4326AxisOrderLatFirst,
    Epsg4326LatitudeRangeValid,
    Epsg4326LongitudeRangeValid,
    Epsg4326UsesDatumEnsemble,
    Epsg4978IsWgs84Geocentric,
    Epsg4978XAxisTowardsPrimeMeridian,
    Epsg4978ZAxisTowardsNorthPole,
    Epsg4979HeightUnbounded,
    Epsg4979IsWgs84Geographic3d,
    EpsgAuthorityNameIsEpsg,
    // §16 EPSG registry
    EpsgCodePositiveInteger,
    EpsgCompoundCrsRange6000To6999,
    EpsgGeographicCrsRange4000To4999,
    EpsgProjectedCrsRange20000To32767,
    EpsgVerticalCrsRange5000To5999,
    GeocentricCrsUsesCartesianCs,
    GeodeticCrsCsIsEllipsoidalOrCartesian,
    // §7 Geodetic CRS
    GeodeticCrsDatumIsGeodeticReferenceFrame,
    GeodeticReferenceFrameAnchorOptional,
    GeodeticReferenceFrameHasExactlyOneEllipsoid,
    GeodeticReferenceFrameHasExactlyOnePrimeMeridian,
    // §7.2 Reference frame
    GeodeticReferenceFrameNameNonEmpty,
    GeodeticReferenceFrameRealizationEpochIsIso8601,
    Geographic2dCrsHasTwoAxes,
    // §15 Axis order
    Geographic2dIsoAxisOrderLatitudeFirst,
    Geographic3dCrsHasThreeAxes,
    Geographic3dIsoAxisOrderLatLonHeight,
    // §27 Grid-based datum shifts
    GridBasedDatumShiftUsesExternalFile,
    HelmertConventionMustBeIdentified,
    HelmertConventionsEquivalentOnlyForZeroRotation,
    HelmertCoordinateFrameConvention,
    HelmertEpsgMethodCodes9606And9607,
    HelmertPositionVectorConvention,
    // §26 Helmert conventions
    HelmertSevenParameterStructure,
    IdentifiedObjectAliasNoNullEntries,
    IdentifiedObjectAliasOptionalList,
    IdentifiedObjectIdentifierEntryComplete,
    // §21 IO_IdentifiedObject
    IdentifiedObjectPrimaryNameNonEmpty,
    IdentifiedObjectRemarksOptional,
    IdentifiedObjectRemarksWhenPresentNonNull,
    Igs20IsDynamicDatum,
    Itrf2014IsDynamicDatum,
    Itrf2020IsDynamicDatum,
    LatitudePolesValid,
    LatitudeRangeNegative90To90,
    LinearAxisMustUseLinearUnit,
    LongitudeNegative180Excluded,
    LongitudeRangeNegative180To180,
    MapProjectionFalseOriginFiniteReal,
    MapProjectionScaleFactorPositive,
    MolodenskyBadenkasTenParameter,
    Nad27EnsembleEpsg6267,
    Nadcon5IsUsHorizontalDatumShift,
    Ntv2IsGridHorizontalShift,
    NullAuthorityCodeInvalidForRegisteredCrs,
    OgcAuthorityNameIsOgc,
    OperationMethodFormulaOptional,
    OperationMethodHasParameterList,
    OperationMethodNameNonEmpty,
    OperationParameterNameNonEmpty,
    OperationParameterValueHasUnit,
    OtherAuthorityNamesEsriIgnf,
    ParameterFileStoresFilenameNotValue,
    ParametricAxisMustUseParametricUnit,
    ParametricCrsCsIsParametricCs,
    ParametricCrsDatumIsParametricDatum,
    ParametricCrsHasOneAxis,
    PassThroughOperationCompoundCrsUsage,
    PassThroughOperationDimensionConsistency,
    PassThroughOperationIndexInRange,
    PassThroughOperationInnerOperationNonNull,
    PassThroughOperationModifiedCoordinatesNonEmpty,
    // §24 PassThroughOperation
    PassThroughOperationPreservesSomeAxes,
    PrimeMeridianGreenwichIsZero,
    PrimeMeridianGreenwichLongitudeFinite,
    PrimeMeridianGreenwichLongitudeInDegreeBounds,
    PrimeMeridianGreenwichLongitudeUnitIsAngular,
    // §7.4 Prime meridian
    PrimeMeridianNameNonEmpty,
    PrimeMeridianNonGreenwichAllowed,
    ProjectedConventionalAxisOrderEastingFirst,
    ProjectedCrsAxesUseLinearUnit,
    // §9 Projected CRS
    ProjectedCrsBaseCrsIsGeographic,
    ProjectedCrsConventionalAxisDirections,
    ProjectedCrsCsIsCartesian,
    ProjectedCrsHasTwoAxes,
    ProjectedCrsNameNonEmpty,
    ProjectedCrsProjectionIsConversion,
    ProjectedNorthingFirstVariantsExist,
    RegisteredCrsNullAuthorityCodeInvalid,
    ScCrsDomainOfValidityIsExtent,
    ScCrsIdentifierHasAuthorityAndCode,
    ScCrsIsAbstract,
    ScCrsNameNonEmpty,
    ScCrsScopeNonEmpty,
    SphericalCsAngularAxesThenLinear,
    SphericalCsApplicableToGeocentricContext,
    // §25 SphericalCS
    SphericalCsHasThreeAxes,
    StaticCrsDatumAtFixedEpoch,
    // §17 Dynamic / static CRS
    StaticCrsPlateFixedNoEpochRequired,
    TemporalCrsCsIsTemporalCs,
    // §19 Temporal / parametric CRS
    TemporalCrsDatumIsTemporalDatum,
    TemporalCrsHasOneAxis,
    TemporalDatumOriginIsIso8601DateTime,
    TimeAxisMustUseTemporalUnit,
    TransformationAccuracyNonZero,
    TransformationAccuracyPositiveReal,
    TransformationInverseApproximate,
    TransformationInvolvesDatumChange,
    TransformationNad27ToWgs84UsesHelmert,
    UomAngularConvertToRadians,
    UomConversionFactorPositive,
    UomFeetAmbiguityInternationalVsSurvey,
    UomLinearConvertToMetres,
    // §28 UoM
    UomNameNonEmpty,
    UomScaleDimensionless,
    UomTimeConvertToSeconds,
    UtmAxisOrderEastingFirst,
    UtmCommonParametersFalseEastingAndScale,
    UtmFalseEasting500000,
    UtmNorthZoneEpsgRange32601To32660,
    UtmNorthZoneFalseNorthing0,
    UtmScaleFactorAtCentralMeridian0996,
    UtmSouthZoneEpsgRange32701To32760,
    // §29 UTM south zone
    UtmSouthZoneFalseNorthing10000000,
    UtmZoneNumberOneToSixty,
    UtmZoneWidthSixDegrees,
    VertconIsUsVerticalDatumShift,
    VerticalCrsAxisLinearUnit,
    VerticalCrsCsIsVerticalCs,
    // §10 Vertical CRS
    VerticalCrsDatumIsVerticalReferenceFrame,
    VerticalCrsDepthAxisDirectionDown,
    VerticalCrsEpsgRange5000To5999,
    VerticalCrsHasOneAxis,
    VerticalCrsHeightAxisDirectionUp,
    VerticalCrsNameNonEmpty,
    VerticalReferenceFrameAnchorOptional,
    VerticalReferenceFrameGravityRelated,
    VerticalReferenceFrameNameNonEmpty,
    VerticalReferenceFrameRealizationEpochIsIso8601,
};

pub use ogc_sfs::{
    Area0DReturnsZero, Area1DReturnsZero, Area2DReturnsPositive, AreaEmptyGeometryIsZero,
    AreaNonNegative, AreaUnitsSquaredSrsUnits, AsBinaryMethodDefined, AsBinaryReturnsWkb,
    AsTextMethodDefined, AsTextReturnsWkt, BoundaryOfBoundaryIsEmpty,
    BufferNegativeDistanceShrinks, BufferPositiveDistanceIncreasesArea, BufferResultIsValid,
    BufferReturnsContainingGeometry, BufferZeroContainsSelf, CentroidDefinedForAll,
    CentroidReturnsPoint, CentroidWithinConvexHull, CentroidXIsFinite, CentroidYIsFinite,
    CollectionCoordDimMatchesComponents, CollectionGeometryNIndexed, CollectionGeometryNNeverNull,
    CollectionNumGeometriesCount, CollectionNumGeometriesNonNegative,
    ConformanceClass0RequiresSevenTypes, ConformanceClass0RequiresWkbWkt,
    ConformanceClass1AddsPredicates, ConformanceClass1AddsSetOps, ContainsDe9ImPattern,
    ContainsIsInverseOfWithin, ContainsIsNotSymmetric, ConvexHullContainsSelf,
    ConvexHullIdempotent, ConvexHullOfConvexPolygonIsSelf, ConvexHullReturnsSmallestConvex,
    Coord2DMPosition, Coord2DPosition, Coord3DMPosition, Coord3DPosition, Coord3DZIsElevation,
    CoordDimUniformInGeometry, CoordDimensionalityIsConsistent, CoordDimensionalityUniform,
    CoordMIsFiniteWhenPresent, CoordMIsMeasure, CoordXIsFinite, CoordYIsFinite,
    CoordZIsFiniteWhenPresent, CoveredByIsInverseOfCovers, CoversDe9ImPattern, CoversImpliesWithin,
    CrossesDe9ImPattern, CrossesDimIntersectionLessThanMax, CrossesDimensionConstraint,
    CrossesIsNotSymmetric, De9ImCellValues, De9ImInteriorBoundaryExteriorAxes, De9ImMatrixDefined,
    De9ImRelatePatternIsNineChars, DifferenceAsymmetric, DifferenceDimensionAtMostSelf,
    DifferenceDisjointFromSubtracted, DifferenceSubsetOfSelf, DimensionConsistencyInHierarchy,
    DisjointDe9ImPattern, DisjointIsInverseOfIntersects, DisjointIsSymmetric, DistanceInSrsUnits,
    DistanceNonNegative, DistanceSymmetric, DistanceTriangleInequality,
    DistanceZeroIffIntersecting, EmptyGeometryBoundaryIsEmpty,
    EmptyGeometryBoundaryIsEmptyGeometry, EmptyGeometryEnvelopeIsEmpty, EmptyHandlingConsistent,
    EnvelopeEmptyWhenGeometryEmpty, EnvelopeIsPointWhenDegenerate, EnvelopeIsPolygon,
    EqualsDe9ImPattern, EqualsIsReflexive, EqualsIsSymmetric, EwkbBaseTypeCodeMasked,
    EwkbSridIsUint32, EwkbSridPresent, GeometryBoundaryDefinedPerType,
    GeometryCollectionAllComponentsValid, GeometryCollectionBoundaryMod2Rule,
    GeometryCollectionHeterogeneousAllowed, GeometryCollectionIsSimpleAllSimple,
    GeometryCollectionMayBeEmpty, GeometryDimension0ForPoint, GeometryDimension1ForLine,
    GeometryDimension2ForSurface, GeometryDimensionMinus1WhenEmpty, GeometryEnvelopeReturnsMbr,
    GeometryHasSrs, GeometryIsEmptyPredicate, GeometryIsSimpleAndIsValidDistinct,
    GeometryIsSimplePredicate, GeometryIsValidPredicate, GeometrySridReturnsInteger,
    GeometrySrsNotNull, GeometryTypeMatchesConcreteName, GeometryTypeReturnsString,
    IntersectionDimensionAtMostMin, IntersectionIsCommutative, IntersectionOfDisjointIsEmpty,
    IntersectionSubsetOfBothInputs, IntersectsAtLeastOneSharedPoint, IntersectsIsNotDisjoint,
    IntersectsIsSymmetric, IsEmptyFalseForNonEmpty, IsEmptyTrueForEmpty,
    IsSimpleNoSelfIntersection, IsValidImpliesSubComponentsValid, IsValidWellFormed,
    Length0DReturnsZero, Length1DReturnsPositive, Length2DReturnsZero, LengthEmptyGeometryIsZero,
    LengthInSrsUnits, LengthNonNegative, LineStringAdjacentPointsDistinct,
    LineStringBoundaryIsEndpoints, LineStringClosedBoundaryEmpty, LineStringClosedEqualsLinearRing,
    LineStringEndPointIsPointNLast, LineStringHasTwoOrMorePoints, LineStringIsClosedStartEqualsEnd,
    LineStringIsRingImpliesClosedAndSimple, LineStringMinimumTwoPositions,
    LineStringNonClosedBoundaryIsEndpointMultiPoint, LineStringNumPointsMatchesCoordCount,
    LineStringOpenBoundaryTwoPoints, LineStringPointNInRange, LineStringSimpleNoSelfIntersection,
    LineStringStartPointIsPointNZero, LinearRingBoundaryIsEmpty, LinearRingBoundaryIsEmptySet,
    LinearRingFirstPositionEqualsLast, LinearRingIsClosedLineString, LinearRingIsSimple,
    LinearRingMinimumFourPositions, LinearRingNonDegenerate,
    MultiLineStringComponentsAreLineStrings, MultiLineStringIsClosedAllClosed2,
    MultiLineStringMayBeEmpty, MultiLineStringSimpleWhenIntersectAtEndpointsOnly,
    MultiPointComponentsArePoints, MultiPointMayBeEmpty, MultiPointSimpleWhenNoTwoEqual,
    MultiPolygonBoundariesDontOverlap, MultiPolygonBoundariesTouchAtPoints,
    MultiPolygonBoundaryIsAllRings, MultiPolygonComponentsArePolygons,
    MultiPolygonInteriorsDisjoint, MultiPolygonMayBeEmpty, OverlapsDe9ImPattern2D,
    OverlapsDe9ImPatternLowDim, OverlapsDimensionConstraint, OverlapsIsSymmetric, PointAlwaysValid,
    PointBoundaryIsEmpty, PointEmptyHasNoCoords, PointEmptyIsEmpty, PointMDefinedWhenMPresent,
    PointOnSurfaceDefinedForAll, PointOnSurfaceIsOnGeometry, PointOnSurfaceReturnsPoint,
    PointXIsFinite, PointXReturnsXOrdinate, PointYIsFinite, PointYReturnsYOrdinate,
    PointZDefinedWhen3D, PointZIsFiniteWhenPresent, PolygonBoundaryIsAllRings,
    PolygonExteriorIsCCW, PolygonExteriorIsLinearRing, PolygonExteriorRingNeverNull,
    PolygonHasExactlyOneExteriorRing, PolygonHoleCountNonNegative, PolygonHolesAreCW,
    PolygonHolesDontContainEachOther, PolygonHolesInsideExterior, PolygonInteriorRingNInRange,
    PolygonInteriorRingNReturnsHole, PolygonInteriorRingsAreLinearRings,
    PolygonNoRingSelfIntersects, PolygonNumInteriorRingsNonNegative, PolygonRingsDontCross,
    PolygonRingsDontTouchAlongSegment, PolygonRingsTouchAtPoints, RelatePatternCharacters,
    RelatePatternLength9, RelateReturnsBooleanMatchingPattern, SridAssignedAtConstruction,
    SridIsInteger, SridNonNegative, SrsConsistentInCollection,
    SymDifferenceEqualsUnionMinusIntersection, SymDifferenceIsCommutative, TouchesDe9ImPattern,
    TouchesInteriorsDisjoint, TouchesIsSymmetric, UnionDimensionIsMax,
    UnionEqualsIntersectionPlusSymDifference, UnionIsAssociative, UnionIsCommutative,
    UnionSupersetOfBothInputs, WithinDe9ImPattern, WithinIsInverseOfContains, WithinIsNotSymmetric,
    WkbByteOrderBigEndian, WkbByteOrderLittleEndian, WkbByteOrderMarkerPresent,
    WkbByteOrderMarkerTwoValues, WkbCoordinateIsDouble, WkbCoordinatesByteOrderMatches,
    WkbCountFieldsAreUint32, WkbLengthValid, WkbMVariant, WkbPointLength21Bytes2D, WkbRingHasCount,
    WkbRoundTrip, WkbSubGeometriesAreCompleteBlobs, WkbTypeCodeGeometryCollection,
    WkbTypeCodeLineString, WkbTypeCodeMultiLineString, WkbTypeCodeMultiPoint,
    WkbTypeCodeMultiPolygon, WkbTypeCodePoint, WkbTypeCodePolygon, WkbTypeCodeValid, WkbZMVariant,
    WkbZVariant, WktCoordinateListInParens, WktCoordsSeparatedBySpace,
    WktDimensionTagPrecedesParens, WktEmptyApplicableToAllTypes, WktEmptyGeometry,
    WktGeometryCollectionProduction, WktKeywordCaseInsensitive, WktKeywordValid,
    WktLineStringProduction, WktMVariant, WktMultiLineStringProduction, WktMultiPointProduction,
    WktMultiPolygonProduction, WktNestingForMultiTypes, WktPointProduction,
    WktPolygonExteriorFirstRing, WktPolygonProduction, WktPositionsSeparatedByComma,
    WktRingsParenthesized, WktRingsSeparatedByComma, WktRoundTrip, WktZMVariant, WktZVariant,
};

pub use iso_19115::{
    CiAddressAdministrativeAreaOptional, CiAddressCityOptional, CiAddressCountryIsIso3166,
    CiAddressCountryOptional, CiAddressDeliveryPointOptional, CiAddressEmailOptional,
    CiAddressPostalCodeOptional, CiCitationAlternateTitleOptional,
    CiCitationCollectiveTitleOptional, CiCitationDateMandatory, CiCitationEditionDateOptional,
    CiCitationEditionOptional, CiCitationIdentifierOptional, CiCitationIsbnFormatValid,
    CiCitationIssnFormatValid, CiCitationOtherDetailsOptional, CiCitationPresentationFormOptional,
    CiCitationResponsiblePartyOptional, CiCitationSeriesOptional, CiCitationTitleMandatory,
    CiCitationTitleNonEmpty, CiContactAddressOptional, CiContactHoursOfServiceOptional,
    CiContactInstructionsOptional, CiContactOnlineResourceOptional, CiContactPhoneOptional,
    CiDateTypeAdopted, CiDateTypeCodeMandatory, CiDateTypeCreation, CiDateTypeDeprecated,
    CiDateTypeDistribution, CiDateTypeExpiry, CiDateTypeInForce, CiDateTypeLastRevision,
    CiDateTypeLastUpdate, CiDateTypeNextUpdate, CiDateTypePublication, CiDateTypeReleased,
    CiDateTypeRevision, CiDateTypeSuperseded, CiDateTypeUnavailable, CiDateTypeValidityBegins,
    CiDateTypeValidityExpires, CiDateValueMandatory, CiIndividualContactInfoOptional,
    CiIndividualNameOptional, CiIndividualNameOrPositionRequired, CiIndividualPositionNameOptional,
    CiOnlineFunctionBrowseGraphic, CiOnlineFunctionBrowsing, CiOnlineFunctionCompleteMetadata,
    CiOnlineFunctionDownload, CiOnlineFunctionEmailService, CiOnlineFunctionFileAccess,
    CiOnlineFunctionInformation, CiOnlineFunctionOfflineAccess, CiOnlineFunctionOrder,
    CiOnlineFunctionSearch, CiOnlineFunctionUpload, CiOnlineResourceApplicationProfileOptional,
    CiOnlineResourceDescriptionOptional, CiOnlineResourceFunctionOptional,
    CiOnlineResourceLinkageMandatory, CiOnlineResourceLinkageValidUrl,
    CiOnlineResourceNameOptional, CiOnlineResourceProtocolOptional,
    CiOrganisationContactInfoOptional, CiOrganisationIndividualOptional,
    CiOrganisationNameOptional, CiPartyIsAbstract, CiResponsibilityExtentOptional,
    CiResponsibilityPartyMandatory, CiResponsibilityPartyNameNonNull,
    CiResponsibilityRoleMandatory, CiRoleAuthor, CiRoleCoAuthor, CiRoleCollaborator,
    CiRoleContributor, CiRoleCustodian, CiRoleDistributor, CiRoleEditor, CiRoleFunder,
    CiRoleMediator, CiRoleOriginator, CiRoleOwner, CiRolePointOfContact,
    CiRolePrincipalInvestigator, CiRoleProcessor, CiRolePublisher, CiRoleResourceProvider,
    CiRoleRightsHolder, CiRoleSponsor, CiRoleStakeholder, CiRoleUser, CiTelephoneFacsimile,
    CiTelephoneNumberMandatory, CiTelephoneNumberNonEmpty, CiTelephoneSms, CiTelephoneTypeVoice,
    DqAbsoluteExternalPositionalAccuracy, DqCompletenessCommission, DqCompletenessOmission,
    DqConceptualConsistency, DqDataQualityReportOptional, DqDataQualityScopeMandatory,
    DqDataQualityStandaloneOptional, DqDomainConsistency, DqFormatConsistency,
    DqGriddedDataPositionalAccuracy, DqNonQuantitativeAttributeCorrectness,
    DqQuantitativeAttributeAccuracy, DqRelativeInternalPositionalAccuracy, DqTemporalConsistency,
    DqTemporalValidity, DqThematicClassificationCorrectness, DqTopologicalConsistency,
    DsAssociationTypeCrossReference, DsAssociationTypeIsComposedOf,
    DsAssociationTypeLargerWorkCitation, DsAssociationTypePartOfSeamlessDatabase,
    DsAssociationTypeRevisionOf, DsInitiativeTypeMission, DsInitiativeTypePlatform,
    DsInitiativeTypeProject, ExBboxEastBoundMandatory, ExBboxExtentTypeCodeOptional,
    ExBboxLatitudeRange, ExBboxLongitudeRange, ExBboxNorthBoundMandatory,
    ExBboxSouthBoundMandatory, ExBboxSouthLeNorth, ExBboxWestBoundMandatory,
    ExBboxWestLeEastOrAntimeridian, ExBoundingPolygonAtLeastOneGeometry,
    ExBoundingPolygonExtentTypeCodeOptional, ExBoundingPolygonGeometryIsValid,
    ExBoundingPolygonPolygonMandatory, ExExtentAtLeastOneElementRequired,
    ExExtentDescriptionOptional, ExExtentGeographicElementConditional,
    ExExtentTemporalElementOptional, ExExtentVerticalElementOptional,
    ExTemporalExtentExtentMandatory, ExTemporalExtentPeriodBeginLeEnd, ExVerticalExtentCrsOptional,
    ExVerticalExtentMaximumMandatory, ExVerticalExtentMinLeMax, ExVerticalExtentMinimumMandatory,
    Iso19115AllMandatoryElementsPresent, Iso19115CitationTitleNeverEmpty,
    Iso19115ConditionalElementsTriggered, Iso19115ContactPartyNameNonNull,
    Iso19115CountryCodeIso3166, Iso19115DateIso8601Format, Iso19115EnumerationValuesValid,
    Iso19115LanguageCodeIso6392, Iso19115MultiplicityConstraintsMet,
    Iso19115ProcessStepDescriptionNeverEmpty, LiLineageAdditionalDocumentationOptional,
    LiLineageAtLeastOneProvided, LiLineageProcessStepOptional, LiLineageScopeOptional,
    LiLineageSourceOptional, LiLineageStatementConditional, LiProcessStepDateTimeOptional,
    LiProcessStepDescriptionMandatory, LiProcessStepDescriptionNonEmpty,
    LiProcessStepProcessorOptional, LiProcessStepRationaleOptional, LiProcessStepReferenceOptional,
    LiProcessStepScopeOptional, LiProcessStepSourceOptional, LiSourceCitationOptional,
    LiSourceDescriptionConditional, LiSourceDescriptionOrCitationRequired,
    LiSourceReferenceSystemOptional, LiSourceSpatialResolutionOptional, LiSourceStepOptional,
    MdAssociatedResourceAssociationTypeMandatory, MdAssociatedResourceInitiativeTypeOptional,
    MdAssociatedResourceMetadataRefConditional, MdAssociatedResourceNameConditional,
    MdAssociatedResourceNameOrMetaRefRequired, MdBrowseGraphicFileDescriptionOptional,
    MdBrowseGraphicFileNameMandatory, MdBrowseGraphicFileNameNonEmpty,
    MdBrowseGraphicFileTypeOptional, MdBrowseGraphicLinkageOptional, MdCharsetArabic,
    MdCharsetBig5, MdCharsetCyrillic, MdCharsetEucJp, MdCharsetGb2312, MdCharsetGreek,
    MdCharsetHebrew, MdCharsetLatin1, MdCharsetLatin2, MdCharsetLatin5, MdCharsetShiftJis,
    MdCharsetUcs2, MdCharsetUcs4, MdCharsetUsAscii, MdCharsetUtf8, MdCharsetUtf16, MdCharsetUtf32,
    MdClassificationConfidential, MdClassificationForOfficialUseOnly,
    MdClassificationLimitedDistribution, MdClassificationProtected, MdClassificationRestricted,
    MdClassificationSecret, MdClassificationSensitiveButUnclassified, MdClassificationTopSecret,
    MdClassificationUnclassified, MdConstraintsApplicationScopeOptional,
    MdConstraintsUseLimitationOptional, MdDataIdentificationCharacterSetConditional,
    MdDataIdentificationExtentConditional, MdDataIdentificationLanguageConditional,
    MdDataIdentificationSpatialResolutionOptional, MdDataIdentificationSupplementalInfoOptional,
    MdDataIdentificationTopicCategoryConditional, MdDimensionNameColumn, MdDimensionNameMandatory,
    MdDimensionNameRow, MdDimensionNameTime, MdDimensionNameVertical,
    MdDimensionResolutionOptional, MdDimensionSizeMandatory, MdDimensionSizePositive,
    MdDistributionAtLeastOneElement, MdDistributionDistributorOptional,
    MdDistributionFormatOptional, MdDistributionTransferOptionsOptional,
    MdDistributorContactMandatory, MdDistributorFormatOptional, MdDistributorOrderProcessOptional,
    MdDistributorTransferOptionsOptional, MdFormatAmendmentNumberOptional,
    MdFormatDistributorOptional, MdFormatFileDecompressionOptional, MdFormatMediumOptional,
    MdFormatSpecificationCitationMandatory, MdGridSpatialRepAxisDimensionProperties,
    MdGridSpatialRepCellGeometry, MdGridSpatialRepNumberOfDimensions,
    MdGridSpatialRepTransformationAvailable, MdIdentificationAbstractMandatory,
    MdIdentificationAbstractNonEmpty, MdIdentificationCitationMandatory,
    MdIdentificationCreditOptional, MdIdentificationDescriptiveKeywordsOptional,
    MdIdentificationGraphicOverviewOptional, MdIdentificationPointOfContactOptional,
    MdIdentificationPurposeOptional, MdIdentificationResourceConstraintsOptional,
    MdIdentificationResourceFormatOptional, MdIdentificationResourceMaintenanceOptional,
    MdIdentificationStatusOptional, MdKeywordTypeDataCentre, MdKeywordTypeDiscipline,
    MdKeywordTypeFeatureType, MdKeywordTypeInstrument, MdKeywordTypePlace, MdKeywordTypePlatform,
    MdKeywordTypeProcess, MdKeywordTypeProduct, MdKeywordTypeProject, MdKeywordTypeService,
    MdKeywordTypeStratum, MdKeywordTypeSubTopicCategory, MdKeywordTypeTaxon, MdKeywordTypeTemporal,
    MdKeywordTypeTheme, MdKeywordsKeywordClassOptional, MdKeywordsKeywordMandatory,
    MdKeywordsThesaurusNameOptional, MdKeywordsTypeOptional,
    MdLegalConstraintsAccessConstraintsOptional, MdLegalConstraintsOtherConstraintsConditional,
    MdLegalConstraintsUseConstraintsOptional, MdMaintenanceContactOptional,
    MdMaintenanceDateOptional, MdMaintenanceFrequencyAnnually, MdMaintenanceFrequencyAsNeeded,
    MdMaintenanceFrequencyContinual, MdMaintenanceFrequencyDaily, MdMaintenanceFrequencyIrregular,
    MdMaintenanceFrequencyMandatory, MdMaintenanceFrequencyMonthly,
    MdMaintenanceFrequencyNotPlanned, MdMaintenanceFrequencyQuarterly,
    MdMaintenanceFrequencyUnknown, MdMaintenanceFrequencyWeekly, MdMaintenanceNoteOptional,
    MdMaintenanceScopeOptional, MdMaintenanceUserDefinedFreqConditional,
    MdMediumDensityUnitsConditional, MdMediumVolumesOptional, MdMetadataCharacterSetConditional,
    MdMetadataConstraintsOptional, MdMetadataContactMandatory, MdMetadataContactPartyNameNonNull,
    MdMetadataDataQualityInfoOptional, MdMetadataDateInfoMandatory,
    MdMetadataDistributionInfoOptional, MdMetadataFileIdentifierOptional,
    MdMetadataHierarchyLevelNameMatchesLevel, MdMetadataHierarchyLevelScopeCode,
    MdMetadataIdentificationInfoMandatory, MdMetadataLanguageConditional, MdMetadataLocaleOptional,
    MdMetadataMaintenanceOptional, MdMetadataParentIdentifierOptional,
    MdMetadataReferenceSystemInfoOptional, MdMetadataResourceLineageOptional,
    MdMetadataSpatialRepresentationInfoOptional, MdMetadataStandardNameOptional,
    MdMetadataStandardVersionOptional, MdProgressCodeAccepted, MdProgressCodeCompleted,
    MdProgressCodeDeprecated, MdProgressCodeFinal, MdProgressCodeHistoricalArchive,
    MdProgressCodeNotAccepted, MdProgressCodeObsolete, MdProgressCodeOnGoing,
    MdProgressCodePending, MdProgressCodePlanned, MdProgressCodeProposed, MdProgressCodeRequired,
    MdProgressCodeRetired, MdProgressCodeSuperseded, MdProgressCodeTentative,
    MdProgressCodeUnderDevelopment, MdProgressCodeValid, MdProgressCodeWithdrawn,
    MdReferenceSystemIdentifierOptional, MdReferenceSystemTypeOptional,
    MdRepresentativeFractionDenominatorMandatory, MdRepresentativeFractionDenominatorPositive,
    MdResolutionDistanceIsPositive, MdResolutionEquivalentScaleOrDistance,
    MdResolutionScaleImpliesSmallIsCoarse, MdRestrictionConfidentialCode,
    MdRestrictionCopyrightCode, MdRestrictionInConfidenceCode,
    MdRestrictionIntellectualPropertyCode, MdRestrictionLicenceCode,
    MdRestrictionLicenceDistributorCode, MdRestrictionLicenceEndUserCode,
    MdRestrictionLicenceUnrestrictedCode, MdRestrictionOtherRestrictionsCode,
    MdRestrictionPatentCode, MdRestrictionPatentPendingCode, MdRestrictionPrivateCode,
    MdRestrictionRestrictedCode, MdRestrictionSbuCode, MdRestrictionStatutoryCode,
    MdRestrictionTrademarkCode, MdRestrictionUnrestrictedCode, MdScopeAttribute,
    MdScopeAttributeType, MdScopeCollectionSession, MdScopeDataset, MdScopeDimensionGroup,
    MdScopeFeature, MdScopeFeatureType, MdScopeFieldSession, MdScopeInitiative, MdScopeModel,
    MdScopeNonGeographicDataset, MdScopeSeries, MdScopeService, MdScopeSoftware, MdScopeTile,
    MdSecurityConstraintsClassSystemOptional, MdSecurityConstraintsClassificationMandatory,
    MdSecurityConstraintsHandlingDescOptional, MdSecurityConstraintsUserNoteOptional,
    MdSpatialRepTypeGrid, MdSpatialRepTypeStereoModel, MdSpatialRepTypeTextTable,
    MdSpatialRepTypeTin, MdSpatialRepTypeVector, MdSpatialRepTypeVideo, MdTopicCategoryBiota,
    MdTopicCategoryBoundaries, MdTopicCategoryClimatologyMeteorologyAtmosphere,
    MdTopicCategoryDisaster, MdTopicCategoryEconomy, MdTopicCategoryElevation,
    MdTopicCategoryEnvironment, MdTopicCategoryExtraTerrestrial, MdTopicCategoryFarming,
    MdTopicCategoryGeoscientificInformation, MdTopicCategoryHealth,
    MdTopicCategoryImageryBaseMapsEarthCover, MdTopicCategoryInlandWaters,
    MdTopicCategoryIntelligenceMilitary, MdTopicCategoryLocation, MdTopicCategoryOceans,
    MdTopicCategoryPlanningCadastre, MdTopicCategorySociety, MdTopicCategoryStructure,
    MdTopicCategoryTransportation, MdTopicCategoryUtilitiesCommunication,
    MdTransferOptionsOfflineOptional, MdTransferOptionsOnlineOptional,
    MdTransferOptionsSizePositive, MdVectorSpatialRepGeometricObjects,
    MdVectorSpatialRepTopologyLevel, PtLocaleCharacterEncodingMandatory, PtLocaleCountryOptional,
    PtLocaleLanguageCodeThreeLetterLowercase, PtLocaleLanguageMandatory,
};
